### ISSUE TITLE
ER GD Badge post modified and other dates

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1017]
Provide date formatter ?https://wpgeodirectory.com/support/topic/shortcode-for-show-recently-updated-badge/#post-522594

**Comment by morazalzar** [comment]
OK thanks. waiting for news.

**Comment by 1naveengiri** [comment]
Fixed merged in master already
https://github.com/AyeCode/geodirectory/pull/1028/commits/c1c6c49a11b8cd8faa92107a0656607260a3ef35#diff-ab6f0d3891834ae358239cea14ac2dbfR162
