### ISSUE TITLE
Conflict between two different client requests 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1023]
https://wpgeodirectory.com/support/topic/field-description-is-being-html-escaped-on-save/
https://wpgeodirectory.com/support/topic/custom-field-description-content-changes-upon-save/#post-513451

Fix for both request creating conflict with one another.

**Comment by kprajapatii** [comment]
HTML tags causes issue in field description. So we sanitized field description before saving to prevent HTML tags.

But by using PHP snippet you can add html tags. See https://wpgeodirectory.com/support/topic/link-to-legal-documents/#post-522528
