### ISSUE TITLE
Wording - Change "Restrict wp-admin" to "Restricted from wp-admin"

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#104]
Change "Restrict wp-admin" to "Restricted from wp-admin"

![image](https://user-images.githubusercontent.com/114659/37513241-d1ca46e2-2904-11e8-9c45-dc1201a49f45.png)

The help text is clearer than the form field.

![screenshot 2018-03-16 at 10 31 52 am](https://user-images.githubusercontent.com/114659/37513441-64b5416e-2905-11e8-9484-b7d329b069e4.png)

**Comment by Stiofan** [comment]
i think the shot ver is ok.
