### ISSUE TITLE
Mobile styles for dashboard forms

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#105]
Recommend 'normaiing' style of forms...font size and form field size, between desktop and mobile.

desktop
![screenshot 2018-03-16 at 11 25 57 am](https://user-images.githubusercontent.com/114659/37515983-028b122c-290d-11e8-9ead-f757fa739cbe.png)

mobile
![screenshot 2018-03-16 at 11 26 11 am](https://user-images.githubusercontent.com/114659/37515990-079e47f2-290d-11e8-8cc9-3cbcf7e0e4ff.png)

**Comment by Stiofan** [comment]
For the most part we are using the WP default styles, i have added some tweaks for the tool tips and the dropdown selects.
