### ISSUE TITLE
Add link to "Pages" settings

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#106]
It would be "nice to have" a clickable link wherever the "Pages" are referenced, to both fronend and backend.  It does show as a clickable link in the Status output, which is great, and make me want to open the status page directly, which perhaps we will be when servicing sites.

It would also be nice if it displayed the Page Title and the Slug.

Maybe the link would only show after save, that would be fine, too.

![screenshot 2018-03-16 at 12 38 39 pm](https://user-images.githubusercontent.com/114659/37518869-4c65e07a-2917-11e8-911c-99c550188891.png)

![screenshot 2018-03-16 at 12 41 57 pm](https://user-images.githubusercontent.com/114659/37518912-811bfb9c-2917-11e8-9a0c-5e49d8260460.png)

**Comment by Stiofan** [comment]
Got a visual of how you imagine this working?

**Comment by alexrollin** [comment]
In the drop down it could shown the Page Name, as is it does now, followed by the slug.
"Edit" - link to edit the page in the backend. Could be an icon.
"Link - link to the page in the front end. Could be an icon.
`
Add listing page     (?) (Edit)(Link) (Dropdown - Page name - Slug)
`

**Comment by alexrollin** [comment]
I found an example in the WC Vendors page settings:
Features
X to de-select page
Edit Page button 
View Page button

Of note, the description for the field is responsive to active changes in the viewport.

![image](https://user-images.githubusercontent.com/114659/39121710-b5ddc0ce-46f2-11e8-9212-fa37a6832573.png)

**Comment by Stiofan** [comment]
edit/view links added to page settings.
Edit links already exist in help popup on status page.
