### ISSUE TITLE
Allow admin to select listing owner from list of all users, not only authors or above

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#107]
In backend, when editing a listing, allow admin to select listing owner from list of all users, not only authors or above.
Currently need to set a subscriber temporarily to author to be able to assign.

**Comment by Stiofan** [comment]
@kprajapatii we would need to make this a ajax user picker, maybe load admin/editors by default and ajax search for other users? If you have a better idea let me know

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/pull/141
