### ISSUE TITLE
Job Board task

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1087]
We need a few changes for job boards.

1. We need a "time ago" feature for post date. Ideally, we would add this to the badge widget and just have a class or something that changes the date to: 4 hours ago, 3 days ago, 2 weeks ago.

2. We will need to be able to use advanced search to filter listings by post date, such as: today, since yesterday, less than 7 days, less than 30 days.

Ping me if u have any questions.

**Comment by kprajapatii** [comment]
#1 Fixed See https://github.com/AyeCode/geodirectory/commit/2be48847647ec7676cc395307919950e5681f51f#diff-1415a92dcbd5f6c4420dad75d69ace4c

Example: https://ppldb.com/kiran/places/
