### ISSUE TITLE
ER - Able to set default zoom level on add listing page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1098]
ER - Add field to address custom field to set add listing page zoom level of the map.

We have had several requests for changing the way that the default location is populated on the add listing page. People want it to be easier for new users to set a location.

Instead of setting the location dropdowns to null, one thing that has worked and helped people is to change the default zoom on the map so that users can more easily drag the marker to their own country and city more quickly, without having to zoom out first.

https://wpgeodirectory.com/support/topic/change-default-location-to-worldwide/#post-534673
https://wordpress.org/support/topic/zoom-in-on-the-map-at-the-time-of-geocoding-the-address/

```
// Set add listing map default zoom level
add_action('geodir_address_extra_listing_fields', function( $cf ) {
  
	global $gd_post,$mapzoom;
	if(empty($gd_post->mapzoom)){
		$mapzoom = 16;
	}
});
```

Added to docs 
https://wpgeodirectory.com/docs-v2/design/maps/#customizing

**Comment by kprajapatii** [comment]
Fixed
