### ISSUE TITLE
ER Infinite Scroll - Load more on Archive and Search pages

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1119]
https://wpgeodirectory.com/support/topic/replace-pagination-with-show-more-button-ajax-post-loading/#post-536979

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/infinite-scroll-for-map/#post-539797

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1597207494/23035/

**Comment by Stiofan** [comment]
@alexrollin is there not already 3rpd party plugins that work with this?

**Comment by alexrollin** [comment]
Yes

**Comment by kprajapatii** [comment]
Duplicate and partially fixed #https://github.com/AyeCode/geodir_advance_search_filters-v2/issues/172
