### ISSUE TITLE
Bug - Remove show_logo from Shortcode Builder

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1137]
![image](https://user-images.githubusercontent.com/114659/78624234-74950f80-7889-11ea-8d60-b5763d0f14ef.png)

This option is no longer needed, is deprecated, and should be removed from default content templates also.

It is causing confusion about how to remove the logo.

Further, the fallback types should have the tooltip changed to say "...or 0 for no fallback images."

![image](https://user-images.githubusercontent.com/114659/78624310-a27a5400-7889-11ea-9532-aeacc54430f9.png)

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/commit/134770eb1410ba0108758121be5d3f37ec0d017e

**Comment by 1naveengiri** [comment]
Already merged
