### ISSUE TITLE
Tooltip docs link to open in new tab

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#116]
New tooltip popup documentation link is great!

Right now the link opens in the same window, so users will browse away from their settings.
Recommend it open in a new window so users can 'keep their place'

![screenshot 2018-03-19 at 10 59 50 am](https://user-images.githubusercontent.com/114659/37589616-16270dc6-2b66-11e8-8932-7d520baab27c.png)

**Comment by Stiofan** [comment]
done
