### ISSUE TITLE
Styling for popups

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#117]
Right now we have a basic link. Looks like the 'visited' keep sit blue, which is good.

![screenshot 2018-03-19 at 10 59 50 am](https://user-images.githubusercontent.com/114659/37589639-2cb44a5e-2b66-11e8-9aff-0807a1fb920c.png)

Recommend additional styling, and an icon to indicate that the link is external and will open in a new tab.

![google maps api key 2](https://user-images.githubusercontent.com/114659/37589664-3d731c8a-2b66-11e8-8ae0-845f25d15e48.jpg)

**Comment by Stiofan** [comment]
i have set it to display on its own line, and open in a new window and also added a icon to denote it will open externally.
