### ISSUE TITLE
Add option to limit number of listings per user

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1171]
Add a CPT setting to be able to limit the number of listings a user can have.
We need to be able to limit FREE and PAID listings differently, and maybe a total, we need suggestions on the best way to do this?

**Comment by kprajapatii** [comment]
= Add three options in CPT settings
- Max No. of Free Listings ( When Pricing Manager  active )
- Max No. of Paid Listings ( When Pricing Manager active  )
- Total No. of Listings ( When Core or Pricing Manager active )

= Applicable at front-end and non admin users only

= If limit is reached then user not allowed to claim new listing

= Use filters to extend limitation for specific user ids or for specific user roles

**Comment by 1naveengiri** [comment]
Just to add one more viewpoint. 
With three settings, suppose the customer has given a total no of listing to a CPT. 
now after activating the pricing manager addon, he/she will have to literally calculate how much limit he/she needs for different packages based on the total listing setting for CPT. 

So In my guess 

- use Total No. of Listings inside each CPT setting page
( When Core and Pricing Manager inactive )

- use Total No. of Listings inside each package ( When Pricing Manager active ) 
and remove/hide the setting from CPT.

**Comment by kprajapatii** [comment]
Added in core.

See https://github.com/AyeCode/geodirectory/commit/44a39c938aafaf15904359bfff5c1a3d2c2f6a73
