### ISSUE TITLE
New listing images uploaded through front end not displayed

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#118]
When adding a new listing, images uploaded through front end editor do not display on the detail page.
When editing a new listing and adding images through front end editor images do not display on detail page.

Featured image does display in backend editor for detail page
image does not display in places listing.

adding images through backend editor and the image displays on the listing.

**Comment by Stiofan** [comment]
Can you explain how i replicate this?

**Comment by alexrollin** [comment]
seems ok now.
will reopen if it happens again.

**Comment by alexrollin** [comment]
(could be conflict between multiple editors with same login?)

**Comment by Stiofan** [comment]
i changed the plugin folder name to remove the -v2 part, that might have caused some issues, i have since reset the DB so that might have fixed it.
