### ISSUE TITLE
odd spacing for cats and tags depending on length of cats

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#119]
shorter cats
![screenshot 2018-03-19 at 11 16 21 am](https://user-images.githubusercontent.com/114659/37589979-1ad59756-2b67-11e8-8e4d-80a823c55910.png)

longer cats

![screenshot 2018-03-19 at 11 16 35 am](https://user-images.githubusercontent.com/114659/37589981-1f19fe56-2b67-11e8-9a1f-0a931062f68f.png)

**Comment by Stiofan** [comment]
This is how it has always been, do u have a proposed solution?

**Comment by alexrollin** [comment]
I think the only upgrade I can think of would be to have it on two lines to start with and, if this can be done with using two widgets for GD Post Meta, that should be enough. Closing for now.
