### ISSUE TITLE
ER - GD Post Meta -> archive_title or location_title

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1196]
Many themes do not have agreeable post title options for archive and details page.

Many themes require compatibility settings for archive and location page titles that break on update

For the Details page it is fine to use GD Post Title 

This would be an option for adding a dynamic post title for archive pages.

This would allow us to advise members to simply hide their normal post title and use our element instead

**Comment by kprajapatii** [comment]
New widget / shortcode [gd_page_title] added to show page title on GD pages.

[gd_page_title tag="h1" title_container=1 strip_html=0 no_wrap=0 container_class="" css_class=""]
