### ISSUE TITLE
GD Experts snag list 

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#1204]
A few things to fix in the new site.

- [x] Fix the design of the About page Paolo
- [x] In the experts' page, because the map must be so small, we should make it fixed on top and have a banner saying buy GeoDirectory down below. Both fixed and non-scrolling. Basanta to make the banner and Stiofan to add it. (we should use the be your own boss banner.)
- [x] Copyright in the footer says 2018. Stiofan
- [x] fix account billing address form: https://geodirectoryexperts.com/account/?type=billing Basanta
- [x] Remove the shipping address option. Stiofan
- [x] What's this? https://geodirectoryexperts.com/account/?type=notifications Stiofan
- [x] Add rel="nofollow noopener noreferrer" to links in detail page Stiofan
- [x] fix add expert fields. - Paolo
- [x] add job listings with minimal design. Basanta
- [x] fix detail page tabs - Paolo

**Comment by Stiofan** [comment]
Feedback needed https://geodirectoryexperts.com/jobs/

**Comment by basantaux** [comment]
Looks good to me :)
