### ISSUE TITLE
Description field 'stuck' as hidden

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#123]
Attempting experiment with making description field optional.

Unable to show description in front end editor (stuck off).

https://ppldb.com/v2/add-listing/?pid=83&listing_type=gd_place
https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd-cpt-settings

![screenshot 2018-03-19 at 12 17 43 pm](https://user-images.githubusercontent.com/114659/37592667-b015556a-2b6f-11e8-95e1-a8624395a087.png)
![screenshot 2018-03-19 at 12 17 24 pm](https://user-images.githubusercontent.com/114659/37592669-b0315846-2b6f-11e8-9472-1f3961bf17cc.png)
![screenshot 2018-03-19 at 12 16 49 pm](https://user-images.githubusercontent.com/114659/37592670-b04a42de-2b6f-11e8-933e-9250162f5d49.png)

**Comment by Stiofan** [comment]
seems to be working ok for me...  explain more if u need me to reopen.
