### ISSUE TITLE
Docs: Extensions & Features

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1231]
### Location Manager

Please start with this list, post comments with links to docs for review.

- [x] Location Manager - Setup Guide
- [x] Settings Overview for Locations > Settings
- [x] Settings Overview for Locations > Add Location
- [x] Settings Overview for Locations > Countries
- [x] Settings Overview for Locations > Regions
- [x] Settings Overview for Locations > Cities
- [x] Settings Overview for Locations > Neighbourhoods
- [x] GD > Near Me Button
- [x] GD > Locations
- [x] GD > Location Switcher
- [x] GD > Location Meta
- [x] GD > Location Description

### Advanced Search

- [x] Advanced Search - Setup Guide
- [x] Settings Overview for Advanced Search
- [x] Settings Overview for CPT > Settings > Search
- [x] How to Add a Field to Advanced Search Section
- [x] How to Add a Field to Main Search Bar
- [x] GD > Search (extended settings)

### Custom Post Types

- [x] Custom Post Types - Setup Guide
- [x] Settings Overview for Post Type (CPT) > Settings > General
- [x] How to Add a new Custom Post Type
- [x] How to Link two Custom Post Types
- [x] GD > CPT Listings
- [x] GD > Linked Posts
- [x] Creating different templates for Custom Post Types
- [x] Can I add listings without an address?

### Pricing Manager

- [x] Pricing Manager - Setup Guide
- [x] Settings Overview for GD > Settings > Pricing
- [x] Settings Overview for Post Type (CPT) > Settings > Packages
- [x] How to Add a new Pricing Package
- [ ] GD > Single Expired Text
- [x] How do Recurring Packages Work?

### Events

- [ ] Events - Setup Guide
- [ ] Settings Overview for GD > Settings > Events
- [ ] How to Make Any CPT an Events CPT
- [ ] GD > Are You Interested
- [ ] GD > Events Calendar
- [ ] GD > Event Schedules

### Claim Listings

- [ ] Claim Listings - Setup Guide
- [ ] Settings Overview for GD > Settings > Claim Listings > Settings
- [ ] Managing Claimed Listings
- [ ] Set up Pay to Claim Listings
- [ ] Using Ninja Forms for Claim Listings
- [ ] GD > Post Claim

### BuddyPress Integration

- [ ] BuddyPress Integration - Setup Guide
- [ ] Settings Overview for GD > Settings > BuddyPress > Settings
- [ ] Why do i have to change the search page slug when using BuddyPress?

### Marker Cluster

- [ ] Marker Cluster - Setup Guide
- [ ] Settings Overview for GD > Settings > Marker Cluster
- [ ] How to Enable Marker Cluster on Individual Maps
- [ ] Server Side vs Client Side Marker Clustering

**Comment by sufyanism** [comment]
@Stiofan Awaiting feedback on the Setup Guide. 
Rest is here - https://docs.wpgeodirectory.com/category/212-advanced-search

**Comment by Stiofan** [comment]
@sufyanism NOTE: we used "addon" in the past but are changing to "extension", please use this in all cases.

**Comment by pol76** [comment]
@stiofan, for advanced search, don't we need a doc explaining how autocomplete works?

**Comment by sufyanism** [comment]
For review: 
- https://docs.wpgeodirectory.com/category/28-location-manager 
- https://docs.wpgeodirectory.com/category/89-custom-post-types-extension 
- https://docs.wpgeodirectory.com/category/212-advanced-search

**Comment by pol76** [comment]
about this: https://docs.wpgeodirectory.com/article/223-gd-cpt-listings#gd-cpt-listings

I'd add a couple of examples of what we mean with "Selectively pick where the widget should be displayed".

Also the doc title should probably be "GD > CPT Listings (Widget)"

**Comment by sufyanism** [comment]
For review - https://docs.wpgeodirectory.com/category/91-pricing-manager-extension 
Added all, except the GD > Single Expired Text. Will add that shortly.

**Comment by pol76** [comment]
Good job on the pricing manager's docs @sufyanism, I'm glad to see the quality of docs improving. I can see you are getting familiar with GD more and more. Thanks!

**Comment by sufyanism** [comment]
For review: 

- https://docs.wpgeodirectory.com/category/244-claim-listings 
- https://docs.wpgeodirectory.com/category/237-events

**Comment by sufyanism** [comment]
For review: 

- https://docs.wpgeodirectory.com/category/265-marker-cluster 
- https://docs.wpgeodirectory.com/category/261-buddypress-integration

**Comment by sufyanism** [comment]
- https://docs.wpgeodirectory.com/category/279-social-importer 
- https://docs.wpgeodirectory.com/category/273-gd-recaptcha
