### ISSUE TITLE
ER Fix preview of uploaded image - constrain proportions

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1234]
This does not look good and gives end users pause

Multiple requests from members

![image](https://user-images.githubusercontent.com/114659/82233343-29fabe80-9930-11ea-8188-411a1b005eed.png)

**Comment by Stiofan** [comment]
@kprajapatii  object-fit: contain; should do it, should we increase the size a little at the same time?

**Comment by kprajapatii** [comment]
Fixed
See https://github.com/kprajapatii/geodirectory-v2/commit/5301e53893aadd656b3b14cf191b19cd97b68eb3
