### ISSUE TITLE
Relocate search placeholder text to GD - Design - Search

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#124]
Recommend Relocation of search placeholder text to GD - Design - Search

Search field default value (Rec. changing this to "Search field placeholder text")
Near field default value (Rec. changing this to "Near field placeholder text")

![screenshot 2018-03-19 at 1 09 05 pm](https://user-images.githubusercontent.com/114659/37594850-bebfb2fc-2b76-11e8-919c-37177d5bd915.png)

Recommend 'always' keeping all the placeholder text or "possible related to translation stuff" in the same "Design" area so people can find it.

This is a question that is asked often: "How can I change that placeholder text? Can I add default text for a default search? Can I format the placeholder text with html?

**Comment by Stiofan** [comment]
I'll talk with Paolo about this later

**Comment by Stiofan** [comment]
Changed to "placeholder text" but we will keep the setting where they are for now.
