### ISSUE TITLE
Allow 'null' for some default placeholders

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#126]
If a field has a default placeholder provided by the GD plugin, then the field should allow that default placeholder to be 'nulled' or made empty. This is especially useful to users who would otherwise be forced to translate the plugin just because they want a field placeholder to have no value.

This could be done with another button, but a 'space' character is what most folks would use.

![screenshot 2018-03-19 at 1 58 06 pm](https://user-images.githubusercontent.com/114659/37596834-b684277e-2b7d-11e8-9666-7fbd97fe1a03.png)

**Comment by Stiofan** [comment]
in most cases a space can be used, in the case of search it has not input labels so you need to have some placeholder text. if u can think of another case just let me know and i will re-open this.
