### ISSUE TITLE
gd_posts object shows featured image url even when it is removed 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1269]
Steps: 

- remove all images from a place post including featured images
- now load the frontend detail page with the Supreme directory theme. 
- it shows no images instead of loading default images. 

 https://secure.helpscout.net/conversation/1174062740/2759/

**Comment by kprajapatii** [comment]
Fixed
See https://github.com/AyeCode/geodirectory/commit/00a1b49dd055e3a9ff729b8644b391fe66b06d8e
