### ISSUE TITLE
Hey, we found a post you started earlier...

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#127]
1. Text cannot be selected? (Should someone be able to select it?)
2. The link is white and hard to see, the hover color is grey and hard to see

![screenshot 2018-03-19 at 2 23 30 pm](https://user-images.githubusercontent.com/114659/37598029-5dc76ac0-2b81-11e8-9564-fcb05355367e.png)

**Comment by Stiofan** [comment]
1. enabled selection
2. i have added an underline for links there.
