### ISSUE TITLE
Widget Admin Name

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#128]
GDV2 will tempt members to install lots of widgets. 

If users end up with 16 different GD - Meta widgets in a row, it might be helpful if they could use an "Admin name" similar to custom fields.

![screenshot 2018-03-19 at 2 38 44 pm](https://user-images.githubusercontent.com/114659/37598781-6d9d832e-2b83-11e8-9297-38b7e2a0492d.png)

Otherwise there may be some confusion tracking down a widget:

![screenshot 2018-03-19 at 2 38 10 pm](https://user-images.githubusercontent.com/114659/37598798-7a389e70-2b83-11e8-990f-7633d928bc24.png)

**Comment by Stiofan** [comment]
Some widgets now use standard title, and i have added a title function for post_meta to show the key
