### ISSUE TITLE
Recent Reviews per user

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1289]
UWP or GD?

Augment Recent reviews widget to take author id? current user?

![image](https://user-images.githubusercontent.com/114659/84580202-1cbcdc80-add5-11ea-9651-aeb3531e2725.png)

**Comment by kprajapatii** [comment]
Add comment_author (Comment Author) parameter(via input text) in GD > Recent Reviews (gd_recent_reviews) widget to filter reviews by author.

- Input text will allow values to filter by current_user, current_author or ID (default = unfiltered). 
  - - current_user: Filters the reviews by author id of the logged in user. 
  - - current_author: Filters the reviews by author id of current viewing post/listing/profile. 
  - - ID Ex 11: Filters the reviews by author id = 11. 
  - - Leave blank to show reviews from all authors.

You can get reference form GD > Listings widget "Filter by author:" parameter.
