### ISSUE TITLE
Add listing shortcode default CPT option is not functioning. 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1293]
<img width="278" alt="Screenshot 2020-06-17 at 3 59 04 PM" src="https://user-images.githubusercontent.com/24760592/84887583-942f8c00-b0b3-11ea-80fc-e1173bffca7d.png">

**Comment by alexrollin** [comment]
If we do not support multiple add listing pages maybe we should remove this.

When people do not use places as the default this should override the CPT sort order?

Or should we just stick to the CPT sort order, with the lowest number as the default?
