### ISSUE TITLE
REST API location distance and order by.

### ISSUE THREAD

**Issue by ThomLS** [AyeCode/geodirectory#1298]
Hello, the REST API with the following information and parameters still doesn't work.

/wp-json/geodir/v2/places/?latitude=21.8380&longitude=73.7190&distance=10&orderby=distance&order=asc

or
/wp-json/geodir/v2/places/?latitude=21.8380&longitude=4.7190&distance=10&order_by=distance

Also the distanceto is weird: "distanceto":null

{"code":"rest_invalid_param","message":"Invalid parameter (s): orderby: orderby","data":{"status":400,"params":{"orderby":"orderby is not \u00e9\u00e9n from post_date_desc."}}}

**Comment by ThomLS** [comment]
https://wpgeodirectory.com/support/topic/listings-search/ Still not working?

**Comment by kprajapatii** [comment]
Hi Thom,

Distance sorting works with Location Manager. See https://wpgeodirectory.com/support/topic/listings-search/#post-518076
