### ISSUE TITLE
Address issue ADD LISTING LANGUAGE ISSUE

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1308]
https://secure.helpscout.net/conversation/1200757051/4245?folderId=3812058

what is weird : if i type : avenue louise ... it suggests brussels and in region you can see brussels and it changes to brussel hoofdgewest ???

**Comment by kprajapatii** [comment]
Fixed

See https://github.com/AyeCode/geodirectory/commit/cd4b45ac7d992c0569ad42e62d96551c326f1397
