### ISSUE TITLE
Many customer request to remove comma or And from category 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1312]
https://secure.helpscout.net/conversation/1215694180/4904?folderId=3812058

**Comment by alexrollin** [comment]
hard to do anything here: 
![image](https://user-images.githubusercontent.com/114659/86763286-84b6b980-c047-11ea-951f-adf15976f28d.png)

**Comment by Stiofan** [comment]
Two points:

1. once AUI is in GD core commas and "and" will be removed if using the badges

2. This can be done currently with only CSS
```
.geodir-field-post_tags {
    font-size: 0;
}
.geodir-field-post_tags  a{
    font-size: 12px;
}
```
