### ISSUE TITLE
Place Categories CAT ID Alignment Issue

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#132]
https://ppldb.com/v2/wp-admin/edit-tags.php?taxonomy=gd_placecategory&post_type=gd_place

Cat ID alignment issue

![screenshot 2018-03-20 at 10 05 42 am](https://user-images.githubusercontent.com/114659/37645208-74141e4a-2c26-11e8-9dfc-b39821d1c92f.png)

topic
https://wpgeodirectory.com/support/topic/backend-place-categories-cat-ids/

**Comment by Stiofan** [comment]
fixed
