### ISSUE TITLE
Unexpected/Unknown Fatal error

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1328]
https://secure.helpscout.net/conversation/1225361483/5331/

The email arrives, I panic, but when I check the site all seems well.

**Comment by kprajapatii** [comment]
Not able to replicate, but added some validation to prevent error.

See https://github.com/AyeCode/geodirectory/pull/1329/commits/dad10f9632fa5a4c8d7218338c27d1a56c70526a
