### ISSUE TITLE
Lazy Load Maps

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1354]
Consistently map loading is what slows a page load down the most. Also, the way we add map scrips is not ideal https://web.dev/no-document-write/?utm_source=lighthouse&utm_medium=unknown

I propose that we add lazy loading to maps, much like images.
1 new option should be added to the map widget.
Lazy Load:  
- Off - No lazy loading
- Auto - Shows when visible on the page via scroll.
- Click to load - Show a button saying "Click to load map"

Let's discuss this.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/99285322dc64a6a96b8acc0005c60d89aee21045
