### ISSUE TITLE
Business Hours - Displays

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#137]
CPT - Settings - Business Hours - Show in what locations
More info - works
Sidebar - works
Details page own tab - not working
Listing Page - works
Map Bubble - works but cannot be expanded/opened (styling slightly off, also)

![screenshot 2018-03-20 at 10 17 19 am](https://user-images.githubusercontent.com/114659/37645931-8e2d854e-2c28-11e8-829d-73b8d46ce9dd.png)

Widget - GD Meta
All - not yet implemented
Frontend Label - not yet implemented
Vali - not yet implemented

![screenshot 2018-03-20 at 10 24 43 am](https://user-images.githubusercontent.com/114659/37646079-ee7755e2-2c28-11e8-8bd6-42e2d9d77118.png)

Topic

https://wpgeodirectory.com/support/topic/frontend-details-page-business-hours-in-tab-not-working/

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/pull/141

**Comment by alexrollin** [comment]
Map Bubble with awesome scroll works now
