### ISSUE TITLE
WP Easy Updates plugin required for GD Core V2?

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#138]
Installing the core plugin only, gives this message: "The plugin WP Easy Updates is required to check for and update some installed plugins/themes, please install it now."
Not really a bug, just wondering if it should be there or not.

**Comment by Stiofan** [comment]
Yes, we will use WPEU so the users can update when we release new beta versions, hopefully every day or two.

**Comment by Guust-Flater** [comment]
Clever :)
