### ISSUE TITLE
Meta tags for locations are not working

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1391]
https://secure.helpscout.net/conversation/1284666109/8015?folderId=3812058
<img width="1072" alt="Screenshot 2020-09-28 at 4 50 27 PM" src="https://user-images.githubusercontent.com/24760592/94426153-c40a2780-01aa-11eb-9a9c-31205759d90b.png">

**Comment by kprajapatii** [comment]
See https://secure.helpscout.net/conversation/1284666109/8015?folderId=3812058#thread-3817036193
