### ISSUE TITLE
Add predefined custom field "Make Private"

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1396]
Add a predefined custom field checkbox that when ticked will set the visibility of the listing to private.

https://secure.helpscout.net/conversation/1297470742/8538?folderId=3803512

**Comment by alexrollin** [comment]
Will the content be searchable?
Removed from loops? or visible only to op and admin in loop?
Addressable with badge and post_meta?
Removed from gd_listings except current_author current_user?

if we are talking status there are many more requests for frontend buttons to adjust post status - closed, or draft to name 2
