### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1413]
- Bootstrap UI (how to enable, how to customize)
- Lazy Load map
- Pricing Table (Pricing Manager see example: https://ppldb.com/kiran/stable/gd_pricing/)
- Show linked posts via gd_listings widget

**Comment by Stiofan** [comment]
@pol76 we prob want to update the blog post with things like where to find the settings.

@sufyanism we need docs for the above, ping me if u have any questions.
