### ISSUE TITLE
post_content has no respect for line breaks

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#142]
Not seeing any line breaks at all in the output on the detail page

![screenshot 2018-03-21 at 11 20 26 am](https://user-images.githubusercontent.com/114659/37704717-e810df4e-2cf9-11e8-92f0-b9800b7af6ed.png)
![screenshot 2018-03-21 at 11 20 15 am](https://user-images.githubusercontent.com/114659/37704718-e84a7a92-2cf9-11e8-98c5-600f38838824.png)

**Comment by Stiofan** [comment]
added wpautop() to the output
