### ISSUE TITLE
FA Icon Picker

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#143]
Enhancement

If a certain plugin/addon is activated, then there an icon picker appears next to these places where a FA Class can be inserted

![screenshot 2018-03-21 at 11 24 51 am](https://user-images.githubusercontent.com/114659/37704945-b110d66a-2cfa-11e8-878e-983c5368ecb1.png)

This one might work with minimal changes:
https://wordpress.org/plugins/better-font-awesome/
and is based on this:
https://github.com/MickeyKay/better-font-awesome-library

It would look like this:
![example icon picker using the better fontawesome plugin](https://ps.w.org/better-font-awesome/assets/screenshot-1.gif)

**Comment by Stiofan** [comment]
implemented
