### ISSUE TITLE
Event Date Format issue

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1431]
[geodir_event_schedules type="upcoming" number="1" template="{start_date} - {end_date} @ {start_time} - {end_time}"]
<img width="476" alt="Screenshot 2020-10-20 at 6 02 43 PM" src="https://user-images.githubusercontent.com/24760592/96748552-4c18d100-13e7-11eb-8dd4-931482fe3b22.png">

https://secure.helpscout.net/conversation/1310057230/9179?folderId=3812058

**Comment by kprajapatii** [comment]
Fixed via https://github.com/kprajapatii/geodir_event_manager-v2/commit/b5a7c5204fcf9208931540ad93ffee4f04be1e02
