### ISSUE TITLE
Urgent Docs

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1438]
- [ ] Tools page 
GD > Status (i don't think this has doc's either) > Tools

- [ ] Developer Section (lots of docs missing here, like API docs)
We have zero API docs such as https://wpgeodirectory.com/docs-v2/api/ (**hold off on this just now,** i may use a different solution for API docs)

- [ ] Server requirements
I started searching "server" and did not find the doc, maybe change title or add tag.

- [ ] FAQ Multisite (should only be activated per site not network)
We need titled "Can i use GeoDirectory on WPMU Multisite?"

- [ ] Caching category
New category for caching so we can list our recommended settings for caching plugins such as "WP Rocket" etc

- [ ] WPML translating listings
A doc explaining how to translate listing with WPML, correct settings for WPML etc.

- [ ] General > Titles & metas
I could not find this?

- [ ] How to merge locations
I could not find this?

**Comment by sufyanism** [comment]
- https://docs.wpgeodirectory.com/article/367-settings-overview-for-gd-status-tools?auth=true
- https://docs.wpgeodirectory.com/article/6-requirements?auth=true 
- https://docs.wpgeodirectory.com/article/370-can-i-use-gd-on-wordpress-multisite?auth=true 
- https://docs.wpgeodirectory.com/article/369-settings-overview-for-general-titles-metas?auth=true
- https://docs.wpgeodirectory.com/article/371-how-can-i-merge-locations?auth=true
