### ISSUE TITLE
additional CSS class for field is not applying. 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1446]
<img width="1175" alt="Screenshot 2020-11-04 at 8 23 51 AM" src="https://user-images.githubusercontent.com/24760592/98063911-1b20ad80-1e77-11eb-9d5b-c52f5ffb7bb1.png">

**Comment by kprajapatii** [comment]
css_class class is used in output of custom field at frontend. see https://github.com/AyeCode/geodirectory/blob/master/includes/custom-fields/output-functions.php#L110
