### ISSUE TITLE
Slider Widget Overlap on Detail Page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#146]
https://ppldb.com/v2/places/pastry-celebration/

On the page and in the SS below it i possible to see a black line on the right side of the starting image.

This black line is the beginning of the next image.

![screenshot 2018-03-21 at 3 45 41 pm](https://user-images.githubusercontent.com/114659/37716637-421aa478-2d1f-11e8-9457-b258505e5208.png)

**Comment by Stiofan** [comment]
i don't see the issue, what browser are u using? Is there something i have to do to replicate?

**Comment by alexrollin** [comment]
This only happens when zoomed. Closing (user error)
