### ISSUE TITLE
"Get Directions" on Details Page doesn't update with a new search

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1479]
https://secure.helpscout.net/conversation/1349110647/11001/

**Comment by 1naveengiri** [comment]
![9f00dce5d5339471b936e755d5f07781](https://user-images.githubusercontent.com/24760592/104167944-3bdf2380-5423-11eb-8c69-5df0b052fbba.png)

**Comment by kprajapatii** [comment]
Fixed
