### ISSUE TITLE
gd_listing shortcode ajax pagination not changing page on arrow click

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1489]
- Add gd listing widget with pagination
- click on farword arrow 
https://secure.helpscout.net/conversation/1357411435/11425?folderId=3812058

<img width="1025" alt="Screenshot 2020-12-08 at 12 05 12 AM" src="https://user-images.githubusercontent.com/24760592/101390581-12455080-38e9-11eb-9774-5982e7b38ec0.png">

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1358570063/11474?folderId=3812058

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/77aa94cfbd0163f2bdb9e886e1ce19f8fb24d6af
