### ISSUE TITLE
CPT Name change does not change Category and Tag names

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#151]
See https://wpgeodirectory.com/support/topic/custom-post-type-name/

**Comment by alexrollin** [comment]
Is this a V2 bug? The addons are not ready yet for testing, methinks... @Stiofan confirm?

**Comment by Guust-Flater** [comment]
Yes, it is. 
Places > Settings > CPT Settings tab > Labels
In V2 CPT names can be changed there without having the CPT addon.

**Comment by Guust-Flater** [comment]
Stiofan says "Fixed"
https://wpgeodirectory.com/support/topic/custom-post-type-name/#post-423033
