### ISSUE TITLE
remove link icon 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1527]
<img width="1680" alt="Screenshot 2021-01-11 at 8 16 47 PM" src="https://user-images.githubusercontent.com/24760592/104196568-f1bd6880-5449-11eb-8729-5b5a8b21676e.png">
https://secure.helpscout.net/conversation/1391960380/12919?folderId=3812058

**Comment by kprajapatii** [comment]
@1naveengiri How to replicate this issue?

**Comment by 1naveengiri** [comment]
It occurs only In legacy design.  I will come on chat with you about it.
