### ISSUE TITLE
Should the image titles and captions show in the photos tab of the detail page?

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#153]
https://wpgeodirectory.com/support/topic/listing-image

**Comment by alexrollin** [comment]
Some of these issues are being worked on here: https://github.com/AyeCode/geodirectory/issues/99
Specifically the extra space under images has been noted by @wpdev10

**Comment by Stiofan** [comment]
no, they were never supposed to show there, that was a css bug, they show in the lightbox.
