### ISSUE TITLE
Tooltips won't close/disappear

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#154]
At Places - Settings - Sorting Options OR on custom fields.
Appears to be related to the field 'buttons' and having a tooltip ON the button

Click on a tooltip on a field on the left, on the tooltip or the field, and the tooltips open, and won't close.

Finicky, but reproduceable on all 3 major browsers.

![screenshot 2018-03-23 at 7 30 02 am](https://user-images.githubusercontent.com/114659/37814846-7e429c32-2e6c-11e8-8340-564a45d3c33b.png)

![screenshot 2018-03-23 at 7 39 57 am](https://user-images.githubusercontent.com/114659/37815038-7d35dd62-2e6d-11e8-87c6-5738e4ed1bef.png)

Related topic:
https://wpgeodirectory.com/support/topic/tooltip-stays-sticky/#post-422705

**Comment by Stiofan** [comment]
resolved.
