### ISSUE TITLE
Extend Geodirectory html field using Advanced Editor Tools (previously TinyMCE Advanced) plugin

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1543]
https://wordpress.org/plugins/tinymce-advanced/
https://secure.helpscout.net/conversation/1389102848/12782?folderId=3812058

**Comment by kprajapatii** [comment]
GeoDirectory is using default WP Editor, it has no extra setting to set specific editor. WP Editor settings can be filtered via hook

`$settings = apply_filters( 'wp_editor_settings', $settings, $editor_id );`
