### ISSUE TITLE
Select2 bug : Show in the extra output location custom fields setting

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1548]
<img width="779" alt="Screenshot 2021-01-19 at 6 33 43 PM" src="https://user-images.githubusercontent.com/24760592/105038137-f525a500-5a84-11eb-8ff3-55bfe29d6cb3.png">

Select2 bug : Show in the extra output location custom fields setting

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/commit/e0c639f9d6df8495ad4bcc173906f1ff39a98dc3
