### ISSUE TITLE
Only last added custom field should open

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#155]
If you add multiple custom fields, then the firs one will reopen instead of the last.
To recreate, add 3 or more in a row, just add, dont click anything else.
You will see like this with 3 text, where the first is open, not the others.
(Could be by design, that is fine "))

![screenshot 2018-03-23 at 8 04 12 am](https://user-images.githubusercontent.com/114659/37815860-fe469628-2e70-11e8-849a-cd599a98d8c1.png)

related topic
https://wpgeodirectory.com/support/topic/adding-custom-fields/

**Comment by Stiofan** [comment]
fixed
