### ISSUE TITLE
Possible solution for Listings with multiple addresses

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#1556]
Couldn't we add a repeater field for the address in add listing form, but create 1 listing for each address. (add canonical URL pointing to the main listing for all clones for SEO purposes)

In search and archives allow admin to only show the primary listing like I think we do for recurring events, while the map shows them all.

Is this a possible solution?

If yes, we would only need to aggregate reviews in the main listing too...

Let me know your thoughts.

**Comment by Stiofan** [comment]
I have talked this over with @kprajapatii but have a few questions.

1. Why are we doing this exactly if we have franchise manager? If we did just this without franchise i think the customer's next question would be "can i change the phone, email for those too" which leads to franchise manager. Most businesses that have multiple addresses all have different phone numbers/emails for them.
2. If each listing has its own URL then how only show one in archive view, this would take you to one location which might not be the one you expect.

Lets discuss it more.

**Comment by alexrollin** [comment]
Franchise manager is great, but a little hard to use.

To make it easier - we could allow users to 

have frontend imports and updates with CSV
find another way to link posts with a UID instead of a post ID 
pay for listings from the wallet - add to wallet - for recurring

I really like the idea of all reviews being on all listings or only on the parent - we have not had a ticket like that but it is neat.

**Comment by alexrollin** [comment]
we get a lot of people asking for service areas related to post codes. 

 a 'post code hyper local search' is a different topic.

**Comment by alexrollin** [comment]
Also, if using franchise then the add-franchise link - this will auto-link to the parent- would be nice if this was available to all custom post link post fields.

**Comment by Stiofan** [comment]
Thats kinda where i was going with this, maybe we just need a UX revamp for franchise.

**Comment by Stiofan** [comment]
Project opened for franchise manager https://github.com/AyeCode/geodir_franchise-v2/projects/1
