### ISSUE TITLE
Progressbar not moving during the demo content installation step.

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#1558]
![image](https://user-images.githubusercontent.com/208945/105524185-4e9c0700-5d05-11eb-9685-12fb473d00ec.png)

**Comment by Stiofan** [comment]
Any progress on this @sandeepjain2015 ?

**Comment by sandeepie** [comment]
@Stiofan working from today on it

**Comment by sandeepie** [comment]
@laranz hi may you provide some steps for find this bug . At my end it is coming fine

https://user-images.githubusercontent.com/43406883/107962924-8aa54d80-6fcd-11eb-8850-4a303c9ae018.mp4

cc : @kprajapatii

**Comment by kprajapatii** [comment]
@laranz  could you confirm issue is still there?

**Comment by laranz** [comment]
@kprajapatii @sandeepie  I installed a fresh WordPress install, and it still happens to me.

Check the video here: https://monosnap.com/file/AQ5CyBlEQSjGU66eXnUSvKYHja5jcQ
