### ISSUE TITLE
Working hours - remove add icon for last day(Sunday) if Sunday not closed

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/geodirectory#156]
This is the suggestion for a business hour on admin as well as on front side while adding a new listing.
![8](https://user-images.githubusercontent.com/32451578/37828810-b0f8da6e-2ec2-11e8-8d7c-ae932b3b5e7a.png)

**Comment by kprajapatii** [comment]
I don't find anything wrong in this. That add icon added so the user can add/remove multiple slots within one day.
