### ISSUE TITLE
BUG Max cats to show filter not working

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#1572]
Tested on this page: https://demos.ayecode.io/supreme-directory/location/united-states/california/san-francisco/

If you use the GD > Categories block the Max cats to show filter does not work correctly. For example, I had to select 4 categories to be able to show 6. 

1 would show 2
2 would show 4
3 would show 5

and so on...

**Comment by kprajapatii** [comment]
We show categories for each CPT. Max cats to show = 2 filter will show 2 categories for each cpt.

For example:
There are 2 CPTs Places & Events on the site. So max cats to show = 2 will show total 4 categories(2 for places & 2 for Events).

Let me know if this is not the case.

@pol76

**Comment by Stiofan** [comment]
Yes the setting is per CPT, in design if you enable show CPT title you see that it splits it into 4 place + 2 Event cats.
Maybe all we need is to make this clear in the setting?

**Comment by Stiofan** [comment]
Settings updated to reflect that this is per CPT.
