### ISSUE TITLE
Kleo theme menu collapse issue with Ayecode UI

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1575]
https://secure.helpscout.net/conversation/1397349005/13227?folderId=3812058

https://secure.helpscout.net/conversation/1322208621/9782/

https://secure.helpscout.net/conversation/1370404418/11929/

https://secure.helpscout.net/conversation/1390144625/12839/

**Comment by Stiofan** [comment]
This will be fixed in the next release of GD.
