### ISSUE TITLE
Cutoff placeholder "Show in what locations" -> Select locat

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#158]
Place holder is cutoff for new custom fields added to places:

![screenshot 2018-03-24 at 1 48 18 pm](https://user-images.githubusercontent.com/114659/37864105-22b1056c-2f6a-11e8-9ded-113c38d1e81c.png)

Related topics
https://wpgeodirectory.com/support/topic/show-in-what-locations/

**Comment by kprajapatii** [comment]
Fixed
