### ISSUE TITLE
Make clear that sample CSV files are not usable - or eliminate them

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1593]
When the site owner is on the importer page he is 2 steps from exporting.

Why do we provide sampel CSV files, - especially when some members mistakenly use them - and they will not import, won't work. So we get tickets about it.

Can we just remove the samples? Or add text that warns them not to actually use the sample files because they don't work?

Can we get contextual help on this page instead that points them to an FAQ about importing?

![image](https://user-images.githubusercontent.com/114659/107752420-ff9f2b80-6d1e-11eb-9892-18779c457a21.png)

**Comment by alexrollin** [comment]
Here is my canned response about this  can @sufyanism add a doc, and we can link to doc instead? to encourage users to make example listings and export hat?

Hello,
​
​did you use Libre or Open office to edit the file?
​Did you add a test listing, and export that for a comparison CSV?
​Can you send us both files the export and the import?
​Did you make sure your import has no post IDs?
​
Are you seeing an array error? See: https://docs.wpgeodirectory.com/article/158-i-get-an-error-when-trying-to-import-a-csv-file

The sample file linked from the Import page is just that, an example. Every site has a different CSV format because each site has different custom fields. Did you use the sample instead of an export?

To get the unique CSV format for your custom post type import please try:

Add a listing and fill all fields
Export the listings in that CPT
Open the CSV with Libre or Open office
Merge your data into the CSV
Upload/import the new saved file

See also: https://wpgeodirectory.com/docs-v2/geodirectory/settings/import-export/#recommended

I recommend you add one listing called "Required Fields only", too, with only the red asterisk fields filled. This will show the minimum data required any record.

A new listing would need all these fields filled, minus latitude and longitude. GD will geocode imported listings using your chosen Maps API, as long as there is sufficient address information.

**Comment by Stiofan** [comment]
Why don't they work?

**Comment by alexrollin** [comment]
They are missing the default category column, for starters.

![image](https://user-images.githubusercontent.com/114659/162949900-2026364d-ba49-4f90-bb3f-f8b1a0317810.png)

The file also contains more than the default fields, so, will probably not work no matter what the user does with the field configuration.

![image](https://user-images.githubusercontent.com/114659/162950041-f003b5ca-770a-46f3-a2b1-2a9341a0f9ab.png)

https://wpgeodirectory.com/support/topic/geodirectory-v2-3/

https://secure.helpscout.net/conversation/1845147381/31200/

**Comment by alexrollin** [comment]
help document link https://docs.wpgeodirectory.com/article/463-csv-imports-useful-tips
