### ISSUE TITLE
Support post ID in gd_post_meta, gd_post_badges, gd_dynamic_content

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1599]
It would be great to have post ID here:

![image](https://user-images.githubusercontent.com/114659/108178198-7152ed00-7104-11eb-98e6-61636a5b28dd.png)
https://secure.helpscout.net/conversation/1427714160/14976/

**Comment by kprajapatii** [comment]
Add support for post_id to show post ID. You can get help how post_status is used.
