### ISSUE TITLE
The block is registered with an invalid category "geodirectory" warning by blocks.min.js with Woocommerce

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1607]
can be reproduced here in the browser console. 
https://ppldb.com/v2/wp-admin/post.php?post=204&action=edit&classic-editor

https://secure.helpscout.net/conversation/1427225419/14947?folderId=3812058

**Comment by kprajapatii** [comment]
Related to Google Chrome browser
