### ISSUE TITLE
Special Offers field filtering issue

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1612]
https://secure.helpscout.net/conversation/1428758927/15027/

Looking at the three listings that were returned in the search for listings with "Special Offfers," I noticed that all three were of a lower (non-SO level) listing package. After changing them to a higher level on the backend, all three had previous entries in the Special Offers field. In other words, they were previously higher tier level packages, they added to the Special Offers field, and then they were downgraded with that field still containing an entry.

So technically, all three do have Special Offers and should be returned, even though their package level doesn't include Special Offers, those offers aren't even visible, and the "Gift" icon doesn't show up.

So seems like in this situation either
- the field should be cleared/reset upon downgrade
- or if the data is retained, the field should be excluded from the search/filter because it is not included in the package.

I imagine this might be an issue that might be present across other fields where those fields have inputs made under one package, but the listing is subsequently changed to a different package that does not include those fields.

**Comment by kprajapatii** [comment]
This is not a issue. Downgrade process executed on expire listing, switching package don't treat it as a downgrade.
