### ISSUE TITLE
GD Loop Block Preview not realistic

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1652]
The block shows like 4 images if slider is used on the archive item and takes up a huge amount of space on the page

![image](https://user-images.githubusercontent.com/114659/111025012-fff41a80-83e1-11eb-9023-f52d5663ab78.png)

https://secure.helpscout.net/conversation/1450780468/16207/

**Comment by kprajapatii** [comment]
@alexrollin I am not able to reproduce this issue? Could you check please and let me know how to reproduce if issue already exists?
