### ISSUE TITLE
Clear location suggestion

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1658]
https://secure.helpscout.net/conversation/1435806973/15393?folderId=3803512

A user has suggested that the clear location should clear you to the current type of page you are on instead of to the location page, eg:
https://demos.ayecode.io/starter/places/category/restaurants/united-states/california/san-francisco/
to
https://demos.ayecode.io/starter/places/category/restaurants/
instead of
https://demos.ayecode.io/starter/places/location/

Thoughts?

**Comment by alexrollin** [comment]
The change described above seems like it would be an advantage and have few if any negative effects.

**Comment by pol76** [comment]
I agree that would actually be an improvement

**Comment by pol76** [comment]
@kprajapatii could you please add this to the next version of the location manager? Thanks

**Comment by kprajapatii** [comment]
Added

It will be in next version for Location Manager.
