### ISSUE TITLE
Improve GD blocks styling option 

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#1659]
The fact that we can only add +5 to -5 as margin and 0 to 5 as padding is very limiting. Why didn't we use a text input there? 

![Capture](https://user-images.githubusercontent.com/25163253/111555563-47fe9e80-874e-11eb-9e35-7acab6025d72.JPG)

Please see how Kadence Blocks does it.

You can add any value needed and choose between px, em, rem, %, vh, vw for padding and px, em, rem, %, vh for margin

![Capture](https://user-images.githubusercontent.com/25163253/111555753-adeb2600-874e-11eb-8013-361fca0f352f.JPG)

Thanks

**Comment by alexrollin** [comment]
+1

**Comment by pol76** [comment]
@kiran, this looks like a relatively easy change that would have a huge impact. Can you please have a look at it? 

Thanks

**Comment by Stiofan** [comment]
@pol76 Those are not px those are bootstrap spacing classes which keep things consistent. Right now using those versions we don't have to add any more CSS. The idea is to eventually have options at different breakpoints which would not work if we switched to px (or at least it would take much more CSS for every widget)

**Comment by pol76** [comment]
stiofan, what I was requesting is a lot more than px.

If you look at the screenshot, Kadence blocks offer the option to add px, em, rem, %, vh, wh, auto and any possible value. I get it we are using bootstrap, but the options we have right now are not enough. Can't they be added as custom css?

**Comment by Stiofan** [comment]
Can it be done: **Yes**. Is it easy: **No**. Has it been requested: **?**

Why is it not easy?
1. To do this we would either need to change the input types on the fly from select to text/number or add another input, to do this we would need some JS which would not work everywhere such as some builders, so the fallback to just show everything would make things look even more complex.
2. Right now when we want to add support for different breakpoints it would just be changing something like "p-4" to "p-4 p-md-5" but for custom we would need whole new media queries which is not the hard bit but it does add extra and longer CSS.
3. Media queries don't work as inline CSS, so they would need to be in a <style></style> tags, but to target only that specific widget we would need the specific widget to have a specific ID or class in the main wrapper, so we would need to add this to every widget that we want to support it.

All doable but just not as "easy" as it might seem.

Another option would be to have a "custom CSS" input like elementor has.
But i have not heard of any complaints about the current system, its the same as many big sites use, including github (kinda, they have a mix)

**Comment by pol76** [comment]
closed for now, we may have to reopen this once we have more time to improve the product....
