### ISSUE TITLE
Integration with Formidable Forms

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1673]
Create widget or class to integrate Formidable Forms to show booking form on listing tab.

We had this in GDv1 via PHP snippet. https://wpgeodirectory.com/formidable-forms-in-geodirectory-tabs/

**Comment by kprajapatii** [comment]
In v1 we added it via hook, in v2 we need to add via custom tab. Rest of part should be same as in v1.

Should we add this in inbuilt like Ninja Forms or provide PHP snippet just like in v1?

@pol76 @Stiofan

**Comment by alexrollin** [comment]
Don't they have their own directory solution now?

**Comment by kprajapatii** [comment]
@alexrollin No i think!

**Comment by pol76** [comment]
yes they do, formidable forms shouldn't be integrated with GD

https://formidableforms.com/wordpress-directory-plugin/
