### ISSUE TITLE
Address formatting

### ISSUE THREAD

**Issue by compito** [AyeCode/geodirectory#1676]
Different countries, different rules. 

Right now, the default formatting looks like this: Tynäsgatan 10, Karlstad, Värmland, 65216 Sverige
I suppose it works in US of A and many other countries.

In Sweden it should be: Tynäsgatan 10, 65216 Karlstad, Värmland, Sverige.
So we have ZIP number before the city name, then we show the region and country name

Can we have that as a general setting? Should go together with other regional settings, like date etc formatting.

**Comment by alexrollin** [comment]
Hello,

you can use our GD Post Address widget to set up formatting like that for the output

https://docs.wpgeodirectory.com/article/63-gd-post-address
