### ISSUE TITLE
gd_post_image shortcode not loading all review attachment

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1691]
[gd_post_images types="comment_images" fallback_types="comment_images" ajax_load="1" type="slider" controlnav="1" animation="slide" show_title="1" show_caption="1" image_size="medium" aspect="1x1" cover="y" link_to="lightbox"]

https://secure.helpscout.net/conversation/1485123556/17875?folderId=3817467

https://njportraitplaces.com/places/united-states/new-jersey/mount-tabor/trinity-place-park/
https://njportraitplaces.com/account/profile/scooterroth/shortcode/#tab-content

**Comment by kprajapatii** [comment]
@1naveengiri I checked same shortcode on my test site and it is working fine. Could you check & confirm if issue still exists?

**Comment by 1naveengiri** [comment]
It seems working now.
