### ISSUE TITLE
GD > Listings related

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#170]
Lets add another "related to" option "post location" which will order by distance to the current viewing listing (on details page only )

**Comment by Guust-Flater** [comment]
@kprajapatii 
An example is for a site that wants to show all listings in the attractions category that are within a 10km radius from the hotel which is in the accommodation category.
So all accommodation category detail pages [for the hotels], can have a tab with attractions nearby which will also show on the map for the detail page of the hotel. But no other hotels will show.

**Comment by kprajapatii** [comment]
Fixed
See https://github.com/AyeCode/geodirectory/pull/300
