### ISSUE TITLE
Extensions - GD Dashboard?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#171]
On the extension page there is also the GD Dashboard. I thought this will be integrated completely into the GD core. If so, this should not be there.

If you click on the "Price" button, I suggest to open a new tab as the user might like to stay on the page.

**Comment by Stiofan** [comment]
Thanks for the feedback, just now its pulling our current product from our sales site via API.  I will be working on this page tomorrow to improve a few things.
Thanks,

Stiofan

**Comment by Stiofan** [comment]
Dashboard removed, and buttons now open in new window.
