### ISSUE TITLE
Restrict WP Admin access should allow user 1

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1718]
In rare cases an admin may assign a second role like shop manager or subscriber to their user 1 admin account. They may do this because they are experimenting or mistakenly think it will add permissions to the main admin user.

Regardless of why they do it, we get regular tickets from users who have done this and want to know how to regain access.

As a solution we could always allow access to user 1. This is I understand a common practice. 

As a wider permission we could always allow admins, even if they have a second role that is blocked.

Right now if ANY of the seconday roles are blocked, the user cannot access. We could grant access if just one of the roles is admin, but that would be the widest access and may be inadviseable.

**Comment by alexrollin** [comment]
![image](https://user-images.githubusercontent.com/114659/118472882-a671da00-b709-11eb-94c0-26b588e93b38.png)

**Comment by alexrollin** [comment]
Another point about this - if possible, it might be good to flush this setting on install.

When users deactivate the plugin, then re-activate, if it flushes this setting back to the default, they can login and set it up again.

We get enough tickets about this that a solution is welcome!

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/pull/1715/commits/e39ae3bd9301d294747058595447e4dd34adab99
