### ISSUE TITLE
GD Settings - General - Pages - Alignment and ? for Page Settings

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#172]
On the Page Settings page the "?" of "Page Settings" is missing as "Template Page Settings" has one.

Also the alignment of the existing "?" of "Page Settings" can be improved
![pic34](https://user-images.githubusercontent.com/35274187/38150890-5fe61c00-3461-11e8-8e12-1a7e85ee5a21.png)

**Comment by Stiofan** [comment]
We only provide more "help tips" where we feel its needed, not everything needs one (though i have just added one here).  For the alignment, i am assuming you mean that the "Template Page Settings" does not align with the rest?  If so, its not supposed to, this is a title section and is not split  into two sections, the ? just goes at the end of the tile.
