### ISSUE TITLE
Tooltip Stop showing after removing the hours on "Business Hours"

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#1724]
Steps to recreate.

1. Hover over - it shows "Remove Hours"
2. Click the + and then remove the newly created hours by pressing -
3. Now hover over the -, there isn't any tooltip.

![laranz - screencast 2021-05-24 20-11-46](https://user-images.githubusercontent.com/208945/119364437-87a4b200-bccc-11eb-8b62-9aa5667b45d6.gif)

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/pull/1784/commits/4c3976c8f926160cad9358ef8e051e38fb54db68
