### ISSUE TITLE
Add place - Error message at categories

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#173]
Just name it better. Address field is already named.
![pic35](https://user-images.githubusercontent.com/35274187/38151149-5e506e26-3462-11e8-9338-e5a93e5607b2.png)

**Comment by DirkJahn** [comment]
Now I got it. As you can change this message you use a "standard" standard message. Is okay. I think this is nice to have...

**Comment by Stiofan** [comment]
Yes, this is a standard message, the message can be changed in settings.
