### ISSUE TITLE
Duplicate listings addon

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1732]
Member requested that we create our own addon to make it easy to create duplicates of events, especially, that have 90% the same information.

https://secure.helpscout.net/conversation/1525152027/19843/

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2338261939/46651?folderId=3812058

**Comment by kprajapatii** [comment]
This can be easily achievable via import/export feature.

Steps:
1) Export Places/Events from Settings > Import / Export
2) In CSV keep listings which you want to duplicate & delete rest of one
3) Make empty ID/post_id column
4) Re-import the CSV
