### ISSUE TITLE
Places (CPTs) without Category?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#174]
It is possible to set the CPTs to have no category. I think that does not make sence. A post should always have a category in WP. You can define what should be the default category, but it has one.

If you don't do it with a category it adds "No Category" in the place overview (backend) and "No Tags". The last one I cannot say why, because if I add a category and no tag this is not added...

![pic36](https://user-images.githubusercontent.com/35274187/38151476-b3c07fda-3463-11e8-9d9a-621aa98fe3e0.png)

**Comment by DirkJahn** [comment]
If I add a tag to the place without category it is changing...
![pic37](https://user-images.githubusercontent.com/35274187/38151676-7e3d35be-3464-11e8-85c1-f7f182f726c8.png)

**Comment by Stiofan** [comment]
If categories are removed via quick edit we try to add default category - ADDED
Quick edit screen breaks layout of columns - FIXED

**Comment by DirkJahn** [comment]
No, this is not what I'm doing. In the custom fields I can disable "Categories" form being "Required". This is from WP point of view not possible!

![pic49](https://user-images.githubusercontent.com/35274187/38161690-6551e066-34d4-11e8-9df2-04aefeb513a9.png)

**Comment by DirkJahn** [comment]
Solution confirmed. If I have "no required" category defined GDv2 V2.0.0.7 is assigning "Uncategorized" to the new place.
