### ISSUE TITLE
Design is hard coded for category image grid layout

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1746]
https://secure.helpscout.net/conversation/1530244203/20095?folderId=3812058

https://github.com/AyeCode/geodirectory/blob/master/templates/bootstrap/categories/image.php#L66

**Comment by kprajapatii** [comment]
Those style are particular for image. The widget style applied to wrapper class gd-categories-widget.

**Comment by 1naveengiri** [comment]
I see so that style is not for individual category items. 

seems like a custom request, lets close it.
