### ISSUE TITLE
Consistent naming of the CPT status

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#175]
You are using "Pending" and "Pending review". Could you please make it consistent.

![pic38](https://user-images.githubusercontent.com/35274187/38151780-fbbba160-3464-11e8-9792-199577f64a4a.png)
![pic39](https://user-images.githubusercontent.com/35274187/38151784-fdbcf89c-3464-11e8-94c4-cf9d83f0a39c.png)

**Comment by Stiofan** [comment]
This is a WP default status, we only use it, i don't intend to change it.

**Comment by DirkJahn** [comment]
This does not make sence for me, because consitancy is very important for me and for users not to get confused (independently if this comes from WP or not)...
