### ISSUE TITLE
Scheme Type of Categories?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#176]
I know this is also in v1, but does this have a function? I have never seen or used it. 

If this has no function it is better to remove or hide it.
![pic40](https://user-images.githubusercontent.com/35274187/38151940-99296c52-3465-11e8-823c-62571b9ba69b.png)

**Comment by pol76** [comment]
hi,

that has a very important function, it allow to set custom schema type for each CPT.

Please see: http://schema.org/docs/faq.html

Thanks

**Comment by DirkJahn** [comment]
Hi Paolo,

ah, now I have it. Never thought in that direction. I like to suggest add a link to schema.org on that to make it clear.

Thanks,
Dirk

**Comment by DirkJahn** [comment]
Hi Paolo (@pol76),

but for what? My place is of a category with the schema "LocalBusiness". So my expectation is that you use this http://schema.org/LocalBusiness for the schema. But at the moment just standard schemas like Address in "PostalAddress" format (http://schema.org/PostalAddress) is generated.  Nothing about the defined "LocalBusiness" schema.
But the "LocalBusiness" is a complex data structure where the address should be included via inheritet property "address" from "Organization".

Or do I think in the wrong direction? I will check the documentation of GDv1 about it.

Best,
Dirk

**Comment by DirkJahn** [comment]
A quick search in your documentation does not show up a link :(

![pic41](https://user-images.githubusercontent.com/35274187/38152611-f031728a-3468-11e8-835b-0b39e43bb9d3.png)

**Comment by pol76** [comment]
We'll add a page to docs for that too. Honestly we assumed it was self explanatory, but obviously it isn't.
Thanks,

**Comment by DirkJahn** [comment]
Can you quickly explain what it should be?

**Comment by DirkJahn** [comment]
I checked again v1. This is creating a LocalBusiness schema as expected.

But the place with v2 does not. I only get a PostalAddress but no LocalBusiness.
