### ISSUE TITLE
Documentation for Complianz | GDPR/CCPA Cookie Consent Integration

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1761]
We have added "Complianz | GDPR/CCPA Cookie Consent" (https://wordpress.org/plugins/complianz-gdpr/) plugin integration with GD maps. It will be in GeoDirectory v2.1.0.17.

Option to enable/disable user consent for GD maps can be found at WordPress Backend > Complianz > Integrations > Plugins > GeoDirectory.
GD map will ask user content to load map if GeoDirectory plugin integration enabled.

Original task https://github.com/AyeCode/geodirectory/issues/1700

**Comment by sufyanism** [comment]
Article draft is ready - https://docs.wpgeodirectory.com/article/581-complianz?preview=60c48d916264f06fc03005d3&auth=true 
Missing - images, will be added when the GD version is released.

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/581-complianz?auth=true
