### ISSUE TITLE
Elementor - gd_add_listing not working in text module

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1764]
When users open the add listing page for editing in elementor the contents are automatically transferred to a text module to replce the description field and then the map will fail to load. the map on the add listing shortcode will not load ever in an elementor text module. can we fix this or find a workaround to avoid the hassle for users?

https://secure.helpscout.net/conversation/1544386224/20765/

**Comment by alexrollin** [comment]
This is also the case for divi, the add listing shortcode will not work in a text module.

**Comment by Stiofan** [comment]
Let's try and get this resolved once and for all @kprajapatii 
I think the main issue is the JS loaded in the widget, if we call this in the footer from the widget instead of inline i assume this will resolve things?  If not we would have to look at other solutions.

**Comment by alexrollin** [comment]
Can we please get this fixed, if possible? It is a 'gotcha' for pretty much 100% of new Elementor/GD users. @kprajapatii @Stiofan

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1559656803/21482/

**Comment by alexrollin** [comment]
again https://wordpress.org/support/topic/map-not-displaying-25/

**Comment by alexrollin** [comment]
See also: https://github.com/AyeCode/geodirectory/issues/1828

**Comment by alexrollin** [comment]
Every day another

https://secure.helpscout.net/conversation/1581692895/22413/

**Comment by alexrollin** [comment]
again https://secure.helpscout.net/conversation/1583161282/22474/

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1572254743/21983/
