### ISSUE TITLE
Restart Install Wizard missing

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#178]
I have not found a button to rerun the wizard. I have not checked if the button is missing in general (because I went through the wizard) but maybe I did something wrong and want to restart the wizard. The first page is telling that I can come back anytime :)

![pic42](https://user-images.githubusercontent.com/35274187/38160911-2fb4a1d2-34c5-11e8-8345-5e627c85e8f3.png)

**Comment by Stiofan** [comment]
You can restart the wizard if you are in the GD settings page, use the help tab (top right).
![setup-wizard-restart](https://user-images.githubusercontent.com/10433311/38161657-39a5b5e0-34cb-11e8-8e84-d42a52723b40.png)

**Comment by DirkJahn** [comment]
Thanks for that. Is very hidden... Why not giving a hint where to find on the welcome page where you mention it?
