### ISSUE TITLE
Doc for list manager incomplete

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1783]
https://docs.wpgeodirectory.com/article/278-list-manager-setup-guide

the oroginal guide has more info - necessary info - https://wpgeodirectory.com/docs-v2/addons/list-manager/

please add at least the following points, refer to original doc for more details

the widget needs to be added to the details page , sidebar is recommended
adding to the gd archive item is optional
there should be a picture of what the widget looks like when installed
it should be made clear that ony public lists are visible to users besides the author

the lists will show at the url /lists/ - only public lists

if you have userswp installed

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1549340336/21025?folderId=3803506

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/278-list-manager-setup-guide?auth=true 
The part about public lists being viewable to users was already mentioned; added another line about it nonetheless. Also added the /lists/ page and the widgets clarification. 
Images of widgets in action can be found on the widget-specific pages, which are linked from this doc.
