### ISSUE TITLE
GD Status - Server Environment

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#179]
I think this is a little bit misleading now. With the PHP version you are behind the WP recommendation but with the MySQL you are recommending what WP is saying.

You should go completely with WP recommendations or what is really needed to run WP.

![pic43](https://user-images.githubusercontent.com/35274187/38160939-0fe75a4c-34c6-11e8-98ab-8b33da772e73.png)
![pic44](https://user-images.githubusercontent.com/35274187/38160941-122f5b1a-34c6-11e8-817e-c969749d0e87.png)

**Comment by Stiofan** [comment]
This is objective, in reality WP supports very old vers of PHP, this is a GD recommendation not a WP one, we support PHP 5.3+ but its better for you to run newer versions for speed, the same goes for MySQL but also security is considered.  There is no definitive answer, only recommendations

**Comment by DirkJahn** [comment]
Yes, but then you should not recomment PHP7.0 as this is already out of active support.

http://php.net/supported-versions.php
