### ISSUE TITLE
Doc update for information about pricing manager packages and expirations

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1790]
please add info to this doc https://docs.wpgeodirectory.com/article/150-how-do-recurring-price-packages-work

Expiration of listings

how expire date affects recurring & non recurring listings

some customer thinks their recurring listing will expire seen expire date not update

in general recurring listing only expire/downgrade when subscription cancelled/completed/deleted

in short expire date has no impact on expiry of recurring listing until subscription cancelled/completed/deleted

we have explained to many customer as we don't have proper doc for this

**Comment by alexrollin** [comment]
ask to Kiran or I in #dev-chat if you have questions @sufyanism

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/150-how-do-recurring-price-packages-work?auth=true 
Is this sufficient?
