### ISSUE TITLE
Ninja Form - EMail & Actions

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#181]
"Store Submission". More leftovers...

![pic46](https://user-images.githubusercontent.com/35274187/38161149-c1d8898a-34c9-11e8-8198-5351f6f34dda.png)

**Comment by Stiofan** [comment]
This is a Ninja Forms feature where it "stores" the submissions...

**Comment by DirkJahn** [comment]
Yes, but then the naming is wrong. It should be "Submission Store" and not "Store Submission". All the other namings are just nouns.
