### ISSUE TITLE
Kadence Restaaurant 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1817]
Fix to menu CSS done, member reports

Thanks…but while it has fixed the original issue it has created another….on both the demo site and my own with the .css tweak.

The top portion of the mobile menu is now covered by what I assume is the #masthead area. Enough to hide the top (Home) link and possibly others.

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1566166042/21752?folderId=3803591

**Comment by basantaux** [comment]
@alexrollin the issue has been resolved in Demo site with little change in the structure.
The customer can now remove the custom CSS that ge gas added for the #masthead. 
If he don't want to import the page again. He can follow this steps.
1. Please move the header content section to inside the image section.
![Screenshot 2021-07-13 at 4 03 57 PM](https://user-images.githubusercontent.com/52257358/125437987-d0f901d7-435b-4b39-93fa-71d810ec7eb2.png)

2. Change the mobile margin of the header content section
![Screenshot 2021-07-13 at 4 08 22 PM](https://user-images.githubusercontent.com/52257358/125438273-324671f0-02e2-4f23-ada8-d988d5a00d6a.png)

The final output would be like this
![IMG_6B038D999820-1](https://user-images.githubusercontent.com/52257358/125438334-6f23517e-67cc-4721-82c7-e2ef75ed2c7a.jpeg)

Hope this helps!
Thanks
