### ISSUE TITLE
Doc need for recent releases on 2021-07-14

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1821]
On 2021-07-14 we release GeoDirectory v2.1.0.18, Claim Listings v2.1.0.5, Location Manager v2.1.0.13, Pricing Manager v2.6.1.0 & Review Rating Manager v2.1.0.6.

Pricing Manager v2.6.1.0 includes one new feature "Limit posts per package user can add".

We need documentation in add/edit package setting for the new option "Limit Posts Per User" which used to set limit for the user that can add under current package.

- Llimit only applicable to non admin users
- Option "Limit Posts Per User" available in package setting to set limit.
- There is also post limit setting in CPT with checks total posts per CPT.

Let me know if you have a query.

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/236-how-to-add-a-new-pricing-package?auth=true
