### ISSUE TITLE
Warning on Search page if we run on PHP8

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#1822]
![image](https://user-images.githubusercontent.com/208945/125755203-5fee0a94-5307-4d55-8c5b-2c0473bd56e5.png)

This isn't happening on PHP version 7.4.1.

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1603753839/23326?folderId=3812058

**Comment by kprajapatii** [comment]
Fixed
