### ISSUE TITLE
Demo mobile issue

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1829]
Business hours z index on mobile

https://demos.ayecode.io/kadence-restaurants-directory/restaurants/united-states/california/san-francisco/cucina-e-vino/

![image](https://user-images.githubusercontent.com/114659/126182235-683834c3-24a3-4108-aac6-bf9064d89a51.png)

https://secure.helpscout.net/conversation/1575197367/22133/

**Comment by basantaux** [comment]
Fixed
![Screenshot 2021-07-20 at 5 11 58 PM](https://user-images.githubusercontent.com/52257358/126318120-a4fb6e28-23be-4ad3-a721-4a778678be5a.png)

**Comment by alexrollin** [comment]
Can you advise what the fix is @basantaux ?

**Comment by basantaux** [comment]
@alexrollin , Can you please suggest the. customer to change the location of the Business hour to rightside bar?
Its creating issue there. 
![Screenshot 2021-07-21 at 4 49 59 PM](https://user-images.githubusercontent.com/52257358/126480935-94577c02-2c1d-42c8-85f3-fd73993579a3.png)
