### ISSUE TITLE
EMail or Contact EMail should not be required

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#183]
It is not possible to disable or enable "required" for

![pic48](https://user-images.githubusercontent.com/35274187/38161477-c6582e92-34cf-11e8-893b-2bd6a132d423.png)
 Email and Contact Email field.

**Comment by DirkJahn** [comment]
Forget about it. I'm on a new installation and the "Advanced" is on.

I really don't like this function as it is always a burdon to click on this button. This is a trap for misunderstandings. I now strongly recommend to rethink this idea.
For me personal this is something that I'm getting a headache again and think that this is letting me to continue testing and wait until you are doing your job!
Very very frustating!

**Comment by DirkJahn** [comment]
The "Contact Email" should by default not required.

**Comment by DirkJahn** [comment]
I did my workout, took a shower and let's look on it again. I understand that you are adding settings in order to be more customizable and don't like to show all these settings to the "By Click Website Builders".
But I'm struggling with what is advanced and what is standard? I'm adding a new comment with my view in the custom fields

**Comment by DirkJahn** [comment]
What is now in the **standard settings** of custom fields:
- Field label
- Field description
- Is active (is here a "?" missing? The below one has one)
- Show in what locations?

The rest is advanced settings.

I would like to have
- Is required

as a standard option. This is used very often (for my understanding).

I also suggest to have an additional "Show advanced" button right aligned to the save button. If you have a long list and has opened the cutom field you are not seeing the "Show Adanced" anymore. 

![pic50](https://user-images.githubusercontent.com/35274187/38161836-7a4b8ab0-34d6-11e8-94ea-fb40f43429f2.png)

**Comment by Stiofan** [comment]
CPT settings, required toggle now shown as standard - CHANGED
CPT settings, show/hide advanced settings button moved inside settings - CHANGED
CPT settings, opening one setting will now close all others - CHANGED
