### ISSUE TITLE
doc setup GA

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1838]
This doc needs another step that says each package must be granted access to GA

https://docs.wpgeodirectory.com/article/301-gd-frontend-analytics

this is under the advanced settings and requires pricing manager

![image](https://user-images.githubusercontent.com/114659/126975323-b4ba0f4f-6040-455d-8d1f-a69c5a00d4ef.png)

the element is most commonly added as a widget to appear in the sidebar of the details page template or as a shortcode in the details page template.

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/301-gd-frontend-analytics?auth=true
