### ISSUE TITLE
Kadence Restaurant search z axis

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1840]
https://demos.ayecode.io/kadence-restaurants-directory/gd-archive-2-copy/?geodir_search=1&stype=gd_place&s=+&snear=&sgeo_lat=&sgeo_lon=

![image](https://user-images.githubusercontent.com/114659/127144509-a747156b-1a23-48da-8ca8-edd9d7e38a27.png)

We have issues with z axis layers fr these search dropdowns all the time. should they always be on top?

**Comment by basantaux** [comment]
fixed,
![Screenshot 2021-07-27 at 10 30 49 PM](https://user-images.githubusercontent.com/52257358/127196703-593593a6-1cd4-4d6a-a3a8-8f2d85c50d7c.png)

just changed the z-index value of search section

![Screenshot 2021-07-27 at 10 31 18 PM](https://user-images.githubusercontent.com/52257358/127196762-71ce96d7-bde8-4b8a-b5e5-f5603b5be83a.png)
