### ISSUE TITLE
Doc Dynamic Content Snippet

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1841]
Add co for snippet for advanced dynamic content

https://docs.wpgeodirectory.com/article/53-gd-dynamic-content

https://secure.helpscout.net/conversation/1522356383/0/?folderId=3803509

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/626-add-custom-conditions-to-dynamic-content-widget
