### ISSUE TITLE
Docs needed for releases

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1843]
GeoDirectory v2.1.0.19
- New feature to provide slider option in GD > Listings. widget. Options available in GD > Listings widget.

Events v2.1.1.6
- New feature added to unpublish/remove expired events. See https://github.com/AyeCode/events-for-geodirectory/issues/58#issuecomment-886722074

**Comment by sufyanism** [comment]
Docs edited to reflect new features.
