### ISSUE TITLE
video iframe have extra top padding 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1846]
https://secure.helpscout.net/conversation/1584732280/22534?folderId=3812058

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1583777198/22501?folderId=3812058

**Comment by kprajapatii** [comment]
Fixed

Legacy https://github.com/AyeCode/geodirectory/commit/00bdaee9d195bc7905c0b6dac6ad524ee23045d8
AUI https://github.com/AyeCode/wp-ayecode-ui/pull/37/commits/1a3c8cf3f30af53210882ebba6274899f4d5ee46
