### ISSUE TITLE
Hide optional fields on add-listing with CSS (and show on edit listing page)

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#185]
With V1 it was difficult for members to hide fields on the Add-Listing page and then expose those same fields on the Edit Listing page. The objective was to make the add listing form simple and quick, and then followup to allow users to add more information later.
However, this was difficult because the add and edit pages used the same CSS classes and so targeting for add VS edit wasn't easy or possible.

Will there be a fix for this in V2?

Related topics
https://wpgeodirectory.com/support/topic/different-fields-in-add-listing-and-edit-listing/

**Comment by Stiofan** [comment]
i'm not even sure that is a good idea... but v2 auto saves the info anyway so u can come back and the info will still be there
