### ISSUE TITLE
Franchise doc update

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1859]
This is the setup doc, 

https://docs.wpgeodirectory.com/article/311-franchise-manager-setup-guide

and it should really have a final step that points here:

https://docs.wpgeodirectory.com/article/310-how-to-add-main-and-branch-listings

I know it is in related links, but, it should be IN the doc i think.

Also, the setup doc has a screenshot of the package info? But it needs this screenshot too, of the franchise related fields in the package itself

![image](https://user-images.githubusercontent.com/114659/128095021-fed7133a-0f22-4734-9f7d-132db5c17a5d.png)
https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings&tab=cpt-package&section=add-package

https://secure.helpscout.net/conversation/1590265767/22741/

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/311-franchise-manager-setup-guide?auth=true
