### ISSUE TITLE
CSS Targeting in GDV2

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#186]
Output GD elements in such a way that  simple instructions can be provided for how to target 'any' CSS for GD.

For example:

Target any element like:

Widget heading:

.gd .gd-widget h3 {color: blue;}

Shortcode heading:

.gd .gd-ss h3 {color: blue;}

**Comment by Stiofan** [comment]
The point of GDv2 is to get away from this, we use the theme templates, so this would be theme specific.

You can (from next ver) target fields like "geodir-field-".$field_key
