### ISSUE TITLE
EMail Link wrong

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#187]
I used custom field Contact EMail and no contact form. It is generating the wrong href. I think I read this already in the forum. In the href is only "mailto:@".

![pic53](https://user-images.githubusercontent.com/35274187/38163474-24251ba0-34f5-11e8-9641-a8902f4d0804.png)

**Comment by Stiofan** [comment]
This is spam prevention, the link should work as normal but screen readers can read it.

**Comment by DirkJahn** [comment]
It is just opening an email client with @ in the address field.

**Comment by DirkJahn** [comment]
have you checked it?

**Comment by DirkJahn** [comment]
I'm not writing these things for fun!

**Comment by Stiofan** [comment]
checked and fixed

**Comment by DirkJahn** [comment]
confirm, it is working now. Thanks
