### ISSUE TITLE
Elementor integration "Feature image" not working

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1871]
The template is not working with the 'featured image' setting.
Instead, it only works when set to the GD post_images field.

Can we get a fix for this? 
3 tickets in the last week because the default install doesn't work.
https://secure.helpscout.net/conversation/1607250302/23483?folderId=3803506

![image](https://user-images.githubusercontent.com/114659/130252121-b41a2606-2fa2-4131-b183-19b2b736be4b.png)

This is how it has to be set to work

![image](https://user-images.githubusercontent.com/114659/130252735-9affc4df-cda4-4fe6-9939-0939b7b4dc9e.png)

Also, the preview for images doesn't work. Would be nice to have.

**Comment by kprajapatii** [comment]
@alexrollin i can't reproduce this on my local site. Could you provide steps to reproduce?

**Comment by alexrollin** [comment]
Install the default GD Single template and verify it has the featured image selected
add a listing with a featured image and check details view, image will not show
edit gd details and swithc header section to gd post images now image will work
https://secure.helpscout.net/conversation/1693687661/26382/
