### ISSUE TITLE
CPT settings doc needs update, new options available

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1872]
Please add all options here:

https://secure.helpscout.net/docs/5e5d013e04286364bc961540/article/5edf61f32c7d3a10cba89c5a

I would kindly request that this include all the settings available on the post type general settings when ALL GD addons are enabled - with notes about which plugins provide which settings if not core.

**Comment by sufyanism** [comment]
https://docs.wpgeodirectory.com/article/222-settings-overview-for-post-type-cpt-settings-general?auth=true
