### ISSUE TITLE
Messing up with location via default locations

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#188]
I added a place with default location A.
Then I changed the default location to B.
The place still have his location in A.
When I edit the place and don't change the Lat/Lang or the address itself and save it, it is switching the location to B but keep Lat/Lang so the place is "physically" still in location A.
When editing the place with the changed default location B so that the location is changed, I would like to have this prevented or get a popup.

I know that this might only be important for the free users, but who knows...

**Comment by Stiofan** [comment]
I have added a warning that will only trigger if you already have listings and actually change the defautl city before save.
