### ISSUE TITLE
Business Hours - Time Zones?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#189]
It is unclear for me in what time zone you are defining the business hours. As I can see at the moment they are defined within the WP time zone (e.g. UTC). This is not mentioned anywhere.

If you have a global directory the location is not dealing with the time zone setting of the server or WP. A user will add the business hours within the local time definition (e.g. EST).

Please add a selectable time zone to the "Business Hours" field.

**Comment by pol76** [comment]
The core plugin works for 1 location only.

It should automatically use the time zone of the default location, definitely not the server time zone.

The location manager should take care of different time zones according to the location selected. If you are already selecting a location while adding a listing, there should be no need to select a time zone IMO.

**Comment by pol76** [comment]
https://developers.google.com/maps/documentation/timezone/intro

**Comment by DirkJahn** [comment]
Okay. But this is not working. I have the default location to Atlanta, GA, US and it shows me closed where it should be open. Atlanta is GMT-4.

**Comment by DirkJahn** [comment]
Thanks for the link. I checked with the Lat/Long and the current timestamp the response of the API:

![pic55](https://user-images.githubusercontent.com/35274187/38167552-090fd8a4-3537-11e8-953d-e94224adca71.png)

With this I can check what should be the local time:

![pic56](https://user-images.githubusercontent.com/35274187/38167554-16c3fcbe-3537-11e8-82e6-4199e996a3b5.png)

But the place is showing me closed:

![pic57](https://user-images.githubusercontent.com/35274187/38167561-2dbe7746-3537-11e8-902f-880cd45b378c.png)

**Comment by Stiofan** [comment]
Core uses the utc offset in wp general settings.

**Comment by DirkJahn** [comment]
Just a thought I had this morning. Some users like to have a directory without locations. I can think on a directory of call centers. Also these should have business hours. With the google maps API approach this would not work.

**Comment by DirkJahn** [comment]
I have checked that it is working with the WP time offset settings. For the core this is okay, I think.

**Comment by Stiofan** [comment]
The new plan is to set the site timezone when adding the default location (incase users don't set the WP time correctly or are doing a directory outside their current timezone)

**Comment by kprajapatii** [comment]
Fixed
https://github.com/AyeCode/geodirectory/commit/3bffc9330bff57db320fa301d80971635a791252
