### ISSUE TITLE
WPML New features testing

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1895]
Email from WPML:
Steps to ensure compatibility with WPML 4.5
WPML logo
To all our compatible partners,

I'm reaching out to let you know that WPML 4.5 is coming in September and it's our biggest release in years.
email-wpml-4...
It introduces the Translate Everything mode, which allows users to translate all their site content automatically as they create it.

We're doing our best to minimize any compatibility issues our mutual clients may face, but we do need your help.
Steps to help our clients and reduce potential issues
01.

Please review your WPML language configuration file now to ensure full compatibility with the new translation mode.

This means registering all your theme/plugin elements (custom post types, fields, taxonomies, page builder widgets/shortcodes, Gutenberg blocks, etc) correctly - unregistered elements won't get translated automatically.
02.

Once you've updated your language config file, log in to your WPML account and visit the Retesting Dashboard to retest your component with the WPML 4.5 beta.​

Completing this step lets clients know your plugin or theme is compatible with this new mode.
03.

If you've published documentation that explains how our products work together, please update it to reduce any confusion when WPML 4.5 is live - we have put together this document to help you.
If you need any help, please don't hesitate to reach out to me. You can also learn more about WPML 4.5 in our latest announcement post.

Finally, we really appreciate you reviewing WPML-compatibility ahead of our release and hope that it's a smooth transition for our mutual clients to 4.5.

Thanks again and have a lovely day,

Olivia,
WPML Partnerships and Compatibility

**Comment by laranz** [comment]
## Translate Everything Workflow.

- [ ]  Country, Region, City not translating. Screenshot: https://user-images.githubusercontent.com/208945/131810264-1b4d23b2-a83c-4171-86bf-0c7d217a4a5f.png
- [ ] There is a word "Optional" in the categories. https://user-images.githubusercontent.com/208945/131810528-32f69ee7-7195-4b7d-b2dc-ed0507d65d15.png
- [ ]

**Comment by kprajapatii** [comment]
- Region & city values are not translatable. Make sure country is translated from WPML > String Translation.
- Mention steps, how to reproduce "Optional" word in categories issue.

**Comment by laranz** [comment]
1. OK.
2. Enable "Translate Everything" option, and created a new listing on English, wait for sometimes, and it will automatically translated it to other language, after it finishes it has that "Optional" value just like the screenshot. ( Just the normal flow )
