### ISSUE TITLE
Elementor deprecation warning on gd single template

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1898]
![image](https://user-images.githubusercontent.com/114659/132012321-307909cf-c7a1-49d3-811f-e025f6b97dd2.png)

See in console here

https://ppldb.com/v2/properties/smoky-mountain-sk8way/

Reported here:

https://secure.helpscout.net/conversation/1619214670/0/?folderId=3803591

**Comment by kprajapatii** [comment]
JS depreciated warning "`Scroll util from "/dev/js/frontend/utils/scroll"` is soft deprecated since 3.1.0 - Use `elementorModules.utils.Scroll` instead" coming from file /plugins/elementor/assets/js/common.min.js
