### ISSUE TITLE
Alternate fix to Custom field causing DB error 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1902]
https://secure.helpscout.net/conversation/1626030182/24146?folderId=3803511

Sometimes during field creation, the field got updated in the custom field table.
but the CPT detail table is not updated with a new field column. 

that cause DB error and does not allow the save field data insert query during post update/creation. 
<img width="1501" alt="Screenshot 2021-09-10 at 6 16 50 PM" src="https://user-images.githubusercontent.com/24760592/132859365-92e6cbfc-54eb-447c-95b7-d19c2fabed24.png">

**Comment by alexrollin** [comment]
Could we have an 'audit' tool in the custom field settings to check if the field is created properly?
