### ISSUE TITLE
Custom Fields - Key Helper

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#191]
Upon adding a new custom field, the field should receive a 'key' that is likely to be unique, perhaps with a 4 char UID appended.

Example, new email field, key 'email-DF38'

Right now when the new "Contact Email" field is added, the key is 'email' which is the same as the Email field, and so the user gets an error for a duplicate html variable

html variable should be changed to 'key' in the help text

![image](https://user-images.githubusercontent.com/114659/38165425-3e9a5720-3513-11e8-861e-32bae0a9e759.png)

**Comment by Stiofan** [comment]
i changed the text, but the plan in the future is fields like this will be a one time use thing, its basically just an email input with a predefined key name that can be used by other things, if u want a new one u just add a email field.

**Comment by alexrollin** [comment]
The issue was only that by adding two of them, there were key conflicts (because they had the same key name).

I think it is a usability issue, that, if a new field is added, it should not contain any data that will force the user to experience an error 'unless they "do something"'.
