### ISSUE TITLE
Can't edit GD block order, block properties in editor

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1914]
How to change block order, controls are hidden 'underneath'

https://ppldb.com/v2/wp-admin/post.php?post=935&action=edit#dummy_3

![image](https://user-images.githubusercontent.com/114659/134893724-3edda7b4-9806-465d-a187-19f16944e252.png)

![image](https://user-images.githubusercontent.com/114659/134893751-8ed186e4-774b-4017-a4cb-064d288f18b7.png)

**Comment by Stiofan** [comment]
Looks like more of a Kadence issue? Happens even with default blocks.

**Comment by kprajapatii** [comment]
It seems issue is coming from popover block editor component.

![block-editor](https://user-images.githubusercontent.com/7394489/134898472-4f3c178a-af4c-472f-9850-dd2906211662.png)
