### ISSUE TITLE
Custom field - price - validation and validation message

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#192]
1. The price validation is not working for me. I cannot enter anything without validation error.
2. I'm getting a mixed language validation message.

![pic54](https://user-images.githubusercontent.com/35274187/38165724-5822e504-3518-11e8-8c6b-53f3e81a09a9.png)

**Comment by DirkJahn** [comment]
Could you please recheck your validation pattern for the price custom field.

Maybe I'm wrong, but with regex I'm getting this one: \d+(\.\d{2})?

**Comment by DirkJahn** [comment]
And once you have this, it will not be possible to get it an empty field?

**Comment by Stiofan** [comment]
I don't see any problems, can u let me know how to recreate, what browser and ver of GD etc.

**Comment by DirkJahn** [comment]
I'm on a fresh installation of V2.0.0.8. I used the predefined price field and entering anything in the price field I'm getting this when clicking on "Publish":

![pic78](https://user-images.githubusercontent.com/35274187/38264528-892dd764-3773-11e8-8142-6e3b19e61e91.png)

When I'm clearing the field and click then "Publish" it is filled with:

![pic79](https://user-images.githubusercontent.com/35274187/38264548-9a459d02-3773-11e8-90c5-c2746db810d1.png)

**Comment by Stiofan** [comment]
I still can't replicate, i have forced the price field to be in EN format, it will be in next ver, if you still have problem after next release i will need to take a look at your site.

**Comment by Stiofan** [comment]
any change?

**Comment by DirkJahn** [comment]
Tested with 2.0.0.10 and still the same. I already wrote how to fix it...

**Comment by DirkJahn** [comment]
Any progress?

**Comment by Stiofan** [comment]
Fixed (though u will need to manaully change the validation pattern to 
\d+(\.\d{2})?
We strip slashes on the whole field but the validation pattern should have been excluded.
Thanks!
