### ISSUE TITLE
Custom Email Required - Cannot set to optional before save

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#193]
When adding a new custom email field, the field is by default set as required.
It is not possible to change the setting to Required:No, without first saving the field.

![image](https://user-images.githubusercontent.com/114659/38166126-dad63662-351e-11e8-8257-b2e9b43f9b9e.png)

**Comment by DirkJahn** [comment]
During my test this is happening if you add a second Email or Contact Email field. With the first one it is allowing to change the switches. Does this have anything to do with using the same field keys?

**Comment by Stiofan** [comment]
@alexrollin was this the predefined email field?  if so that is a bug here: https://github.com/AyeCode/geodirectory/issues/220  if not then i can't replicate.
