### ISSUE TITLE
Fallback image in gd_post_image shortcode should load title and meta from WordPress media metadata

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1933]
customer query, if post image shortcode showing category default image as a fallback image

it should load title or caption set in a wp media setting.

<img width="1178" alt="Screenshot 2021-10-08 at 8 32 42 PM" src="https://user-images.githubusercontent.com/24760592/136580233-db00def3-fb5f-4310-bc26-87c36e510922.png">

**Comment by alexrollin** [comment]
This OR it should NOT show title and caption at all for default images.
