### ISSUE TITLE
Business Hours: Add a Text if place is closed whole day.

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#194]
Could you please add something (like "Today closed") where you otherwise show the opening hours. This is looking weird.

![pic58](https://user-images.githubusercontent.com/35274187/38167613-31818f34-3538-11e8-80ca-9623d23db049.png)

**Comment by kprajapatii** [comment]
Fixed
See https://github.com/AyeCode/geodirectory/pull/221
