### ISSUE TITLE
Private Address Doc

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1948]
Add the "Private Address" option to GeoDirectory listings to prevent the display of address and map location.

With the Private Address feature your listing owners can hide their address and map location with the click of a button. Listings marked with a Private Address will still appear in GeoDirectory archives and keyword or IN search. Listings with Private Address marked are excludedfrom Near search or the 'Near Me' location page.

The Private Address is a checkbox

Steps
Open the Custom Fields settings.
Click "Private Address" to add the field, then save.
Drag and Drop to place the field where you like in the form.
Adjust the field description for your listing owners.
Edit a listing and mark the "Private Listing" field.

**Private Address Custom Field**

![image](https://user-images.githubusercontent.com/114659/138262718-024cec48-7093-4392-a23f-d546a9508110.png)

**Field Description**

If you are offering this option for private addresses, it may help to add some information to the address field description to clarify why the address field is still required. Here is some text to get you started:
​"Add your address here. Online Only? Choose the Private Address option and enter an address in the correct time zone so users will get the right start time for the event. No address or location info will show on the site."

**Private Address in the GD Details templates**

GD Map  widgets will be hidden, as well as map tab.

Address details will not show in GD Output Location, or with GD Post Meta, or GD Post Address

Address details and maps will still be visible to logged in Admins. 

**Private Address in the GD Archive item**

Listings marked with a Private Address will show the text "Private Address" where the address would normally be displayed in the GD Archive item.

![image](https://user-images.githubusercontent.com/114659/138261663-ee5b549c-c99e-4098-b446-61e6c5d16d31.png)

**Private Address with Location Manager**

Listings with Private Address marked will still show in Category+Location Archive pages as well as Location pages.

Listings with Private Address marked will not show in Near search results or Near Me location pages.

Read more about Location Manager

**Private Address with Pricing Manager**

The Private Address custom field can be included or excluded in Packages. 

Use it as an upsell opportunity for paid packages. Read more about Adding Packages

**Badge**

Set up a badge to show on listings with a Private Address using the 'private_address' key

![image](https://user-images.githubusercontent.com/114659/138261370-a1ea1349-0a5e-49f9-a744-5b76efd7858e.png)

Read more about GD Post Badge

**Translate or Localize Private Address feature**

The "Private Address" text string shown in the GD Archive item can be changed with normal localization of the GeoDirectory core PO file. Read more about localizing GeoDirectory.

**Comment by kprajapatii** [comment]
@alexrollin We have release Core + LM with Private Address feature. Please prepare doc.

**Comment by alexrollin** [comment]
done https://docs.wpgeodirectory.com/article/666-how-to-set-up-private-address
