### ISSUE TITLE
Avada builder not working for search page

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1955]
There seems to be no way to get the search page working with avada template builder.
https://secure.helpscout.net/conversation/1682417230/26016?folderId=3803506

To replicate visit /wp-admin/admin.php?page=avada-layouts
and set a global content section.  You can then try and create a new layout for search but it does not work, you can create one for archive pages which seems to work, but there seems to be an issue with the search page.

**Comment by Stiofan** [comment]
https://ppldb.com/aye/wp-admin/admin.php?page=avada-layouts
works here: https://ppldb.com/aye/gd-jobs/
not here: https://ppldb.com/aye/search-page/?geodir_search=1&stype=gd_jobs&s=+&snear=&sgeo_lat=&sgeo_lon=
Ping me if u have questions.

**Comment by kprajapatii** [comment]
Fixed and applied changes at https://ppldb.com/aye/search-page/?geodir_search=1&stype=gd_jobs&s=+&snear=&sgeo_lat=&sgeo_lon=
