### ISSUE TITLE
Schema incomplete

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#196]
As I'm not getting any feedback to #176 and you closed this far too early I opened a new issue.

I tested with V2.0.0.7 the schema is incomplete or not working. The schema definition in the Category is LocalBusiness, but I'm just getting some PostalAddress. In GDv1 I'm getting the whole LocalBusiness structure.

**Comment by Stiofan** [comment]
This has been updated and activated and is in latest 2.0.0.8-beta release
