### ISSUE TITLE
PHP 8+ Compatibility 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1962]
check all GD's latest add-ons with PHP 8+ and fix if any compatibility issues.

**Comment by Stiofan** [comment]
did u find any issues? i have been running v8 on my localhost for a few months

**Comment by 1naveengiri** [comment]
Yes,  maybe I haven't updated all my addons. 
I will re-check it and update it here accordingly.

**Comment by Stiofan** [comment]
i'll close this for now, just re-open it if u find any issues
