### ISSUE TITLE
Lazyload images dont work in elementor popup

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1964]
https://wordpress.org/support/topic/gd_listings-shortcode-in-elementor-popups-images-not-loading/#post-15061227

Maybe add a code snippet for the popup load and scroll when elementor is active?

Test site here: https://ppldb.com/elementor/index.php/testp/
popup: https://ppldb.com/elementor/wp-admin/post.php?post=106&action=elementor#

**Comment by kprajapatii** [comment]
Fixed

Please check https://ppldb.com/elementor/index.php/testp/
