### ISSUE TITLE
BuddyBoss Conflict: BuddyBoss removed GD CSS in profile page

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1965]
https://secure.helpscout.net/conversation/1688475565/26208?folderId=3812058

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1703772896/26715?folderId=3812058

Temp fix 

`add_action( 'bp_init', 'bp_include_geodirectory_scripts', 1 );
function bp_include_geodirectory_scripts(){
    remove_action( 'bp_init', 'bp_exclude_geodirectory_scripts' );
}
`

**Comment by 1naveengiri** [comment]
@kprajapatii  Buddyboss removing GD style on the profile page.  
can we add some permanent fix for it?

**Comment by kprajapatii** [comment]
I think this should be fixed from BuddyBoss side, because BuddyBoss removing GD style.

@1naveengiri

**Comment by 1naveengiri** [comment]
They are blaming us for it 
https://secure.helpscout.net/conversation/1898449347/32596?folderId=3812058

we have to some adjustments ourside.

**Comment by kprajapatii** [comment]
For now added it here https://docs.wpgeodirectory.com/article/712-buddyboss-compatibility-css-snippet
