### ISSUE TITLE
Places Sorting Options - No effect on sorting

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#197]
For example, adding Sort by title, and giving it a name for ascending and descending, these are visible on the "Places" page but they do not have any effect. I would expect the listings to be re-ordered based on title, Z-A or A-Z, but, no change.

![screenshot 2018-04-02 at 9 33 30 am](https://user-images.githubusercontent.com/114659/38187694-11e15e80-3659-11e8-81b1-a7e991ea3c92.png)

Related topic
https://wpgeodirectory.com/support/topic/gd-archive-sorting-options-not-working/#post-424517

**Comment by Stiofan** [comment]
FIXED
