### ISSUE TITLE
Kadence Issues

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1971]
Kadence breadcrumbs on search page showing : Home / Search results for " "

https://secure.helpscout.net/conversation/1709282283/26888/

Kadence styles and compatibility
https://secure.helpscout.net/conversation/1700915546/26617/

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1731556962/27594?folderId=3812058

**Comment by 1naveengiri** [comment]
Kadence extra page options are not working for GD pages. 

possible fix for compatibility ourside. 
https://gist.github.com/1naveengiri/c12bf27a1aee7894533686f2aab7007d

**Comment by kprajapatii** [comment]
We have requested Kadence team to add condition for GD archive pages. 

@1naveengiri
