### ISSUE TITLE
Elementor Pro updated doesn't show GD layout types

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1972]
Have to select table view link at the bottom to see them listed.
wp-admin/admin.php?page=elementor-app&ver=3.4.8#/site-editor/templates/single
![image](https://user-images.githubusercontent.com/114659/143914598-07dc6ac0-5454-49f3-b336-fc2a0d5098b4.png)

Reported twice already
https://secure.helpscout.net/conversation/1704086110/26727?folderId=3803506

**Comment by kprajapatii** [comment]
@alexrollin I see it even don't shows non GD layouts. https://ppldb.com/elementor/wp-admin/admin.php?page=elementor-app#/site-editor/templates

Do you see non GD layout types?

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1714529000/27077/

**Comment by alexrollin** [comment]
working example
![image](https://user-images.githubusercontent.com/114659/144613648-338ea3dd-c9af-4d0d-839a-8445ba5c904e.png)

**Comment by kprajapatii** [comment]
@alexrollin I applied changed on our test site, Could you check and confirm? https://ppldb.com/elementor/wp-admin/admin.php?page=elementor-app&ver=3.4.8
