### ISSUE TITLE
Select2 conflict with Yoast.

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#1974]
On a fresh install with only GeoDirectory + Yoast causing this issue.

![image](https://user-images.githubusercontent.com/208945/144431928-d6c638a9-0024-47a0-a070-42a9c600ae3f.png)

Naveen had this code snippet to fix the issue.

```
add_action( 'admin_enqueue_scripts', 'remove_default_stylesheet',99 );
add_action( 'admin_enqueue_scripts', 'remove_default_stylesheet',99 );
function remove_default_stylesheet() {

	$screen         = get_current_screen();
	$screen_id      = $screen ? $screen->id : '';
	$geodir_map_name = GeoDir_Maps::active_map();
	$asdsadasd = geodir_get_screen_ids();
	
	if ( in_array( $screen_id, geodir_get_screen_ids() ) ) {
		wp_deregister_style( 'yoast-seo-select2' );
		wp_deregister_style( 'yoast-seo-monorepo' );
	}
}

```

Ticket: https://secure.helpscout.net/conversation/1714568814/27080/

**Comment by kprajapatii** [comment]
@laranz Please try this patch and check if there is conflicts yet on WP & GD pages. https://github.com/AyeCode/geodirectory/pull/1978/commits/01417116ec79923fb948409f036fce697e2407db

**Comment by laranz** [comment]
It works fine 🎊
