### ISSUE TITLE
Support Loco Translate

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1980]
Loco is growing in popularity
Unfortunately our 'variable' strings don't work well with it, like this 'ago' set 

![image](https://user-images.githubusercontent.com/114659/145569092-57ad268f-915c-46fa-ac21-347909082119.png)
https://secure.helpscout.net/conversation/1721985057/27308/

**Comment by kprajapatii** [comment]
AUI textdomain is not loaded via Loco .po translation, because AUI is library and it don't loaded via plugin textdomain. See https://secure.helpscout.net/conversation/1721985057/27308/#thread-5061640591
