### ISSUE TITLE
GD Widgets don't show in elementor search and are 'lost' in WordPress widgets section

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#1996]
Search GD, nothing there!

![image](https://user-images.githubusercontent.com/114659/147474675-0ca270b4-e90f-407c-9c4b-b21d343d81a9.png)

They are here, though, but, can we put them in a 'plugin' section called geodirectory?

![image](https://user-images.githubusercontent.com/114659/147474646-caea5294-67f4-40c9-a6bf-1e3bd8cdefe0.png)

https://secure.helpscout.net/conversation/1740119336/27769/

**Comment by kprajapatii** [comment]
Elementor v5.0 have added option to show/hide native WordPress widgets from search results. See https://secure.helpscout.net/conversation/1740119336/27769/#thread-5112746544

As of now no option to set our widgets in separate category. Elementor has put this feature as Experiment.

@alexrollin

**Comment by alexrollin** [comment]
ty will doc it
