### ISSUE TITLE
Default value not working

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#200]
I think this is also in v1 that default values are not working. I tested it with a phone number, but it is not working for all custom fields.

If this is by design not working, please remove this parameter from the custom fields where it is not working.

**Comment by Stiofan** [comment]
i'm going to be doing a bit of work on CFs so i'm gona leave this open and come back to it after.

**Comment by DirkJahn** [comment]
This is driving me crazy. Why does on "Special Offers" the default value is working and on others not. Make it please consistent in the next release!

**Comment by Stiofan** [comment]
Default implemented as default field value and new "placeholder" option also added
