### ISSUE TITLE
[Feature Request] Save Progress while adding listings.

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#2001]
Hello, Is it possible to add a save progress the listings? I would like to be able to add some sort of save function so people can complete a listing at another time if they can't finish in 1 go. 

Ticket [ID](https://secure.helpscout.net/conversation/1758970146/28300?folderId=3803506)

**Comment by Stiofan** [comment]
This is already a feature: https://secure.helpscout.net/conversation/1758970146/28300/
