### ISSUE TITLE
Divi builder header and footer style is not maintained for GD pages

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2003]
https://secure.helpscout.net/conversation/1758197604/28276?folderId=3812058
https://secure.helpscout.net/conversation/1150124345/1395/

**Comment by 1naveengiri** [comment]
Divi maintains a different style sheet for CPT's and somehow it does not load all required style for added custom header/footer.

**Comment by kprajapatii** [comment]
No longer to reproduce it on test site. Meantime try snippet as a solution. https://secure.helpscout.net/conversation/1150124345/1395/#thread-3288095883
