### ISSUE TITLE
Recently Viewed block don't fill the post_type automatically.

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#2007]
https://user-images.githubusercontent.com/208945/150575620-3741af3b-9468-45c7-9f95-2f06b0c23d84.mp4

This will cause issues if the user doesn't have Places post type or edited the slug.

Ticket ID: https://secure.helpscout.net/conversation/1757121663/28232?folderId=3844502

**Comment by kprajapatii** [comment]
This is normal behaviour when no post type selected it assigns gd_place as a default post type. gd_place post type can't be deleted.
