### ISSUE TITLE
Docs for Report Post feature in v2.1.1.12

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#2016]
- Report Post feature https://github.com/AyeCode/geodirectory/issues/1982

- Widget "GD > Report Post" with settings available to show "Report Post" button / form for listing.
- Click on button will open popup with form asking name, email and reason with report
- On submit report it sends notification to the admin.
- In backend page created under Settings > Reported  Posts to manage reported posts (delete/move to pending etc)

NOTE: This feature available for AUI style only.

Let me know if have any query.

@alexrollin @laranz @Guust-Flater

**Comment by Guust-Flater** [comment]
I ll take care of this doc.
Cheers

**Comment by kprajapatii** [comment]
Example: https://ppldb.com/kiran/properties/united-states/pennsylvania/philadelphia/eastern-lodge/

@Guust-Flater

**Comment by Guust-Flater** [comment]
https://docs.wpgeodirectory.com/article/677-gd-repor t-post
