### ISSUE TITLE
Shortcode gd_categories title_tag working on the wrong item

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#203]
When I change the title_tag it is not effective on the title. It changes the tag of the items (in this case of the categories).

![pic63](https://user-images.githubusercontent.com/35274187/38237750-4da8eeb8-3728-11e8-83b1-bfc8911c9429.png)

**Comment by Stiofan** [comment]
This is what that setting is for, i have made it more clear in the settings help tip

**Comment by Stiofan** [comment]
changed
