### ISSUE TITLE
Backend Add Shortcode

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#204]
Opening the "Add Shortcode" and then opening the "Advanced Settings" you don't use the whole window you opened. This is misleading as I thought all is already shown.

![pic64](https://user-images.githubusercontent.com/35274187/38238186-697431a6-3729-11e8-9882-0a8c4f33da51.png)

**Comment by Stiofan** [comment]
I can't replicate this, is there something i have to do?

**Comment by DirkJahn** [comment]
I tested it with chrome and edge.
1) Open Page to edit
2) Click on "Add Shortcode"
3) Select one with a lot of options (e.g. gd_categories)
4) click on "Show advanced"
and then I'm seeing the pic like above. Let me check your video. I can also see this in your video:
![pic82](https://user-images.githubusercontent.com/35274187/38267332-72e3218c-377b-11e8-93f8-42a26eba5583.png)

You don't see all options (the window is big enough) and you cannot see the "Hide advanced"!

**Comment by Stiofan** [comment]
AH, i made the video on my mac nor my normal machine (mic sucks) and i did not even notice it here, but i have recreated and fixt it. Thanks!
