### ISSUE TITLE
Backend Add Shortcode gd_categories - sub-cats

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#205]
Is this double? The tooltip say it is the same. (tooltip has the same description)

![pic65](https://user-images.githubusercontent.com/35274187/38238349-d49090ba-3729-11e8-8932-22ce53d77b7c.png)

**Comment by DirkJahn** [comment]
I guess that the tooltip is wrong. With the created attributes I again guess that the second one is counting. But then the title is wrong.

**Comment by DirkJahn** [comment]
Okay. This is really a mess. 

The list (numbers shown) and the values are wrong. If I select "2" I'm getting "8" and so on.

![pic66](https://user-images.githubusercontent.com/35274187/38239235-6e69495a-372c-11e8-8130-322f859fedbc.png)

**Comment by Stiofan** [comment]
The count was backwards and has been fixed.
The two tool tips are similar but different.
