### ISSUE TITLE
Text domain geodir_buddypress

### ISSUE THREAD

**Issue by Dotdocs** [AyeCode/geodirectory#2056]
The textdomain for the geodir buddypress integration addon is not loading.

It is fixed by 
1. adding:
   $this->load_textdomain();
in function __construct()
in /includes/class-geodir-buddypress.php

But also by correcting the Textdomain. It should not contain underscores according to:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

I did:
2. A search-and-replace (including the ' ' ) of all 'geodir_buddypress'  to 'geodir-buddypress'
3. Change Text Domain in geodir_buddypress.php to: geodir-buddypress
4. Replace the underscores of  geodir_buddypress.php, the plugin folder and the two files in /languages folder

Any other solutions or a version update soon?

**Comment by kprajapatii** [comment]
@Dotdocs I have just released BuddyPress Integration addon with textdomain fix.
