### ISSUE TITLE
Add shortcodes - Deselecting is removing the parameter

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#206]
In the Add Shortcode (e.g. gd_categories) you have standard activated parameters (e.g. show count). If you deselect "show count" you are removing the parameter out of the shortcode, but as I guess the count here is standard "on" you are not removing the counts.

![pic67](https://user-images.githubusercontent.com/35274187/38239544-52c7619a-372d-11e8-8839-8c094b05fbc3.png)

**Comment by Stiofan** [comment]
Good spot, yes textboxes are weird, they don't even register if empty...  I have changed the functionality to keep inline with the rest of the options.
