### ISSUE TITLE
German Address Format Supporrt on Add Listing form.

### ISSUE THREAD

**Issue by laranz** [AyeCode/geodirectory#2060]
![image](https://user-images.githubusercontent.com/208945/160835278-93015d80-9d71-4667-9ca6-42184e3d94b7.png)

In the address part of the add listing form, they want the zip code to be first, and then city, then region and then country.

Ticket ID: https://secure.helpscout.net/conversation/1830724606/30759?folderId=3844502

**Comment by alexrollin** [comment]
duplicate https://github.com/AyeCode/geodirectory/issues/1063
