### ISSUE TITLE
GD > post meta is not adding field link to icon option

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2073]
https://secure.helpscout.net/conversation/1839270708/31062?folderId=3812058

When a social media icon is printed using the GD > post meta shortcode with the display only icon.
it is not adding the social media link to the icon.

**Comment by kprajapatii** [comment]
This is not a bug. Post meta icon option shows icon set in field stetting. It don't adds links to it. Link only added when displaying value. This can be achieved by post badge.
