### ISSUE TITLE
At gd_listings the selection of list/columns missing

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#209]
I have not found something to add the list, 2 columns etc. view at the gd_listings presentation. The shortcoded [gd_loop_actions] is not working before [gd_listings].

I don't understand why you have this shortcode. Why not use the concept from the template pages.

**Comment by Stiofan** [comment]
I still need to lock down some things that can only be used in certain places.
The gd_listings SC has a (miss labeled) setting for that.

This widget might be used in the sidebar where two is the max, if users set 5 it will be a mess...
