### ISSUE TITLE
Classifieds/Real-Estate Sold Settings not possible to undo

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2103]
It is not possible to undo the "mark as under offer" feature, u suggest making the button be ticked and highlighted, and then unticking removed it. 

Also, doing this should also try to set the "sale status" custom field if exists such as with dummy data.

**Comment by kprajapatii** [comment]
Fixed

Three ways to undo sold/under offer/sales agreed status:

- From the backend edit listing page via post status
- From the frontend edit listing via Sale Status field
- From the frontend listing author actions

You can check at here: https://ppldb.com/kiran/properties/united-states/pennsylvania/philadelphia/buddakan/

**Comment by Stiofan** [comment]
Good work Kiran!
