### ISSUE TITLE
gd_listings - business hours

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#214]
If you have business hours and defined it e.g. to be shown in sidebar, the gd_listing is generating it anyhow.

Backend:

![pic71](https://user-images.githubusercontent.com/35274187/38244103-d939be4c-3739-11e8-9426-6da518484459.png)

Frontend:

![pic72](https://user-images.githubusercontent.com/35274187/38244110-dcd8b148-3739-11e8-8b96-db42f306575c.png)

**Comment by DirkJahn** [comment]
And if you define it in the backend to be in the listings you will get it twice.

**Comment by Stiofan** [comment]
This is how it works, there are many ways to add info. I don't see the problem?

**Comment by DirkJahn** [comment]
When I'm deleting any of the options in "Show in what location?" it is still shown in the listings.

If I add the location "listings" I see it twice:

![pic80](https://user-images.githubusercontent.com/35274187/38266191-504d0726-3778-11e8-8924-273fab7433cd.png)
![pic81](https://user-images.githubusercontent.com/35274187/38266198-53370f0e-3778-11e8-9b25-02a278332bf9.png)

**Comment by DirkJahn** [comment]
Okay. Found the problem. Was in the "GD Archive item".

Close it! Thanks

**Comment by DirkJahn** [comment]
Could you please think about it if it makes sence that in the installed "GD Archive item" you have this added with [gd_post_meta ...]. I think more people will trap into it.

**Comment by Stiofan** [comment]
i don't understand your last comment?, closing, get me on skype if u can't reply here

**Comment by DirkJahn** [comment]
You have per default a [gd_post_meta ...] with the business hours in the GD Archive item page. You can add this as a location (listings) in the custom fields.
So my proposal is to remove the gd_post_meta from the GD Archive item
