### ISSUE TITLE
gd_post_address more formatting

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#2146]
please add street2_br and street2_brc

a new _c for all options would also be very helpful!

https://secure.helpscout.net/conversation/1943059637/0/?folderId=3803506

**Comment by kprajapatii** [comment]
We already support _br, _brc & _c. We support 5 variables at the moment mentioned at here https://github.com/AyeCode/geodirectory/blob/master/includes/custom-fields/output-functions.php#L2453

Example: https://ppldb.com/v2/gd_post_address/

@alexrollin
