### ISSUE TITLE
gd_listings - sorted "featured"

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#215]
I have added the predefined field "featured" and with gd_listings sorting on "featured" is not working.

![pic73](https://user-images.githubusercontent.com/35274187/38245089-145c949c-373d-11e8-8c3e-8aaa260415b1.png)

**Comment by Stiofan** [comment]
are u using Featured DESC sort order?

**Comment by DirkJahn** [comment]
Used this shortcode:
[gd_listings title="List View and Sorted Featured" post_type="gd_place" sort_by="featured" title_tag="h3" layout="list" post_limit="5" add_location_filter="1"]

**Comment by Stiofan** [comment]
This has changed and can now use custom set sort options which solves this issue.

**Comment by DirkJahn** [comment]
Could you please give me a documentation about it. Without I cannot test.
