### ISSUE TITLE
GD > Listing shortcode must have an option to show expired posts to users on user profile

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2151]
https://secure.helpscout.net/conversation/1948064064/33936?folderId=3812058

**Comment by kprajapatii** [comment]
Expired posts only visible on author posts listings.

On profile page it needs to use snippet and use is_gd_author=1 in gd_listings shortcode.

`function gd_snippet_current_profile_listings( $arguments, $options, $instance ) {
	if ( ! empty( $options ) && isset( $options['base_id'] ) && $options['base_id'] == 'gd_listings' && ! is_admin() && is_page() ) {
		$arguments['is_gd_author'] = array(
			'title' => 'Is GD Author Page?',
			'desc' => __( 'Tick to show current logged author listings.', 'geodirectory' ),
			'type' => 'text',
			'default' => '',
			'desc_tip' => 1,
			'placeholder' => '',
			'advanced' => 1,
			'group' => __( 'Filters', 'geodirectory' )
		);
	}
	return $arguments;
}
add_filter( 'wp_super_duper_arguments', 'gd_snippet_current_profile_listings', 10, 3 );`
