### ISSUE TITLE
CPT Meta widget - optional to display on CPT page only OR on CPT and Category pages

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#2163]
If adding these shortcodes to Archive:

[gd_cpt_meta key="description"]
[gd_category_description]

then CPT description displays on all category pages too, with the result that it shows CPT description AND category description.

Also, both CPT and category pages have exactly same body classes, so CPT and category pages cannot be targeted specifically.
Maybe add a class that is related to the category ID or slug too, then targeting pages has more options.

Thanks

**Comment by alexrollin** [comment]
+ 1 body class for category specific archives, 
+1 for body class with cat id in the

**Comment by kprajapatii** [comment]
Following class added to body tag for related GD pages
**geodir-page-term** - On GD category/tag pages.
**geodir-page-term-TERM_ID** - On GD category/tag pages. Ex: geodir-page-term-11
**geodir-page-TAXONOMY** - On GD category/tag pages. Ex: geodir-page-gd_placecategory
**geodir-page-cpt** - On GD post type archive pages

@alexrollin
