### ISSUE TITLE
gd_listings uses GD Archive Item

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#217]
Does this really make sence?

I would love to have here a very generic approach. Why not give [gd_loop] an id for the item to get.

[gd_loop id="10"] for getting the page with id for the items
[gd_loop id="23"] etc.

Then you can do all this gd_listings things with the loop if you add here the attributes of the gd_listings shortcode.

[gd_loop id="10" title="My Listings" post_type="gd_place" related_to="tags" sort_by="az" title_tag="h3"  post_limit="5"]

I guess the layout should be then in the [gd_loop_actions].

**Comment by Stiofan** [comment]
This is by design, i did think about making just one widget but they use different queries and different settings for sort etc.  It would have actually complicated things not made things easier.
