### ISSUE TITLE
Some FontAwesome icons are missing in custom field icon picker

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#2176]
Ex:  fas fa-door-closed is missing.

**Comment by kprajapatii** [comment]
We need to update icons from the JS files https://cdnjs.com/libraries/fontawesome-iconpicker

**Comment by Stiofan** [comment]
I think the issue is that things don't seem to show up in the search if there are no search terms

**Comment by kprajapatii** [comment]
It is working here https://itsjavi.com/fontawesome-iconpicker/, because icons are included in JS file https://itsjavi.com/fontawesome-iconpicker/dist/js/fontawesome-iconpicker.js

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/c84bcc504e18e7704970289f43447efa601f5927
