### ISSUE TITLE
Favorites not working

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#219]
From the gd listing clicking on the "heart" I'm getting a script error (incl. 403 error).

![pic75](https://user-images.githubusercontent.com/35274187/38246924-a9ecf6e0-3743-11e8-98f1-f05e7350b45c.png)

If I click from the map bubble I'm forwarded to the login page even if I'm already logged in. After the relogin I'm getting a nice output.

![pic76](https://user-images.githubusercontent.com/35274187/38246933-b4bfd70e-3743-11e8-925b-2f2448623a13.png)

**Comment by DirkJahn** [comment]
LOL... I have to seen it in the forum. Could you please check if it has been fixed also from the map bubble?
Thanks.

**Comment by Stiofan** [comment]
both issues fixed and will be in the next release.
