### ISSUE TITLE
Gd >badge does not support gd-lity popup in bootstrap design

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2195]
https://secure.helpscout.net/conversation/1994187673/35323?folderId=3812058

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1994268675/35325?folderId=3812058

**Comment by kprajapatii** [comment]
No way to show popup like lity in AUI because gd-lity & data-lity no longer working.
