### ISSUE TITLE
Gd > Image swipe animation on mobile is not working without autostart enabled

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2196]
https://secure.helpscout.net/conversation/1980004111/34849/

**Comment by 1naveengiri** [comment]
it can be reproduced here 
check this URL on mobile https://ppldb.com/v2/places/united-states/pennsylvania/philadelphia/sample-place-3/

the 2nd  image slider.

**Comment by kprajapatii** [comment]
Snippet applied, let's wait for the reply from customer.

`function gd_snippet_220922_fix_image_swipe() {
?><script type="text/javascript">jQuery(function($){if(jQuery('.geodir-image-container .geodir-carousel .carousel-indicators > li.active').length){jQuery('.geodir-image-container .geodir-carousel .carousel-indicators > li.active').trigger('click');}});</script><?php
}
add_action( 'wp_footer', 'gd_snippet_220922_fix_image_swipe', 99 );`
