### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2219]
<img width="1634" alt="Screenshot 2022-09-30 at 1 14 40 PM" src="https://user-images.githubusercontent.com/24760592/193223241-3322aa31-9b4e-48fd-a8d2-c13f3f1817dc.png">
https://secure.helpscout.net/conversation/2019342617/36058/

**Comment by Stiofan** [comment]
@kprajapatii please check @1naveengiri pull https://github.com/AyeCode/geodirectory/pull/2220/files
