### ISSUE TITLE
gd_best_of shortcode output?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#225]
gd_best_of is not working like expected. I see the following issues:
1) It is generating a title without defining it (see pic "Best of GeoDir 4")
2) It is creating DropDown and Tabs. Should only be one!
3) In the place listing featured images and default images are not working. No image is shown.
4) If I select tabs on the left it is messing up with the end of the page (see pic 2 - Edit is somewhere within the widget)
-> This widget needs love again.

![pic84](https://user-images.githubusercontent.com/35274187/38295310-e04d2444-37ed-11e8-9724-d69e297482a8.png)
![pic85](https://user-images.githubusercontent.com/35274187/38295318-e45518e4-37ed-11e8-9c74-31ca68172d40.png)

**Comment by Stiofan** [comment]
fixed
