### ISSUE TITLE
Search page "xxx"?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#229]
When I enter the search page I'm having "xxx" under the search bar...

![pic87](https://user-images.githubusercontent.com/35274187/38349875-4a4570f2-38a9-11e8-911c-7dae20b5c2e4.png)

**Comment by DirkJahn** [comment]
It is coming from [gd_loop]. If I insert it a second time I get it twice.

**Comment by Stiofan** [comment]
I was testing where to output the message, ots fixed in latest.
