### ISSUE TITLE
Conditional field issues

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2295]
https://youtu.be/jHFm5E4S8S0

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2132623270/39702/

the issue can be reproduced locally too.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/kprajapatii/geodirectory/commit/4c4de490c4e4617d8c15b7a3e11d6f68539e6225
