### ISSUE TITLE
Can't add a custom field to places

### ISSUE THREAD

**Issue by watels** [AyeCode/geodirectory#2314]
I want to add a custom field to my places. I go to places > settings > personnalized fields
I add a field text. But then on the right side I can't customize its name. I have no save button.

And when I leave the page and come back, the field has disappeared.
I tried on Chrome v110 and on Firefox v110
same issue.

**Comment by pol76** [comment]
Hi, 
please open a support request either here: 

https://wordpress.org/support/plugin/geodirectory/ 
or here 
https://wpgeodirectory.com/support/

Our support team doesn't provide software support opn Github.

Thanks,
