### ISSUE TITLE
Shortcode Builder - Give it also a GD Logo

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#233]
It is not clear that this is connected to GD. If you have later a lot of plugins installed you could get confused what button is for what. So I suggest to add a GD logo to the button.

![pic88](https://user-images.githubusercontent.com/35274187/38350515-e7b52f9c-38ab-11e8-8e07-a78ff8e4d1dc.png)

**Comment by Stiofan** [comment]
This icon pick was a last minute thing but it is part of a class library we have wrote, it wont just be used for GD but for all our plugins and we hope by otheres also. A better logo is needed, the class name is "Super Duper" if you have any suggestions :)
