### ISSUE TITLE
GD > Listing shortcode General tab is empty

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2331]
<img width="1211" alt="Screenshot 2023-03-28 at 6 36 59 PM" src="https://user-images.githubusercontent.com/24760592/228246178-be3c2669-2211-4bcb-ac62-a6c668a80e4b.png">

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2196229565/41929?folderId=3812058

**Comment by Stiofan** [comment]
need to click show advanced

**Comment by kprajapatii** [comment]
Events filters were in General group which shown only when Events post type selected. I moved those settings to Filters section. Now it will not show General section.

**Comment by 1naveengiri** [comment]
@kprajapatii  the general tab still shows up in the **GD > Listing** block
is it removed?

**Comment by kprajapatii** [comment]
It is coming from Events plugin and already fixed. It will be available in next update of Events plugin. Here is patch https://github.com/kprajapatii/events-for-geodirectory/commit/fcf0f30d3aa312357227f14b1711d7fcf51b7e3c#diff-4edd8f1d7faec4457e05602425a9af6ac1138c2c727f8f3b9a37ce36840bfda9
