### ISSUE TITLE
GD Archive item template not working in list view.

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#234]
Scenario:
Some information on the left and the pic to the right.

This is not working in the list view! I have not made any test how this should look like in the grid views.

![pic89](https://user-images.githubusercontent.com/35274187/38350913-ac5b6f40-38ad-11e8-90cf-900f9091d8d5.png)

I just entered "left" and "right" to the sections and what do I get?

![pic90](https://user-images.githubusercontent.com/35274187/38350920-b2de2222-38ad-11e8-899a-179dca015ea0.png)

**Comment by DirkJahn** [comment]
In the grid view I can see that the left section is above the right section, which looks okay for me.

**Comment by Stiofan** [comment]
using the below code, i could not replicate this:
```
[gd_archive_item_section type='open' position='left']
left
[gd_archive_item_section type='close' position='left']
[gd_archive_item_section type='open' position='right']
right
[gd_archive_item_section type='close' position='right']
```

**Comment by DirkJahn** [comment]
Is in the list view. I just made a new page and added this code to the page and I see "This is right" on the left and "This is left" on the right.:

```
[gd_archive_item_section type='open' position='left']
This is left
[gd_archive_item_section type='closed' position='left']
[gd_archive_item_section type='open' position='right']
This is right
[gd_archive_item_section type='closed' position='right']
```

**Comment by Stiofan** [comment]
type='closed' should be type='close'
