### ISSUE TITLE
WP Offload Media | Compatibiity

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2341]
https://secure.helpscout.net/conversation/2205151794/42237/
https://secure.helpscout.net/conversation/2147743748/40272
https://secure.helpscout.net/conversation/2088882551/38196
https://secure.helpscout.net/conversation/2020890042/36095
https://secure.helpscout.net/conversation/1430841978/15133

**Comment by 1naveengiri** [comment]
- user profile pic
- Business profile images uploaded by business owners
- Review images uploaded by reviewers

**Comment by kprajapatii** [comment]
duplicate
