### ISSUE TITLE
value-strip adding div

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#2342]
![gd-diviimage](https://user-images.githubusercontent.com/114659/231134168-928b744b-0cee-4f52-a97a-f8673b4f3dc5.png)

https://secure.helpscout.net/conversation/2203395222/42173?folderId=3803591

**Comment by kprajapatii** [comment]
Checked and it is working fine as expected.

1) **show='value-strip'** : strips HTML within value container & it don't strips parent wrapper.
2) **show='value-raw'** : shows raw value stored in database with parent wrapper.
3) **show='value-strip'  no_wrap='1'** : strips HTML within value container & it strips parent wrapper. as well
4) **show='value-raw'  no_wrap='1'** : shows raw value stored in database without parent wrapper.

To strip parent wrapper div it must use no_wrap=1.
