### ISSUE TITLE
Divi map issue on contact page

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2366]
https://secure.helpscout.net/conversation/2246184920/43616?folderId=3812058
https://secure.helpscout.net/conversation/2103014573/38628/

**Comment by 1naveengiri** [comment]
```
/**
 * Function to revert Geodirectory blocking Divi maps API
 */
add_filter( 'et_pb_enqueue_google_maps_script', 'et_pb_enqueue_google_maps_script_custom_callback_func' );
function et_pb_enqueue_google_maps_script_custom_callback_func(){
	$google_api_option          = get_option( 'et_google_api_settings' );
	$google_maps_script_enqueue = ! $google_api_option || ! isset( $google_api_option['enqueue_google_maps_script'] ) || ( isset( $google_api_option['enqueue_google_maps_script'] ) && 'on' === $google_api_option['enqueue_google_maps_script'] ) ? true : false;

	return $google_maps_script_enqueue;
}

```

**Comment by kprajapatii** [comment]
I checked contact pages on both sites https://dev.ae3.org/contact/ & https://thp-gdp.flywheelstaging.com/contact. But no one has map placed on contact page.

What error is shows & how to replicate the issue?

Whenever create a task on Git, please try to replicate an issue on our test site and add details how to replicate.

@1naveengiri

**Comment by 1naveengiri** [comment]
@kprajapatii  I will check if I can reproduce it.
