### ISSUE TITLE
Add Font Awesome 5 support

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#237]
As this is a new version you should also support the latest version of Font Awsome. The main class changed from "fa" to "fas".

**Comment by Stiofan** [comment]
There are a few reasons i don't want to use v5

1. v5 seems to be pushing the paid version more
2. The CSS version is still officially in beta, and by WP rules you can't load external JS files (you can only load external CSS font files)
3. Its bigger.
4. I have not seen anything new i have thought, "we need that"

**Comment by Stiofan** [comment]
ofcourse if the majority want it then it will be added, i'll need to do some research into it and its loading times and see when its coming out of beta

**Comment by alexrollin** [comment]
Related topic:
https://wpgeodirectory.com/support/topic/font-awsome-2/
