### ISSUE TITLE
Aye code v5 / GD listing carousel

### ISSUE THREAD

**Issue by khahina** [AyeCode/geodirectory#2379]
Hye,
GD > Listings , Style carousel didn't work when select Aye code v5. 
Custom-post are out the screen, neither with block or Elementor .

All plugins update, elementor pro (but same with just gutenberg page and block) , and licence membership Geodirectory

**Comment by Stiofan** [comment]
Hello, this has not been reported, i have been working with this today and I did not see any issues, I suspect it may be a conflict or some broken JS.  Have you opened a support ticket? https://wpgeodirectory.com/support/

**Comment by khahina** [comment]
Hye, 
not today. 

but will do .

The carousel work fine in V4.






De : Stiofan ***@***.***>
À : AyeCode/geodirectory ***@***.***>
Sujet : Re: [AyeCode/geodirectory] Aye code v5 / GD listing carousel (Issue #2379)
Date : 12/06/2023 18:10:46 Europe/Paris
Copie à : khahina ***@***.***>;
   Author ***@***.***>


Hello, this has not been reported, i have been working with this today and I did not see any issues, I suspect it may be a conflict or some broken JS. Have you opened a support ticket? https://wpgeodirectory.com/support/

**Comment by khahina** [comment]
i found it's the center parameter who do that, the carousel work fine if you did'nt tick this parameter.

**Comment by khahina** [comment]
So it's a carousel bug. But i can deal with it

**Comment by Stiofan** [comment]
did u open a ticket?

**Comment by khahina** [comment]
yes but I found how to avoid the problem, by unchecking the 'center' box for the carousel setting.


Thank you


---------------------------------------
https://moncoachwp.fr
ACEASCOP FORMASCOPE – Mon Coach WP 
Technoforum – Parc du Sanital -16 rue Albert Einstein – 86100 Châtellerault – France
***@***.***
RCS DE POITIERS 443 194 733 / RM 86
NUMERO DE TVA INTRACOMMUNAUTAIRE FR 70 443 194 733

De : Stiofan ***@***.***>
À : AyeCode/geodirectory ***@***.***>
Sujet : Re: [AyeCode/geodirectory] Aye code v5 / GD listing carousel (Issue #2379)
Date : 14/06/2023 11:33:02 Europe/Paris
Copie à : khahina ***@***.***>;
   State change ***@***.***>


did u open a ticket?
