### ISSUE TITLE
Request: Add "Disable Field Label Output" on Post Meta Display

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#238]
As the "post meta" widgets and shortcodes are becoming more familiar;

Would it be possible to allow Advanced Settings option for custom fields for 

"Disable Field Label Output"
"Disable Field Icon Output"

The result would be that "Address:"  and the Address icon would not be output.

![image](https://user-images.githubusercontent.com/114659/38419929-7d615cd6-39a2-11e8-8281-bf65af9f0cd3.png)

Related Topic:
https://wpgeodirectory.com/support/topic/start-testing-installation-and-places/page/2/#post-425118

**Comment by Stiofan** [comment]
Show options changed to allow for greater flexibility.
![meta-show-options](https://user-images.githubusercontent.com/10433311/39188971-fc6d7c42-47c8-11e8-9f6c-bdebf1f89db1.png)
