### ISSUE TITLE
Position map at a specific location on page load

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2381]
customer wants to position the map to the United state on page load. 

https://secure.helpscout.net/conversation/2271472236/44387?folderId=3812058

**Comment by 1naveengiri** [comment]
@kprajapatii its a popular request

**Comment by kprajapatii** [comment]
It can be achieved by snippet.

`function gd_snippet_map_params( $params, $map_args ) {
	if ( $params['map_canvas'] == 'gd_map_4' ) { 				// Replace map_canvas to own value
		$params['enable_marker_cluster_no_reposition'] = true; 	// Don't reposition after load
		$params['autozoom'] = false; 							// Disable auto-zoom to set custom map center
		$params['zoom'] = 2;									// Default zoom
		$params['latitude'] = 48.858372;						// Default latitude
		$params['longitude'] = 2.294481;						// Default longitude
	}

	return $params;
}
add_filter( 'geodir_map_params', 'gd_snippet_map_params', 11, 2 );`
