### ISSUE TITLE
Request: Logo Custom Field

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#239]
A predefined field for the logo that has an option to be displayed in the map bubble, in which case it would override the featured image.

Many customers have wanted to use logos. 

Related topics
https://wpgeodirectory.com/support/topic/replace-company-logo-with-featured-image-lets-get-over-it/

**Comment by Stiofan** [comment]
Logo predefined field added, post_images shortcode/widget now has option to show logo as first image - ADDED
