### ISSUE TITLE
Request: Location pages for postalcodes

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#240]
Users in UK and AU often want to search by postalcode.

It would be great if postalcodes also received location pages.

Related Topics:
https://wpgeodirectory.com/support/topic/some-au-postcodes-not-returning-results/

**Comment by Stiofan** [comment]
users can search by post code, adding them as a location extension i think is a bit much, they in most cases represent a very small area, a user could user neighborhoods if they wanted
