### ISSUE TITLE
Request: Disable auto-draft in favor of "Are you sure..."?

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#241]
The notifications from auto-draft can be confusing for users.

A member has recommended, instead, that there be an option to disable the auto-save of the draft, perhaps.

Also, the JS alert that says "change MAY not be saved" would be the expected "Leave without saving?" 

Related topics:
https://wpgeodirectory.com/support/topic/we-found-a-post/#post-425219

**Comment by Stiofan** [comment]
Its not possible to disable the auto draft, its not possible to disable it fully in WP either.
They will automatically deleted after 7 days.
