### ISSUE TITLE
Improve UI of select custom field options input

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2417]
its easy to mess this up with a stray comma or slash, lets think and discuss of a better UI for this.

**Comment by kprajapatii** [comment]
Right now comma(,) & slash(/) are reserved characters for us in options. Slash used to separate label & value while comma used to separate each option.

But we can replace current options input by replacing it with better UI via pop.
- Use repeater row with two input texts for label & value.
- Allow to set OPTGROUP

I think store in JSON format would be better to store in CF db.

Example
`[{"optgroup":"start","label":"My Opt Group"},{"label":"Option 1","value":"Value 1"},{"label":"Option 2","value":"Value 2"},{"optgroup":"end"},{"label":"Option 3"}]`

**Comment by Stiofan** [comment]
We need options at the top to enable labels, and a nice way to show optgroup.

Proceed with this when u get a chance.

**Comment by kprajapatii** [comment]
FINAL UI:
- Use textarea to add multiple options
- Each option added with new line
- Option format: 
   - LABEL
   - VALUE : LABEL
   
   - optgroup : LABEL
   - optgroup_close

   Examples:
**WITH OPTGROUP**
   ```
optgroup : Automobile
   car : CAR
   bus : Bus
   optgroup_close
   optgroup : Electronics
   TV
   Air Conditioner
   Refrigerator
   optgroup_close
```

 **WITHOUT OPTGROUP**
```
   car : CAR
   bus : Bus
   TV
   Air Conditioner
   Refrigerator
```

===
Tool to search & update value in DB
- Tool name "Search & Replace Custom Field Value"
- Tool UI will have 4 inputs
- Select Post Type, Select Field Key, Old Value & New Value
- On submit tool it will search and replace matching rows.
