### ISSUE TITLE
UX - Hard/Impossible to 'get to' default location?

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#242]
When I move the pin I get the error about the location must be in the default location.
But then I have to click 3, 9, or 11 times to clear the error.
When that is done, then I am still looking at a map and don't even know where the default location might be.
There is no city input field, so, I cannot write in the name of the city and "set on Map".

![image](https://user-images.githubusercontent.com/114659/38430980-23e78268-39c3-11e8-99c1-c3424ec20120.png)

**Comment by Stiofan** [comment]
made a change to prevent many popups
