### ISSUE TITLE
"Get Directions" tooltip is showing twitter tooltip

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#245]
![directions-tooltip](https://user-images.githubusercontent.com/114659/38432017-6a3e5e0a-39c6-11e8-8f88-d22a4ddeb558.png)

related topic
https://wpgeodirectory.com/support/topic/get-directions-3/#post-425309

**Comment by Stiofan** [comment]
Get directions has now been moved to a widget/shortcode instead of a custom field
