### ISSUE TITLE
Search page template is not working with beaver builder

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2473]
The Search page created using the Beaver Builder shows an empty page
https://wordpress-492495-4046703.cloudwaysapps.com/search/?geodir_search=1&stype=gd_place&s

also creating a search page template using Beaver builder themer is not possible. 
even if I create a template using BB themer it display nothing.
https://wordpress-492495-4046703.cloudwaysapps.com/wp-admin/edit.php?post_type=fl-theme-layout

**Comment by kprajapatii** [comment]
GD Search page needs setup little different then normal GD Archive pages.  I setup GD Search https://wordpress-492495-4046703.cloudwaysapps.com/search/?geodir_search=1&stype=gd_place&s=restaurant&snear=&sgeo_lat=&sgeo_lon=
