### ISSUE TITLE
Bricks Builder Integration

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#2476]
Allow to get the listing custom fields values with Bricks Builder elements.

https://secure.helpscout.net/conversation/2423272621/49095?folderId=3812066#thread-7261438501

**Comment by pol76** [comment]
@stiofan as I mentioned before, this should be a very high priority of ours. Let's not wait months to implement it please.

**Comment by pol76** [comment]
![image](https://github.com/AyeCode/geodirectory/assets/25163253/93341faf-a2c9-47d5-88bc-68e75fbde7b2)

**Comment by kprajapatii** [comment]
https://github.com/AyeCode/geodirectory/commit/b1e1e2e4af82de8f2878579ff4ca754147476e73
