### ISSUE TITLE
Multi-select checkbox field styling

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#248]
Multiselect field is out of form alignment in some themes (agency pro?)
unable to reproduce
![select-align1](https://user-images.githubusercontent.com/114659/38458071-b2c2bd28-3a99-11e8-8648-8d336608fe7a.png)
![select-align2](https://user-images.githubusercontent.com/114659/38458072-b2da8a84-3a99-11e8-9f79-ab3f2e1ab7e4.png)

in 2016 the field shows with some list item bullets:
![image](https://user-images.githubusercontent.com/114659/38458095-2afd6978-3a9a-11e8-8587-cba9302b72d6.png)
same list item bullets visible in 2017
![image](https://user-images.githubusercontent.com/114659/38458105-4f55a6aa-3a9a-11e8-8669-0a7f3654af52.png)

Related topic
https://wpgeodirectory.com/support/topic/alignment/#post-425381

**Comment by Stiofan** [comment]
added more specific css
