### ISSUE TITLE
Elementor Archive posts block -  infinite scrolling pagination option is not working

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2508]
<img width="1107" alt="Screenshot 2023-12-20 at 8 22 59 PM" src="https://github.com/AyeCode/geodirectory/assets/24760592/cdfe848d-0bcb-488e-8476-3a329e76785d">

**Comment by kprajapatii** [comment]
Elementor Archive Posts block "Load on Click" and "Infinite Scroll" don't supported with custom skin. It only works with default skins like Classic, Cards & Full Content.

See https://wordpress.org/support/topic/plugin-breaks-elementor-load-on-click-and-infinite-scroll/ & https://github.com/dudaster/ele-custom-skin/issues/790

**Comment by hedali1997** [comment]
Before installation, use Load on Click, but after installation, Load on Click becomes invalid
Custom js:
```js
    if (jQuery(".e-load-more-anchor").length > 0) {
      	const mainListDom = jQuery(".e-load-more-anchor").parent().parent();
        let pageDataSettingJson = mainListDom.attr('data-settings');
        let pageDataSetting = JSON.parse(pageDataSettingJson);
        if (!pageDataSetting['pagination_type']) {
            pageDataSetting['pagination_type'] = 'load_more_on_click';
        }
        mainListDom.attr('data-settings', JSON.stringify(pageDataSetting));
    }
```
Maybe it can help you
