### ISSUE TITLE
Latest Elementor pro + GD cause warrnings

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2510]
![Screenshot 2023-12-29 at 09 24 26](https://github.com/AyeCode/geodirectory/assets/24760592/fd1e9190-7170-4685-ae9a-3e2ea1f3cd29)

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2458274955/50155/
https://secure.helpscout.net/conversation/2463704244/50291?folderId=3812058

**Comment by kprajapatii** [comment]
I can'r reproduce error on our test site at https://ppldb.com/v2/restaurants/. Provide steps to reproduce issue.

@1naveengiri
