### ISSUE TITLE
Search page template is not working for the Bricks Builder layout

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2524]
Issue can be seen here https://wordpress-492495-4127525.cloudwaysapps.com/

**Comment by kprajapatii** [comment]
Bricks template needs to set conditions to show on individual page.

![bricks-search-page](https://github.com/AyeCode/geodirectory/assets/7394489/67cf22ec-0285-4a94-83eb-49966bf81041)
