### ISSUE TITLE
Media settings in Wizard

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#254]
Add media settings check to wizard as part of "Settings Report" to inform new users of required settings.

![image](https://user-images.githubusercontent.com/114659/38558243-c9ff2b06-3ccf-11e8-8cfc-3f6a2947923b.png)

This has been added to getting started overview doc: https://wpgeodirectory.com/docs-v2/geodirectory/getting-started/#settings

**Comment by Stiofan** [comment]
this is no longer a required setting, just a recommended one.

**Comment by alexrollin** [comment]
Awesome!

**Comment by alexrollin** [comment]
Will image import (with listings) now require the path, then?
