### ISSUE TITLE
GD > Post images Masonry gallery not working with BS5

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2547]
I'm not sure if we have it in our BS5 package, check if there is an easy way to add this.

**Comment by kprajapatii** [comment]
In BootStrap v4 masonry was adjusted with CSS.
In BootStrap v5 masonry is not included and it required separate masonry library to load. See https://getbootstrap.com/docs/5.3/components/card/#masonry

Should we load library or remove masonry for BS5?

@Stiofan

**Comment by Stiofan** [comment]
@kprajapatii looks like its just a single JS file, lets add it to AUI and then add a function to enqueue it in AUI, then call it from the GD post images block only when masonory is set?

**Comment by Stiofan** [comment]
This does not look right on my localhost
![Screenshot from 2024-03-15 15-37-19](https://github.com/AyeCode/geodirectory/assets/10433311/1b366ebc-ee99-463b-8100-7cefe0c2e97f)

**Comment by kprajapatii** [comment]
I setup at ppldb.com/v2 site and it is working fine.

Examples:
https://ppldb.com/v2/restaurants/united-states/new-york/new-york-1/maya-inn/?#masonry
https://ppldb.com/v2/masonry-gallery/

FYI: Masonry gallery changes will be released in next v2.3.45
