### ISSUE TITLE
GD > Categories block no category filter setting is not working

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2569]
when **Tick to show all the categories. Leave unticked to show only child categories of the current viewing category.** this setting is enabled. the block is not loading sub categories of the current category.

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2564461386/54162/

**Comment by kprajapatii** [comment]
Can you reproduce it at https://ppldb.com/v2?

@1naveengiri
