### ISSUE TITLE
GD Dashboard - Suggested features

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#257]
You already made a survey about additional features for the V2 dashboard, but I don't see any improvements here. I like to refer to the post:
https://wpgeodirectory.com/support/topic/gd-dashboard-what-data-would-you-like-to-see/

**Comment by Stiofan** [comment]
Some thins will be added by addons.  If you have a suggestions feel free to add it.

**Comment by DirkJahn** [comment]
? this was not the idea to just say "invalid" and "close" it. There are already a lot of suggestions in the topic of the forum and your team never answered to any of the suggestions. This is not really motivating to people who read it, think about it and then participate.

**Comment by Stiofan** [comment]
That will be looked at more in future but if it is to be added here i would prefer them to be individual issues not a general issue.

**Comment by DirkJahn** [comment]
Your team asked for it, so it is up to you to add it here!
