### ISSUE TITLE
Multi Selection field - Groups not working

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#259]
You can select, but you cannot publish

![pic97](https://user-images.githubusercontent.com/35274187/38616099-234cfb70-3d93-11e8-96ba-43d8039f3c8d.png)

![pic98](https://user-images.githubusercontent.com/35274187/38616112-288c53ec-3d93-11e8-8f65-b0a37e165dc2.png)

**Comment by Stiofan** [comment]
Seems to work fine for me?

**Comment by Stiofan** [comment]
unrelated problem but on next release resave the field setting and then it will work.
