### ISSUE TITLE
Condition set for a fielset should get applies to all the fields inside it

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2594]
https://secure.helpscout.net/conversation/2597862703/56038?folderId=3812058

**Comment by kprajapatii** [comment]
Each field ha own conditional field setup. So it does no make sense to apply for entire fieldset.

**Comment by 1naveengiri** [comment]
another request 
https://support.ayecode.io/conversation/1364?folder_id=115

Customers use a fieldset for grouping fields together. They find it annoying to set the same condition for each field inside. 
when they think they easily hide/show the entire fieldset at once.

**Comment by DragNfLy** [comment]
Implementing a nested fieldset architecture will be a great UX and UI improvement to GeoDirectory. Setting conditions on 100's of child fields of a fieldset is super annoying. Please consider this improvement.

**Comment by DragNfLy** [comment]
> Each field ha own conditional field setup. So it does no make sense to apply for entire fieldset.

Fieldset should also have 'Css class' option please.

**Comment by DragNfLy** [comment]
Instead of updating the current fieldset; - GD dev's could consider create an additional 'Nested FieldSet' field which would allow for this.
