### ISSUE TITLE
Hamburger menu not working on Directory Starter theme

### ISSUE THREAD

**Issue by nicolaslimet** [AyeCode/geodirectory#2599]
ticket: https://secure.helpscout.net/conversation/2609042112/56531/

The same is happening on my dev site https://ppldb.com/nick/ (the dev site has only Supreme + Starter themes and geo plugins)

No console warning that are relevant

**Comment by kprajapatii** [comment]
Moved to https://github.com/AyeCode/directory-starter/issues/19
