### ISSUE TITLE
UX - Error is saving non-unique GD Pages

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#260]
Saving a page for more than one setting should throw an error and disallow save:

![image](https://user-images.githubusercontent.com/114659/38623855-ff70685e-3da6-11e8-9788-bbfa3bd58168.png)

Same for the templates:
![image](https://user-images.githubusercontent.com/114659/38623943-33402822-3da7-11e8-87cc-267ccedd28c4.png)

Related topic
https://wpgeodirectory.com/support/topic/http-https/#post-425988

**Comment by Stiofan** [comment]
FIXED
