### ISSUE TITLE
Video iframe not working in GD > Post Images in BS styles

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2622]
We have a feature documented here: https://docs.wpgeodirectory.com/article/67-gd-post-images
You can add a video to show in lightbox iframe, its not working on BS5, only BS4. Ping me if you need further explanation. seems to be an issue in geodir_lightbox_embed() JS function.

**Comment by Stiofan** [comment]
https://wordpress.org/support/topic/local-video-gallery/

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/wp-ayecode-ui/pull/83/commits/f1b4956ea16fe675ae449cfa5df7459b48135ca8

**Comment by Stiofan** [comment]
Further points:

1. when loaded in slider it will continue to play even when not the selected frame.  It should blank the iframe URL when no active so you can have multiple videos and they don't continue to play when not active
2. Add support for file uploads, for example a video uploaded file, currently the screenshot and the lightbox are broken as it outputs the |118||| ID and title/desc tot he URLs.
