### ISSUE TITLE
Conditional field data should get clear when field does not meet the given condition

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2625]
The challenge is that when a user changes the category in the "Add listing" form, the conditional fields from the previous category still retain their data, leading to inappropriate fields being displayed on the front end.

https://secure.helpscout.net/conversation/2639095962/57706?folderId=3812058

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/wp-ayecode-ui/pull/89/commits/0d4d9a7733f56b0fee555aeea2e2e9bc3117ff7d
