### ISSUE TITLE
Elementor - do we use their waypoints.js

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2627]
_I wanted to let you know that we found that your plugin GeoDirectory is currently calling Elementor’s waypoints.js file, which will soon be deleted in an upcoming release (v3.24) scheduled for a beta release on August 19.
We will be replacing waypoints.js with the native Intersection Observer API, thereby reducing the reliance on external libraries and decreasing the number of JS assets loaded on the page (saving 18kb). Your addon will also benefit from this improvement.
We kindly ask you to update your plugin’s code to use ‘IntersectionObserver()’ or include waypoints.js files in your addon to avoid any issues on our shared users’ websites._

Check if we use this files functionality (I don't think so but please confirm)

**Comment by kprajapatii** [comment]
We don't use Elementor's waypoints.js file or functionality from the file.

**Comment by Stiofan** [comment]
Thanks for confirming
