### ISSUE TITLE
WP oEmbed custom field

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#263]
Allow users to specify unlimited oEmbed custom fields that use wp oEmbed

Members regularly request a second video field.

https://make.wordpress.org/support/user-manual/content/media/adding-media-to-your-pages-and-posts/embedding-media-from-other-sites/

## Related Topics
https://wpgeodirectory.com/support/topic/multiple-videos-2/#post-426578

**Comment by Stiofan** [comment]
this should work in the next release if you add each video url for example on a new line.
