### ISSUE TITLE
Dyanmic content - post author

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#2630]
Please add options for "post_author" and maybe one for "admin_only"  let me know if you can think of anything else?

**Comment by kprajapatii** [comment]
Added filter keys:
- logged_in (Logged In)
- logged_out (Logged Out)
- user_roles (Specific User Roles) - Comma separated user roles & with condition **is_contains** or **is_not_contains**.
- post_author (Post Author)  - Use current_user to match with current logged in user
