### ISSUE TITLE
Make GD widgets compatible with Elementor element caching

### ISSUE THREAD

**Issue by nicolaslimet** [AyeCode/geodirectory#2648]
Client suggests that GD widgets/elements that cannot be cached (dynamic) disable the caching feature at widget/element level.

Users must currently disable the feature globally, losing performance improvements on widgets that could be cached.

https://secure.helpscout.net/conversation/2667713214/58821?folderId=3803506

**Comment by kprajapatii** [comment]
Checked on local site and it seems Elementor already prevent caching on element that contents dynamic tags.
