### ISSUE TITLE
Custom Field "File Upload" not working with app-Files

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#266]
Tested it with JPGs -> working
Tested it with Excel (xlsx) -> not working

![pic104](https://user-images.githubusercontent.com/35274187/38766015-f0d3a69a-3fcb-11e8-9f3f-59aca5c752d9.png)

**Comment by Stiofan** [comment]
In the custom field you need to select the types, did u select .xls?  I tested and its working, though i have made many changes to the file upload so it might be resolved due to that. 
if you have any problems after next release just let me know and i'll re-open this.
