### ISSUE TITLE
Titles & Meta 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#267]
New template variable %%category_description%%  for use in:

**GD - Titles & Meta > Listing page meta > Listing page meta description**

This variable would substitute the text description from a GD CPT Category - > Description (not Top Description)

## Related Topic
https://wpgeodirectory.com/support/topic/hide-category-description/#post-426593

## Reference
https://kb.yoast.com/kb/yoast-wordpress-seo-titles-metas-template-variables/#custom-variables

**Comment by Stiofan** [comment]
looks like u meant to post this in v1?

**Comment by alexrollin** [comment]
no, it is for V2, for consideration
