### ISSUE TITLE
Avada toggle is not working with Ayecode UI V5

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2682]
https://secure.helpscout.net/conversation/2708598805/60470?folderId=3812058
https://secure.helpscout.net/conversation/2692177007/59811/

**Comment by 1naveengiri** [comment]
Switching it to v4 works

**Comment by kprajapatii** [comment]
Avada Fusion Builder is using BootStrap v4 so some features will not work with BootStrap v5. In this case switching AyeCode UI > BootStrap v4 is only solution.
