### ISSUE TITLE
prevent PHP warnings using in_array

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#269]
I see a lot of warnings with the V2 beta concerning in_array call.

![pic106](https://user-images.githubusercontent.com/35274187/38795945-2f25fa9e-415a-11e8-9966-e9da0c3140d9.png)

If you are searching for a string "needle" within a string "heystack" the correct call will be `strpos`.

**Comment by Stiofan** [comment]
this was a unserialise issue, now fixed
