### ISSUE TITLE
Sorting options not working without showing

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#270]
#215 still not working.

What I do and what I expect:
I want to have the list of places sorted by featured, but this as default, without the user to be able to change. When I'm adding the "Featured?" to the sorting options I'm getting this:

![pic107](https://user-images.githubusercontent.com/35274187/38796809-d522d190-415c-11e8-938d-58cb7b02d081.png)

Activate this option and my expectation is that I'm done and the list is sorted by "featured". But this is not what V2 is doing. The ASC and DESC is not set at this moment -> that is a bug. One should be set and not hidden by the presentation option, as this has nothing to do with showing this option!

![pic108](https://user-images.githubusercontent.com/35274187/38796921-322aac46-415d-11e8-995a-5c09c0fb59e2.png)

**Comment by Stiofan** [comment]
you need to activate the Descending sort and add a title, it will then be avaiable in the sorting options.
The current "featured" sorting option has been removed.
