### ISSUE TITLE
Custom field "Get Direction Link"

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#271]
This predefined custom field has some issues:
1) Wrong type! It is of type "price"
![pic109](https://user-images.githubusercontent.com/35274187/38797634-6a4b777a-415f-11e8-87fe-877dd9387d7a.png)

2) totally unclear what is this for. My thought was that I'm getting a "Get Direction Link" from the Map. But this is not what I got. Documentation????

**Comment by Stiofan** [comment]
This has been removed and replaced with a widget/shortcode.
It simply gives an external link to get directions from the post's GPS, its specially designed to work on mobile, it will open correctly in IOS and Android and also PC.
