### ISSUE TITLE
GD Dashboard - UX

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#272]
Different concept for "Pending Listings" and "Pending Reviews"????

Is confusing me how "pending listings" and "pending reviews" look like....

![pic110](https://user-images.githubusercontent.com/35274187/38808210-9ccb9174-417f-11e8-938f-9a283776a11c.png)

**Comment by Stiofan** [comment]
Do you mean the "See all" or something more?

**Comment by DirkJahn** [comment]
Left is the number clickable, on the right not... this is what I mean with UX

**Comment by DirkJahn** [comment]
on the right you have "see all" on the left not

**Comment by Stiofan** [comment]
This is due to the face there can't be a view all for all CPTs, so the CTP is clickable, where as with the reviews they are in the once place.
