### ISSUE TITLE
Add place - frontend - tags

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#273]
I would assume here that it will get the already existing tags, but it does not...

![pic111](https://user-images.githubusercontent.com/35274187/38808721-7576a13e-4181-11e8-8296-dfa9dc5e9204.png)

**Comment by Stiofan** [comment]
This was already implemented but a bug made it only show if the listing already had tags, this is fixed and will be in the next release.
FYI it shows the 10 most popular tags.
