### ISSUE TITLE
Tool to edit address format

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#276]
I'm not sure if you didn't think about it, or if I can't find it in V2, but we should give a tool to users to change the address format easily.

That's one of the most frequent support request because each country has its own format and the snippet we provided has been used by countless users.

Something with tags would be more than enough, example:

%street-name% %street-number%
%city% %region%
%zipcode% %country%

(not sure I'm missing any element of the address, but I think that should be it)

Giving the option to easily break lines.

Let me know what you think.

Cheers!

**Comment by alexrollin** [comment]
+1

{neighborhood}, too

**Comment by Stiofan** [comment]
There are a few ways to tackle this:
1. Make an "Address" widget that will let you do this.
2. add a custom field input to set it, but this would limit it to the one format all over.
3. Simply add a filter to alter it.

I think number 1 is best even if it means adding a new widget.

Thoughts?

**Comment by alexrollin** [comment]
My own sense is that members would like to have control of the address display for each different template: detail, archive, map, and archive item.

The tool for the address could allow the members to:
adjust element spacing
separators
line breaks

My reach enhancement request would be to consider how members might link each address element:
City linked to city location page, neighborhood linked to neighborhood location page etc.

**Comment by Stiofan** [comment]
I have added an option in the country table to be able to have this per country.
(note we only store "street" not "%street-name% %street-number%" as original post)

**Comment by alexrollin** [comment]
A member has requested this.

After using v2, would it not make sense to simply allow GD Post Meta to get the individual parts?

Topic
https://wpgeodirectory.com/support/topic/change-address-format-2/#post-453692

**Comment by Stiofan** [comment]
Thats not soemthing for post meta, if anything it would be a new widget, there is a filter that can be used just now: https://wpgeodirectory.com/support/topic/change-address-format-2/#post-453834
