### ISSUE TITLE
UX - Contact form user experience

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#278]
The contact form on mobile is squished into a small viewing window making it hard to see more than one field at a time.
When the keyboard appears, the visible portion still has black bars above and beneath making to 'seem' like more 'could' be visible.

Plusses
+ Works!
+ Nice and big and easy to read
+ Tabs work well on mobile allowing advance to the next field easily

Minuses
- Black space on bottom seems 'unoptimized'
- Black space on top seems uniformative

![screenshot_20180421-104533](https://user-images.githubusercontent.com/114659/39082344-e6543262-4551-11e8-8153-3f04cb59637a.png)

**Comment by Stiofan** [comment]
fixed and will be in next release
