### ISSUE TITLE
Sub-page form display

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#279]
Allow a form like a contact form (integration) to be shown on a listing subpage.
Example mysite.com/places/restaurants/morimoto/contact-us/

Render in tab is great! And does already have a permalink. However, the main issue is that the page display is not focused on the form.
The popup is great also, but the UX for the form is highly impacted by the display in the popup.

A full page subpage display puts the focus on the form, and UX for the form.

The subpage could work as a GD Template so the site manager can make an intro message like:

```
Template for contact form:
Thank you for your interest in [gd_post_meta key="post_title" show="value"]!
Use this form to contact [gd_post_meta key="post_title" show="value"]. Please fill out all the fields completely.
[ninja_form id=3]
```
It is less common for sites to try to squish a contact form into a popup, and more common to put the form on a different page. A subpage makes sense and allows direct linking, too.

Most importantly the form can fill a page and the site manager can have control of the page just like other templates.

**Comment by Stiofan** [comment]
the sub page idea is a bad idea...
The popup UI i will be looking at soon.
It works in a tab just now and will jump to that place then linked to.
