### ISSUE TITLE
sd_insert_shortcode not working

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#280]
Uncaught ReferenceError: sd_insert_shortcode is not defined
    at HTMLButtonElement.onclick (post.php?post=10&action=edit:362)
onclick @ post.php?post=10&action=edit:362

Open backend editor on template
Open GD shortcode editor
Configure post meta title value only
click insert shortcode - nothing
click copy shortcode - popup shows confirm, but nothing is added to clipboard.

**Comment by Stiofan** [comment]
Yeah this was on our v2 demo only, its fixed now.
