### ISSUE TITLE
Rephrase Geodirectory taxonomies description text

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#284]
Menu Item  : Wordpress - Settings - Permalinks - GeoDirectory Taxonomies

Help description text says:

> If you like, you may enter custom structures for your category and tag URLs here. For example, using topics as your category base would make your category links like https://...v2/places/topics/attractions/. Tags can not be blank, category slug can only be blank if the main structure has more than one tag used.

Perhaps?
If you like, you may enter custom structures for your category and tag URLs here. For example, using topics as your category base would make your category links like https://...v2/places/topics/attractions/. **Tag base** can not be blank **. Category base** can only be blank if the **Geodirectory permalinks (above) are using more than one of the available tags.**

![image](https://user-images.githubusercontent.com/114659/39252192-6744d984-48a5-11e8-89f0-c11c5a7cd151.png)

**Comment by Stiofan** [comment]
I have changed this slightly, i did not like the idea of bold though, there is error checking for this, that should be enough.
