### ISSUE TITLE
Leave a reply text link inactive

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#288]
Should this point to #review?
https://ppldb.com/kiran/gdv2/events/united-states/ohio/circleville/culinary-tasting-session/#respond

![image](https://user-images.githubusercontent.com/114659/39370767-0cbea0ca-4a40-11e8-8ae9-a331e8b0fced.png)

**Comment by Stiofan** [comment]
some themes auto add things to different page templates, in this case 2012 adds that link, we can manaually set what template is used, setting it to page.php removes this: https://ppldb.com/kiran/gdv2/wp-admin/admin.php?page=gd-settings&tab=design&section=details
