### ISSUE TITLE
CSV and handling commas in categories

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#290]
Make sure CSV import and export are handling commas correctly.

Please see:

https://wpgeodirectory.com/support/topic/deletion-of-category/#post-428295

**Comment by Stiofan** [comment]
In v2 we use IDs as we are doing it the stardard WP way which uses wp_set_post_terms() which states:

> If you want to enter terms of a hierarchical taxonomy like categories, then use IDs. If you want to add non-hierarchical terms like tags, then use names.
