### ISSUE TITLE
Not respecting read more tag

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#291]
listings does not respect the read more tag `<!--more-->`

In the listings pages I would cut the excerps at the read more tag as this is standard function of WP.

**Comment by Stiofan** [comment]
Many years ago we used to use this but it left the listings pages looking a mess, its far better if we impose the read more for all. Closing for now but feel free to comment if you have a response.

**Comment by DirkJahn** [comment]
I don't know why you then keep it inside the menu if you never will support it.

![pic9](https://user-images.githubusercontent.com/35274187/39663791-e646aa1a-5079-11e8-9500-e697be109ba1.png)

For a UX view of point these functions have to be disabled.

**Comment by DirkJahn** [comment]
And why should it looking a mess? It will not be displayed to the frontend and the user has the oportunity to use it or not. If you have very long descriptions **this** will look **weird** on the listings pages. Especially on mobile view it might not be good to scroll to the end.
Also you don't have a chance to go back. Clicking on the "read more" is a oneway street.

**Comment by Stiofan** [comment]
Thats just part of the editor, there are many plugins that don't use the read more functionality but don't remove the button...

**Comment by DirkJahn** [comment]
So you are comparing you with all the bad guys not thinking on UI/UX?

**Comment by Stiofan** [comment]
WooCommerce do the same...
