### ISSUE TITLE
Feature Request: Allow HTML at pic title

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#293]
It is possible that you like to have something strong within the title or to have a href here. At the moment you are stripping tags.

**Comment by Stiofan** [comment]
This is setting the image title and alt tags, these can't have HTML in them.

**Comment by DirkJahn** [comment]
Why not? Nearly most of the available plugins can have HTML tags inside the title.

**Comment by DirkJahn** [comment]
I'm talking about this one and this has nothing to do with the `<img title="bla">` parameter!

![pic5](https://user-images.githubusercontent.com/35274187/39428719-bebf2f34-4c88-11e8-958f-912b9b88f76e.png)

**Comment by DirkJahn** [comment]
You can strip the html code from the <img title=""> but I like to have it still here!
