### ISSUE TITLE
file upload limit applied globally

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#298]
logo has max 1 file upload (first in form)
menu has max 3 file upload (and is later down in the form)

Using the frontend editor, if you add 3 files to menu first, you can go back to logo and upload 3 more.

In the backend max 3 files for the whole listing.

https://ppldb.com/v2/places/pastry-place-2/

![image](https://user-images.githubusercontent.com/114659/39472149-b7ba8f5c-4d47-11e8-881f-abdad44ad51c.png)
the limit is applied in the backend edit form, but only globally, too many images does not show error (probably for the best)
![image](https://user-images.githubusercontent.com/114659/39472323-e713446e-4d48-11e8-855a-70255e9dc08d.png)

![image](https://user-images.githubusercontent.com/114659/39472364-19e4c354-4d49-11e8-927c-5327d5ed888b.png)

![image](https://user-images.githubusercontent.com/114659/39472129-a547213c-4d47-11e8-9d6d-4790678f859d.png)

**Comment by Stiofan** [comment]
nice spot, i have fixed this and uploaded to demo
