### ISSUE TITLE
GD Listing shortcode []

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#305]
add gd listings shortcode select all categories and get []
`
[gd_listings title="GD LISTINGS SHORTCODE" post_type="gd_place" category[]="0" sort_by="az" title_tag="h3" layout="gridview_onehalf" post_limit="5" add_location_filter="1"]`

![image](https://user-images.githubusercontent.com/114659/39587654-5093404e-4efa-11e8-9caf-c4969c4df3f0.png)

## Related Topic
https://wpgeodirectory.com/support/topic/here-some-bugs/

**Comment by Stiofan** [comment]
fixed and will be in next release
