### ISSUE TITLE
Change "CPT Settings" Tab to "CPT Options"

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#306]
We are getting some menu recursion-ish feelings with specificying

Navigate to 
**CPT - Settings - CPT Settings (tab)**

How about

Navigate to 
**CPT - Settings - CPT Options**

**Comment by Stiofan** [comment]
@pol76 Maybe we should just simplfy things here:
Custom fields | Sorting | Tabs | Options
Or maybe the last one could just be "General"?

**Comment by pol76** [comment]
Custom fields | Sorting | Tabs | Options or General sounds good to be!
