### ISSUE TITLE
Hierarchical Tab defintion?

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#307]
It is possible to define a one level hierarchical tab, but this tab is not showing up (not in the first and also not in the second level).

![pic6](https://user-images.githubusercontent.com/35274187/39606060-b776c504-4f33-11e8-8794-ad023c2f902a.png)

![pic7](https://user-images.githubusercontent.com/35274187/39606099-de5cabe8-4f33-11e8-8440-bb73b5728c1e.png)

**Comment by Stiofan** [comment]
This was a bug, now fixed and will be in next release.
Thanks!
