### ISSUE TITLE
YOAST SEO - meta information

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#317]
Wrong meta information (og:description and twitter:description) with YOAST SEO. 

What I can see the only wrong one is the description (without defining a template in YOAST SEO). 
Without the template it is generating something out of Category, Tag, etc. information of the place.

Defining "%%excerpt%%" in the template of YOAST SEO I'm getting "Test" with all places. (Here I'm not sure if there is something in the installation). But anyhow, it should be generated out of the place description with the "%%excerpt%%".

**Comment by Stiofan** [comment]
fixed
