### ISSUE TITLE
YOAST SEO - Sitemap

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#318]
There is a difference in the sitemap generation with YOAST SEO between V1 and V2. In V2 I have in the place sitemap now the base link "/places" (Archive Page). In V1 this is not generated.

I would here suggest not to have the base "/places" link inside the sitemap for the places as this is an listings page (archive) and keep just all the individual pages here.

**Comment by Stiofan** [comment]
I see both with the /places listed in v1 and v2.

I prefer to have it listed here, it is the same as posts, it lists the listing (archive) of the posts first, and if it was not here then where else would it be...

**Comment by DirkJahn** [comment]
Sorry, I was not precise enough. I tested agains a V1 with location manager installed.

It is not correct that the archive page is generated to the sitemap all the time. This depends on your permalink structure. For example if you have in custom structure "/%category%/%postname%" The archive pages of the categories are not generated to the posts. Maybe this might be a bug or not, but I don't care here. BTW what is generated does not make sense for me here, but is not part of the discussion.

In GD (v1/v2) with the location manager you are not creating the archives (and you might have millions in all combinations) to the sitemap (This is why I wrote that there is a difference. Was not aware that you handle/iterate different with or without location manager). But without location manager you are create one. 
For me then there is already an issue in GD v1 with creating the sitemap.

**Comment by Stiofan** [comment]
I think the site map is the way i want it for core. i'll go over things again with location manager nearer the time.

**Comment by DirkJahn** [comment]
Good. For your information: I'm okay with the core and with what I have in location manager now. I just see a difference. I will rise this again when we have the location manager.

**Comment by Stiofan** [comment]
thanks Dirk
