### ISSUE TITLE
WPML - Locations not working

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#319]
With WPML the location of the translated places cannot be found, so the map shows "No records found" on details, listings and I guess all pages.

BTW: On the details page the sidebar map in such a case is loading the map in background, on the tabs it is not...

![pic17](https://user-images.githubusercontent.com/35274187/39954939-5759449e-55c8-11e8-96e4-ea0f61958ed1.png)
![pic18](https://user-images.githubusercontent.com/35274187/39954940-5a668494-55c8-11e8-9bb3-d93108f9f222.png)

**Comment by DirkJahn** [comment]
This was tested with translation option "Translatable - use translation if available or fallback to default language" and nothing else (beside two translated taxonomies).

**Comment by Stiofan** [comment]
multilingual functions have been moved to its own addon, this will work with the next release (v2.0.0.14) and any bugs should then be reported there: https://github.com/AyeCode/geodir-multilingual
