### ISSUE TITLE
WPML - Override with original language content not working

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#320]
If I create a translation of a place and click on override with the original language content it is not copying the content to the translation.
All GD specific information are kept empty, the WP standard fields are filled in with the original content correctly.

**Comment by Stiofan** [comment]
multilingual functions have been moved to its own addon, this will work with the next release (v2.0.0.14) and any bugs should then be reported there: https://github.com/AyeCode/geodir-multilingual
