### ISSUE TITLE
WPML - place slug translated too

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#321]
When I'm loading the GD translation (via WP update) the slugs are also translated and then I'm getting 404 errors for the places.

![pic19](https://user-images.githubusercontent.com/35274187/39955223-72b3c75c-55cb-11e8-994f-cb8440de16cd.png)

The "translated" slug:
![pic20](https://user-images.githubusercontent.com/35274187/39955224-74e03f92-55cb-11e8-8e3e-1688889d7bcc.png)

My settings:
![bild 21](https://user-images.githubusercontent.com/35274187/39955225-769cfece-55cb-11e8-937f-24736453e2a3.png)

**Comment by DirkJahn** [comment]
I think that this is not a WPML problem. I'm guessing this has something todo with the GD translation file.

**Comment by Stiofan** [comment]
multilingual functions have been moved to its own addon, this will work with the next release (v2.0.0.14) and any bugs should then be reported there: https://github.com/AyeCode/geodir-multilingual

**Comment by DirkJahn** [comment]
Have you tested this (you already mentioned you had a look on it)? This has nothing to do with WPML (multi-language). This is coming from the plugin translation file! And inserting/using the wrong slug.

**Comment by DirkJahn** [comment]
![pic31](https://user-images.githubusercontent.com/35274187/41173396-03aa3106-6b57-11e8-9b0d-bdf3344f4093.png)


![pic32](https://user-images.githubusercontent.com/35274187/41173401-08f21e8a-6b57-11e8-8be9-f8c0c36c9254.png)

**Comment by Stiofan** [comment]
i'll confirm before closing

**Comment by DirkJahn** [comment]
The last pics were from an installation without wpml

**Comment by DirkJahn** [comment]
This was my last test at all.

This issue is NOT solved. 

It will potential kill SEO for people using it in a different language installation.

**Comment by Stiofan** [comment]
Are u using GD 2.0.0.14?

**Comment by DirkJahn** [comment]
The setup:
![pic33](https://user-images.githubusercontent.com/35274187/41424432-4cc1dae6-6ffe-11e8-9456-67a343e9d951.png)

**Comment by DirkJahn** [comment]
And I don't know why you are referencing to WPML. I wrote twice that this is not a WPML issue.

**Comment by kprajapatii** [comment]
@DirkJahn

Are you using a WordPress standard translation via po file or using any third party translation addon?

I have translated places slug and checked (see attachments).

![gd-place-settings](https://user-images.githubusercontent.com/7394489/41452962-ac0e601c-7091-11e8-9dad-5f3fb4077a93.png)
![gd-detail-page](https://user-images.githubusercontent.com/7394489/41452961-abda1852-7091-11e8-987e-8e5c86576f23.png)

Can you provide us translated files?

Let us know.

Thanks,
Kiran

**Comment by DirkJahn** [comment]
If I'm installing on a german WP it is downloading the translation file automatically.

**Comment by kprajapatii** [comment]
The slug translation issue has been fixed. See https://github.com/AyeCode/geodirectory/pull/351/commits/03cba9dd9c411a397d00d32972713eea219a2a5b#diff-28260fdef0ed73b226b5d63c233a3ad8R334
