### ISSUE TITLE
shortcode wizard validation

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#323]
perhaps should check for shortcodes inside the shortcodes
`
[gd_categories title="GD Categories [gd_categories]" title_tag="h4" post_type="gd_place" cpt_ajax="1" sort_by="az" max_level="0" max_count="all"]
`
![image](https://user-images.githubusercontent.com/114659/39956503-f7287a6c-55e1-11e8-9ed0-541bdb2ae5d2.png)

**Comment by Stiofan** [comment]
there is no efficient way to distinguish between a shortcode and just some text in brackets and i don't think this will come up very often.
