### ISSUE TITLE
gd_listings  related_to="tags" tags=”Pastry” 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#325]
Cannot get related posts with tag Pastry to show
https://ppldb.com/v2/location/
https://ppldb.com/v2/places/tags/pastry/
`[gd_listings title="Recent Pastry Places" post_type="gd_place" related_to="tags" tags=”Pastry” sort_by="az" title_tag="h3" layout="gridview_onehalf" post_limit="2"]`
https://ppldb.com/v2/wp-admin/post.php?post=7&action=edit
![image](https://user-images.githubusercontent.com/114659/39956720-56f2f1d0-55e6-11e8-86c9-726b30f91068.png)

**Comment by Stiofan** [comment]
This is not how this feature works. 
This feature is if the gd_listings widget is used on the DETAILS page then you can make it filter listings that are related to the current listing, so if the current listing has tag "boat" then it will show listings that also have that tag.
