### ISSUE TITLE
Titles and Metas - Single Post Pages

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#326]
**All Tags for tetsing**
`MTITLEDESC-OUT  | title - %%title%% | sitename - %%sitename%% | sitedesc - %%sitedesc%% | excerpt - %%excerpt%% | sep - %%sep%%  | pt_single - %%pt_single%% | pt_plural - %%pt_plural%% | category - %%category%% | id - %%id%% | location - %%id%% | in_location - %%in_location%% | in_location_single - %%in_location_single%% | location_country - %%location_country%% | in_location_country - %%in_location_country%% | location_region - %%location_region%% | in_location_region - %%in_location_region%% | location_region - %%location_region%% | location_city - %%location_city%% | in_location_city - %%in_location_city`

Category -  not working - changed to `%tegory%%` on save
Location tags -  not working

**Comment by Stiofan** [comment]
This was a weird one, now fixed, thanks.
