### ISSUE TITLE
WPML - translating categories - All places

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#328]
if you translate a category the place is shown multiple times in the "All places" with a selected language.

![pic22](https://user-images.githubusercontent.com/35274187/40043132-dac16430-5823-11e8-9ef1-4b21154a9115.png)

**Comment by Stiofan** [comment]
multilingual functions have been moved to its own addon, this will work with the next release (v2.0.0.14) and any bugs should then be reported there: https://github.com/AyeCode/geodir-multilingual
