### ISSUE TITLE
Hierarchical Categories are lost in the select box

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#329]
On my live site I use hierarchical categories and it is absolutely needed to show this hierarchy to the users. In the select box all hierarchical information is lost. This will confuse the user to correctly select categories.

With GDv1 this was possible to decide by the users.

![pic23](https://user-images.githubusercontent.com/35274187/40043743-b65de60c-5825-11e8-8c06-eb58a5d2062f.png)
![pic24](https://user-images.githubusercontent.com/35274187/40043747-b885a7c6-5825-11e8-94f0-86ada4c6313d.png)

**Comment by Stiofan** [comment]
fixed
