### ISSUE TITLE
Exclude map load

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#331]
New GMaps Platform fees have caused a lot of concern.

One idea of a member was to stop Supreme maps from loading (at all) on certain pages (like the archive/Listing page) instead of just hiding them with CSS in order to control costs.

This might only be an issue with a theme like Supreme that removes some choice about template layout.

## Related Topics
https://wpgeodirectory.com/support/topic/remove-search-results-map-and-expand-view-for-listings-only/#post-430727

**Comment by Stiofan** [comment]
This will change in GDv2 as SD will need to be changed to work with it and it will be a case of switching a page template.
