### ISSUE TITLE
ER: GD Listings filtered by tags

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#332]
> **Enable GD Listings filtered by tags and categories**

tags – Filter by tags (default = unfiltered), for example tags=”Museum,Garden”. Note that this filter uses the name of the tag, not the ID or slug.

categories – Filter by categories (default = unfiltered), for example categories=”16,43”. Note that this filter uses the ID, not the name or slug.

> https://wpgeodirectory.com/support/topic/shortcodes-sorting/#post-425748

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/718/commits/eddb8f76842e6ee9679f5f43d6d48afdad70387e

**Comment by kprajapatii** [comment]
@alexrollin
