### ISSUE TITLE
WPML - Search page gone

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#334]
Just activating WPML and clicking on standard search page I'm getting a blanck screen with the standard language.

![pic25](https://user-images.githubusercontent.com/35274187/40195950-4d4fc7a2-5a0f-11e8-81d1-2d217d138038.png)

**Comment by Stiofan** [comment]
multilingual functions have been moved to its own addon, this will work with the next release (v2.0.0.14) and any bugs should then be reported there: https://github.com/AyeCode/geodir-multilingual

**Comment by DirkJahn** [comment]
My expectation is that all the reported issues are solved otherwise please copy these issues to the right repository by your own.

**Comment by Stiofan** [comment]
the issues have been looked at, i am closing them here, if NEW issues are found they should be reported in its own addon.
