### ISSUE TITLE
GD Map Filter by Tags

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#335]
> **Enable GD Map filtered by tags **

tags – Filter by tags (default = unfiltered), for example tags=”Museum,Garden”. Note that this filter uses the name of the tag, not the ID or slug.

**Comment by Stiofan** [comment]
@kprajapatii please add this like GD Listings and reply here once done:
https://wpgeodirectory.com/support/topic/multilocations-not-designed-to-understand-how-major-cities-work/#post-496302

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/846/commits/8209d0644eed9a508ecaa89960c4dec519d644a2
