### ISSUE TITLE
Selecting icon on Place settings

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#368]
Clicking on this:
![pic35](https://user-images.githubusercontent.com/35274187/42085982-2bc379fe-7b92-11e8-9b04-bbfef6aeed37.png)

is giving me this:
![pic36](https://user-images.githubusercontent.com/35274187/42086008-3663a47e-7b92-11e8-8ca2-9bb05c8042ba.png)

**Comment by Stiofan** [comment]
this is the desired output, its a lighbox to select the icon.  Its done this way for 2 reasons, 1. so we dont have to load a large select input several times on a page and 2 so it can be a text input and a user can easily select and icon also.
