### ISSUE TITLE
V1 -> v2 converter

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#387]
Some feedback:

1. Should flush re-write rules on completion.
2. GD page content missing, On install/update we should check the GD pages to see if they are empty and if so enter the default info from the defaults class.
3. the link to view the progress took me to the setup wizard, but maybe that was because it was complete?

**Comment by Stiofan** [comment]
1. I have fixed
2. seems fixed
3. Link now takes me nowhere,, should there be a UI?

**Comment by kprajapatii** [comment]
3) Clicking on link:
- If update is done then it will show message like "GeoDirectory data update complete. Thank you for updating to the latest version!" and also show link to run setup wizard.
- If update is not done then it show message like "Your database is being updated in the background..."

**Comment by kprajapatii** [comment]
4 - 7 updated
https://github.com/AyeCode/geodirectory/pull/390/commits/02dc90d30848b12fcbc6dd29b9faa77783741782 & 
https://github.com/AyeCode/geodir_location_manager-v2/pull/20/commits/931bab8a320ac22447232ed3a97d85a2c70823ff
