### ISSUE TITLE
Photos Tab Icon FA5 warning

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#391]
![screenshot 2018-07-24 at 8 30 32 pm](https://user-images.githubusercontent.com/114659/43158663-856cf80c-8f80-11e8-8601-a9e83361bb83.png)

https://ppldb.com/v2/places/united-states/new-york/new-york/restaurants/buddakan/#reviews

**Comment by Stiofan** [comment]
This is already fixed but old installs u need to set the icon again in the tab settings.
