### ISSUE TITLE
rc18 - disabling social importer also removes license key

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#393]
When updating social importer from 1.3.5 to 1.3.6 gd then disabled social importer and an error occurred

`
The plugin geodir_social_importer-v2/geodir_social_importer.php has been deactivated due to an error: Plugin file does not exist.
`
Also, once it was disabled, the license for the plugin was removed.

![screenshot 2018-07-28 at 6 04 02 pm](https://user-images.githubusercontent.com/114659/43358360-a46ba33a-9290-11e8-8b8b-a86c6db62576.png)

**Comment by Stiofan** [comment]
licence are stored per plugin slug so if the slug changes the licence will say its not there which the -v2 on the end will do.
