### ISSUE TITLE
rc18 - API keys not listed

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#394]
Once an API key has been created/added, there is no list of keys.

Reported
https://wpgeodirectory.com/support/topic/rest-api-keys/#post-440140

![image](https://user-images.githubusercontent.com/114659/43358394-4868d926-9291-11e8-9845-c5aae318d783.png)

**Comment by Stiofan** [comment]
FYI @kprajapatii it seems to work on my local but not on the v2 test site.

**Comment by kprajapatii** [comment]
Fixed
admin-api-keys.min.js was missing
