### ISSUE TITLE
rc-18 - Dummy data from previous version not recognized

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#397]
Dummy data installed with a previous version was not recognized as dummy data.

**Comment by Stiofan** [comment]
I could not recreate this, is there some steps i have to follow?

**Comment by alexrollin** [comment]
I was upgrading the v2 site, it was on rc17. I upgarded it to rc18 and the dummy data tab would not remove the data (installed prior ti rc18.

**Comment by Stiofan** [comment]
I can't think of a reason this would be the case, i'll flag it for kiran to see if he can think of anything.

**Comment by kprajapatii** [comment]
@alexrollin i checked  this but not recreated issue.

Any specific steps to recreate from my side?
