### ISSUE TITLE
rc-18 - some dummy data cats lacking fa icon assignment

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#398]
some dummy data categories don't have a category icon,  leading users to believe that the icons are broken
https://wpgeodirectory.com/support/topic/fa-v5-errors/#post-440142
![screenshot 2018-07-28 at 7 29 15 pm](https://user-images.githubusercontent.com/114659/43359070-8fc76d86-929c-11e8-8f25-c43e9d31f45d.png)

reported here;
https://wpgeodirectory.com/support/topic/fa-v5-errors/#post-440142

**Comment by Stiofan** [comment]
fixed
