### ISSUE TITLE
No listings found message should contain add listing link

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#408]
1. If add listing enabled and a cat or search has no listings then the no listings message should have a link to the add listing page.
2. the above link should auto fill the location and category if present.

**Comment by Stiofan** [comment]
@dhavalayecode do #1 of this task please

**Comment by Stiofan** [comment]
@1naveengiri please do only part 1 of this task, forget part 2.

**Comment by 1naveengiri** [comment]
@Stiofan  added code for this task. Please take a look.
