### ISSUE TITLE
Check WPML compatibility

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#41]
Also check new feature
https://wpgeodirectory.com/support/topic/compatibility-with-wpml-new-feature/#post-413436

**Comment by Stiofan** [comment]
Patrik, ask kiran for help if u have any questions.

**Comment by wpdev10** [comment]
I have looked into this and found that the following filter is modifying the where clause of the query for listings:
`add_filter('posts_where', 'geodir_default_where', 1);`

Code is written in file listing_filters.php located in geodirectory-functions folder.

Let me know if more details required.

**Comment by Stiofan** [comment]
All WPML tasks should be moved here: https://github.com/AyeCode/geodir-multilingual
