### ISSUE TITLE
Fresh install featured image media url error

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#412]
On fresh install with dummy data, dummy featured image shows bad URL
https://ppldb.com/v2test/wp-content/uploads/sites/59//2018/08/2018/08/a1.jpg

Correct image url is shown in featured image in backend editor
https://ppldb.com/v2test/wp-content/uploads/sites/59/2018/08/a1.jpg

![screenshot 2018-08-15 at 3 45 03 pm](https://user-images.githubusercontent.com/114659/44151219-31f11be4-a0a2-11e8-9aad-d7df080d0c19.png)

See here: https://ppldb.com/v2test/places/category/feature/

**Comment by Stiofan** [comment]
fixed
