### ISSUE TITLE
Custom field in SEO metas and titles does not work if field key has an underscore within the field key

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#415]
This is a bug report for "Single page SEO can now use any custom field by using the field key prefixed with an _underscore eg: %%_email%% - ADDED".

All seems to work well unless there is an underscore in the field key:
%%_phone%% works, but %%_second_phone%% does not.
Testing shows that the underscore within the field key is the problem.

**Comment by Stiofan** [comment]
fixed and will be in next release
