### ISSUE TITLE
"Places" can get lost in the menu

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#418]
In many cases users will change the name and icon for the Places CPT, and this results in the adjustment of the order of the menu items.

It would be nice if by default the "Places" and other CPTs could show up right next to GeoDirectory in the WP Menu so that they can be found.

In this case we can find it by the icon, but, what if they changed the icon? How do we find the default CPT?

![screenshot 2018-08-17 at 2 41 43 pm](https://user-images.githubusercontent.com/114659/44266687-ba701080-a22b-11e8-9f0b-3c3b9acb11f2.png)

**Comment by pol76** [comment]
Hovering the link and see which one has the URL ending with:
/wp-admin/edit.php?post_type=gd_place
This is what I did when I found myself in similar cases... Just FYI

**Comment by Stiofan** [comment]
I have added a fix for this as best i can which will work in 99% of cases but the register post type menu_position value does not accept decimals like the normal menu items but they are now both set to 55.
