### ISSUE TITLE
%location% not working in Category Top Description

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#429]
Category: https://ppldb.com/v2/wp-admin/term.php?taxonomy=gd_placecategory&tag_ID=30&post_type=gd_place&wp_http_referer=%2Fv2%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dgd_placecategory%26post_type%3Dgd_place

Location page: https://ppldb.com/v2/places/category/feature/united-states/new-jersey/maple-shade-township/

![screenshot 2018-08-24 at 11 20 40 am](https://user-images.githubusercontent.com/114659/44576780-c14cd500-a78f-11e8-992d-a0226d92349e.png)

Reported here:
https://wpgeodirectory.com/support/topic/category-top-description-location-tag-not-working/#post-443833
https://wpgeodirectory.com/support/topic/location-placeholder-in-category-description-is-not-working/
https://wpgeodirectory.com/support/topic/category-and-region-city-top-description-is-not-showing/

**Comment by alexrollin** [comment]
also

%location% not being replaced in cat top description

example front end page: https://ppldb.com/v2/doctor/category/md/united-states/new-jersey/maple-shade-township/

Cat top description content: https://ppldb.com/v2/wp-admin/term.php?taxonomy=gd_doctorcategory&tag_ID=33&post_type=gd_doctor&wp_http_referer=%2Fv2%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dgd_doctorcategory%26post_type%3Dgd_doctor

Reported here:

**Comment by Stiofan** [comment]
This has been updated to use the same location tags as the SEO page, so basically the %location% tag will now be %%location_single%% or any other one u want to use.
![screenshot from 2018-10-15 12-48-38](https://user-images.githubusercontent.com/10433311/46949303-d865c000-d078-11e8-9e11-305e94e3d0cd.png)
