### ISSUE TITLE
GD Categories - cannot show/use Category/Map Icon

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#432]
GD Categories - cannot show/use Category/Map Icon

V2 GD Categories does not user category/map icons for anything except the 'viewed category'.

Could there be a shortcode param "Use Category/Map Icon"?

![screenshot 2018-08-24 at 11 35 48 am](https://user-images.githubusercontent.com/114659/44578705-9c0e9580-a794-11e8-9bed-5eb069c7f6c1.png)

**Comment by Stiofan** [comment]
The icons were added for this output, if you don't want the icon output there then you just remove the icon and it will show the map marker.
