### ISSUE TITLE
Tag Search showing incomplete results

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#438]
Search for a tag without using autocomplete results 

Here is search fr tag: tagtest without autocomplete, should return 4 results.

https://ppldb.com/v2/search/?geodir_search=1&stype=gd_place&s=tagtest&snear=&sort_by=&spost_category%5B%5D=&sgeo_lat=&sgeo_lon=

https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place

![screenshot 2018-08-30 at 8 49 28 am](https://user-images.githubusercontent.com/114659/44834488-a1a32a00-ac31-11e8-9d2c-dba35f51ef06.png)

![screenshot 2018-08-30 at 8 49 19 am](https://user-images.githubusercontent.com/114659/44834491-a5cf4780-ac31-11e8-80c6-cf64c83225e4.png)

Reported here: 
https://wpgeodirectory.com/support/topic/searching-for-tags-not-working/

**Comment by Stiofan** [comment]
fixed
