### ISSUE TITLE
Read more character count and toggle open/close

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#443]
please see: https://wpgeodirectory.com/support/topic/places-read-more-cant-be-re-minimized/#post-444776

**Comment by alexrollin** [comment]
reporting also: https://wpgeodirectory.com/support/topic/read-more-functionality-in-listing-widgets/

**Comment by Stiofan** [comment]
That is a post meta field, its not an exceprt, to show more/less you can simply use CSS to adjust the height of the box
.geodir-field-post_content {
    max-height: 100px !important;
}
