### ISSUE TITLE
ER - Retina icons

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#449]
Allow retina icons (optional, secondary?)
Now possible with 3.8+ default is optimized=true

https://stackoverflow.com/questions/9208916/google-map-custom-markers-retina-resolution

reported here:
https://wpgeodirectory.com/support/topic/changing-the-image-size-that-is-seen-on-the-map-2/#post-445384

**Comment by Stiofan** [comment]
Optimized=true is not an option we can use, it causes issues with lots of markers.

We can use https://developers.google.com/maps/documentation/javascript/reference/marker#Icon.scaledSize

@kprajapatii i think our options are either add a second input for retina or ask for 2x image.
what do u think?

**Comment by alexrollin** [comment]
fwiw I recommend a second input if only for the sake of variety

**Comment by Stiofan** [comment]
Its not something we really want to "vary"... mo options, mo problems

**Comment by kprajapatii** [comment]
To use Icon.scaledSize option which size will be perfect? Is it fixed size or calculated from icon size dimensions?

**Comment by Stiofan** [comment]
You need to set a specific size. So, maybe the way to do it is if the height is above a certain size then we devide it in half?  We already provide the icon sizes in the api response, so either we set a flag r=true (rentina=true) or we just do if height>30px devide height and width in half and pass that to Icon.scaledSize.  thoughts?

**Comment by kprajapatii** [comment]
Fixed

See https://github.com/AyeCode/geodirectory/commit/1882471d0fcf364b97e766522aba8a972cc9a2b5
