### ISSUE TITLE
some custom post type detail pages not visible

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#452]
https://ppldb.com/v2/location/

choose place listing - works
choose hospital listing - works
choose doctor listing - doesn't work
example:

https://ppldb.com/v2/doctor/md/new-jersey/maple-shade-township/dr-oetker/

![screenshot 2018-09-10 at 3 56 38 pm](https://user-images.githubusercontent.com/114659/45301880-23d4fd80-b512-11e8-9850-52c5fc7a039f.png)

**Comment by Stiofan** [comment]
I cleared version numbers and then went to the page via the doctor CPT page and it worked https://ppldb.com/v2/doctor/united-states/new-jersey/maple-shade-township/md/dr-oetker/
