### ISSUE TITLE
text correction in Extensions -> Themes Tab

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#454]
Text at the bottom of **GD - Extensions -> Themes Tab**

Current text: 

All of our GeoDirectory Themes can be found on GeoDirectory.com here: GeoDirectory Themes

Recommended

All of our GeoDirectory Themes can be found on **WP**GeoDirectory.com here: GeoDirectory Themes

https://ppldb.com/v2/wp-admin/admin.php?page=gd-addons&tab=themes

![screenshot 2018-09-10 at 4 02 36 pm](https://user-images.githubusercontent.com/114659/45302233-081e2700-b513-11e8-9d78-8fdd027b4de0.png)

**Comment by Stiofan** [comment]
fixed
