### ISSUE TITLE
Shortcode builder - Page/Templates - Insert defaults

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#457]
Allow users to make use of the shortcode builder to paste/insert the original default shortcodes for each of the pages and page templates.

https://wpgeodirectory.com/docs-v2/geodirectory/templates/

**Comment by Stiofan** [comment]
I have added a button next to page settings to show the default content.
![screenshot from 2019-01-07 17-36-13](https://user-images.githubusercontent.com/10433311/50783430-c0ca5c00-12a2-11e9-92ab-881ebb2e62ad.png)
![screenshot from 2019-01-07 17-36-04](https://user-images.githubusercontent.com/10433311/50783431-c0ca5c00-12a2-11e9-8cce-36a81a7f379d.png)
