### ISSUE TITLE
ER - %%CPT_LISTING_COUNT%% for archive title

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#459]
Member has requested that there be a way to list the total count of a CPT in the Title (and meta)

Like %%CPT_LISTING_COUNT%%

Related topic:
https://wpgeodirectory.com/support/topic/shortcodes-in-archive-page-title-not-working/#post-446840

**Comment by Stiofan** [comment]
Its not something i am keen to implement, this would need to be trakced per cat/cpt and location, we already do somthing similar and its a nightmare for caching and building queries.
