### ISSUE TITLE
ninja forms integration not sending to listing email field

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#465]
gd_doctor type has email filled, contact button in widget on sidebar, and contact form in tab

both send confirmation email, but no email to listing Email field address.

https://ppldb.com/v2/doctor/united-states/new-jersey/maple-shade-township/md/dr-zoidberg/#contact-me

Reported here:
https://wpgeodirectory.com/support/topic/ninja-no-good/#post-447714

**Comment by Stiofan** [comment]
The contact form needs to start out as a GD contact form, it will add all the right info (there are hidden fields that are needed) to send to the listing email. Maybe add something to the docs?
