### ISSUE TITLE
ER: Author Image, Author Profile Link, post date, last modification date

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#470]
we not have author actions shortcode.

Will there be a way to display 

 - author image : WP | UWP |  BP
 - author profile link:  : WP | UWP |  BP
 - post date
 - last modified date

member request
https://wpgeodirectory.com/support/topic/display-author-post-date-and-last-modification-date/

**Comment by Stiofan** [comment]
author profile link, post date and last modified date added, i'll keep more details stuff like author image to things like UWP (i have already discussed this with Patrik)
