### ISSUE TITLE
Allow import of images with uppercase file extension

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#472]
Currently images with uppercase are showing as 404

Related topic:
https://wpgeodirectory.com/support/topic/images-not-showing-after-import-from-csv/#post-448474

From the docs:
https://wpgeodirectory.com/docs/core-export/
You only need to add the filename of the image, for example photo.jpg. The extension should be in lowercase, ie: .jpg, not .JPG. Uppercase file extensions will result in the image not being recognized when viewed in the site.

**Comment by Stiofan** [comment]
Fixed and will be in the next release.
