### ISSUE TITLE
Hide Admin Bar not working for subscriber

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#473]
https://ppldb.com/v2/

![screenshot 2018-10-03 at 3 56 09 pm](https://user-images.githubusercontent.com/114659/46415150-f18b7a00-c724-11e8-8c98-a1aaa4230421.png)

![screenshot 2018-10-03 at 3 57 01 pm](https://user-images.githubusercontent.com/114659/46415177-fd773c00-c724-11e8-8cab-36a343689e12.png)

Reported here:
https://wpgeodirectory.com/support/topic/restrict-wp-admin-is-showing-the-admin-bar-for-a-subscriber/

**Comment by Stiofan** [comment]
setting not related to the admin bar
