### ISSUE TITLE
Category in Search Bar : Allow 1, 2, 3 Levels

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#475]
Member requests support of Subsubcategory in search bar.

Currently:

V1 allows "Subcategory"
V2 allows "Category"
```

Eat (V2 - Category)
 - Italian (V1 - Subcategory)
 - - Southern Italian (Neither - Subsubcategory)
 - - Nothern Italian (Neither - Subsubcategory)
```

V1
![screenshot 2018-10-04 at 5 59 36 pm](https://user-images.githubusercontent.com/114659/46487716-03424f80-c801-11e8-8cd1-27e21a73d3e7.png)
![screenshot 2018-10-04 at 5 56 45 pm](https://user-images.githubusercontent.com/114659/46487717-03424f80-c801-11e8-87db-0d43ea4800a3.png)

V2
![screenshot 2018-10-04 at 6 09 05 pm](https://user-images.githubusercontent.com/114659/46487729-0a695d80-c801-11e8-81a8-02afed32c2b8.png)

reporting topic
https://wpgeodirectory.com/support/topic/category-how-to-show-more-than-1-level-subcategory/#post-448766

**Comment by Stiofan** [comment]
FIXED
