### ISSUE TITLE
Body Classes - package ID and category

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#477]
In the past body classes have been an important way for members to help their visitors distinguish between listings.

With V2, we could use examples for the following body classes to the Archive Item and Detail Page

 - Package ID
 - Default Category
 - Additional Categories

Further, a rewrite of the relevant/out-of-date portions of this would also help: https://wpgeodirectory.com/add-custom-body-classes-to-wordpress/

@kprajapatii

**Comment by Stiofan** [comment]
package id and default cat are now added
