### ISSUE TITLE
ER: Advanced params for GD Listing including pagination

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#485]
Member requests for gd_listings params that are not yet available in v2

https://github.com/AyeCode/geodirectory/blob/master/includes/widgets/class-geodir-widget-listings.php#L190

```
//            'with_pagination'       => '1',
//            'top_pagination'        => '0',
//            'bottom_pagination'     => '1',
//            'without_no_results'    => 0,
```
https://wpgeodirectory.com/docs/core-shortcodes/#listings

Topic
https://wpgeodirectory.com/support/topic/gd-listing-shortcode-pagination-and-tags/#post-450268
https://wpgeodirectory.com/support/topic/gd_listings-sorting/#post-458001

**Comment by alexrollin** [comment]
request for pagination
https://wpgeodirectory.com/support/topic/pagination-7/#post-467441

**Comment by alexrollin** [comment]
request for pagination
https://wpgeodirectory.com/support/topic/display-paginated-listings/#post-469261

**Comment by kprajapatii** [comment]
Fixed

See https://github.com/AyeCode/geodirectory/pull/660/commits/7b11a9ed4d50af85743a7447da0f7323ce96ded1
