### ISSUE TITLE
Test all GD blocks with Gutenberg and report what works and what needs work

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#486]
Test all GD blocks with Gutenberg and report what works and what needs work.

Example:
Images block
FRONTEND: works
EDITOR: option x does not render

**Comment by dhavalayecode** [comment]
Hello ,

I have tested GD block and widget with Gutenberg and below the reports.

Blocks

GD post meta blocks - Works
GD post title blocks - Works
GD Map blocks - Works
GD Post Directions blocks - Works

Widgets

GD Search  - Works 	
GD Best of listings - Works
GD categories - Works
GD category Description - Works 
GD Dashboard  - Works
GD Recent Reviews  - Works
GD Post Rating  - Works
GD Post Fav  - Works
GD Author Actions  - Works
GD Listings  - Works
GD Add Listings - Works
GD Single Taxonomies - Works
GD Single Tabs - Works
GD Single next prev - Works
GD single closed text - Works
GD Loop - Works
GD Loop Paging - Works
GD Loop actions - Works
GD Post Distance - Works
