### ISSUE TITLE
If tabs are removed, make comments/reviews available (anyways) or shortcode

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#487]
If [gd_single_tabs] is not used on the detail page template, comments/reviews will not show up.

Tabs (and list) output has a lot of markup, Would be nice to have a different way to output the comments/reviews area with tabs or tabs-list markup.

**Comment by Stiofan** [comment]
maybe this was fixed since opened but if the reviews are not output in tabs or another way then the normal WP reviews section will show.
