### ISSUE TITLE
Text Field html5 regex max length pattern not working

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#488]
[0-9A-Za-z]{0,120}

Should limit the input to 120 characters. 

Need some examples for the docs.

**Comment by Stiofan** [comment]
ok i was having issues as i was trying [a-zA-Z0-9]{0,120} on a number input which then breaks all validation on that input, of a number it would need to be somthing like [0-9]{2,4}

So this all seems to be working, just ping me if u need any examples.
