### ISSUE TITLE
ER: Admin actions widget to adjust listing status from frontend

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#493]
Right now in V2 there is the Author actions widget. Perhaps an "Admin actions" widget to allow the admin to publish from the frontend would be a good idea.

Topic
https://wpgeodirectory.com/support/topic/easily-publish-newly-submitted-listings-easily-identify-new-listings/

**Comment by Stiofan** [comment]
I did not like the idea but i did like one of the users other suggestions to add a bubble for pending posts to the admin menu.
