### ISSUE TITLE
2.0.3.2 - GD Listing shortcode disables Beaver Builder on Page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#499]
Any page created wit Beaver that gets a GD listing shortcode can then no longer be edited with BB. The BB edit button doesn't show up. If BB is launched from the backend editor of that page, then none of the visual builder elements show up for editing, meaning the blue outlines do not show up.

http://ppldb.com/beaver/ (home page cant be edited)
http://ppldb.com/beaver/bb-test/ (test page that cant be edited)

reporting topic
https://wpgeodirectory.com/support/topic/beaver-builder-not-working-after-update/

**Comment by Stiofan** [comment]
This is fixed and will be in the next release
