### ISSUE TITLE
2.0.3.2 - Editor (permissions?) error on description field

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#502]
to recreate

false
go to ppldb.com/v2/add-listing with admin login
add listing, no error

positive
go to ppldb.com/v2/add-listing with subscriber login
see error

The only apparent error is "This field is required" near the description field, but it has a value.

![screenshot 2018-10-27 at 10 29 33 am](https://user-images.githubusercontent.com/114659/47601628-d8988080-d9d3-11e8-81f5-16d44e99db0e.png)

reporting topics:
https://wpgeodirectory.com/support/topic/company-logo-import-not-working/#post-451450
https://wpgeodirectory.com/support/topic/event-imported-with-siv2-does-not-import-have-photos-in-tab/#post-451287

**Comment by Stiofan** [comment]
fixed
