### ISSUE TITLE
2.0.3.2 - Only one image imported

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#503]
Test

add a place with 3 images
export and verify image links
import - see only one image imported

reporting topic
https://wpgeodirectory.com/support/topic/cant-import-more-than-one-photo/

**Comment by Stiofan** [comment]
I think this is due to a bug that was already fixed (but removed by kirans mistake) i tested and could not recreate after re-applying my fixes, i'll close this for now and we can re-open it if it persists after next release.
