### ISSUE TITLE
2.3.0.2 - If Bp 3.2 is active - cannot go to search page - redirects home

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#504]
test on ppldb.com try to visit search page

reporting topic
https://wpgeodirectory.com/support/topic/report-searching-issues-css-question/#post-451466

**Comment by Stiofan** [comment]
https://wpgeodirectory.com/support/topic/report-searching-issues-css-question/#post-451469
BP take over the slug "search" prob best we add this in docs that you need to change it if using BP.
I could add a warning somewhere if u think it will help?  Let me know when ur done with docs and i'll make this done.

**Comment by alexrollin** [comment]
I have added a V2 known issues section here: https://wpgeodirectory.com/docs-v2/faq/troubleshooting/#bp

**Comment by Stiofan** [comment]
there is now a warning in place for this in the core plugin
