### ISSUE TITLE
Second video field key cannot be edited

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#509]
Places settings, add a second video fied, key is greyed out and cannot be edited.

https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings

![screenshot 2018-11-05 at 12 00 09 pm](https://user-images.githubusercontent.com/114659/47994417-7554cf80-e0f2-11e8-8e90-9056f3ac79bf.png)

reporting topic
https://wpgeodirectory.com/support/topic/2-or-more-video-problem/#post-452511

**Comment by alexrollin** [comment]
Close: Add a textarea field instead

**Comment by alexrollin** [comment]
Nice to have - users cannot add a second video field (so they don't encounter this issue)

**Comment by Stiofan** [comment]
New non single use predefined custom fields should have ability to change field key - FIXED
