### ISSUE TITLE
Place details page, tabs not displaying correctly in V2

### ISSUE THREAD

**Issue by MHAdministrator** [AyeCode/geodirectory#512]
Place details page, tabs not displaying correctly in V2
The selected tab is "blank" when selected

![profiletabserror](https://user-images.githubusercontent.com/44895100/48411005-f5a9af00-e748-11e8-8ec3-e12ab06290fa.png)

Here is the system status [system state.txt](https://github.com/AyeCode/geodirectory/files/2576058/system.state.txt)

**Comment by Stiofan** [comment]
Please update your theme to v2, you can find this in your account area if you have already gone through the free checkout: https://wpgeodirectory.com/your-account/
if not you can add it from here: https://wpgeodirectory.com/downloads/directory-starter/

**Comment by MHAdministrator** [comment]
Thanks Stiofan 👍 , maybe GeoDirectory can update the V2 Supreme zip file which contains the older Starter theme version? Would simplify things I think :-)
