### ISSUE TITLE
Sidebar widgets not displaying on place details page

### ISSUE THREAD

**Issue by MHAdministrator** [AyeCode/geodirectory#513]
Sidebar widgets not displaying on place details page

Widgets are active
![widgetsnotdisplayingbutactive](https://user-images.githubusercontent.com/44895100/48411478-4e2d7c00-e74a-11e8-9155-62b6d23060a3.png)
 
Widgets not displaying
![widgetsnotdisplaying](https://user-images.githubusercontent.com/44895100/48411511-60a7b580-e74a-11e8-8cbf-0c4d025ed542.png)

System Status = [system state.txt](https://github.com/AyeCode/geodirectory/files/2576091/system.state.txt)

**Comment by Stiofan** [comment]
I am assuming you are using Directory Starter which has its own sidebar for GD pages.
