### ISSUE TITLE
CSS Web Safe Font Combinations using Quotes disable visual editor in WP

### ISSUE THREAD

**Issue by rungemach** [AyeCode/geodirectory#517]
Changing the fonts listed under Appearance>Themes>Customize>Body>Typography to any CSS Web Safe Font Combinations using Quotes such as "Lucida Sans Unicode", "Lucida Grande", sans-serif; "Trebuchet MS", Helvetica, sans-serif, impacts the admin page. It removes the ability to use the visual editor, all of the buttons and any display in the visual editor. 
Just GeoDirectory V2 and some of the plugins are installed. No other plugins.

**Comment by pol76** [comment]
If you deactivate GD the problem goes away? What theme are you using?

**Comment by Stiofan** [comment]
I was able to replicate and have fixed this in Directory Starter theme
