### ISSUE TITLE
Bug - star shadow when listings squished together

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#518]
To see the issue:

Go to thispage https://ppldb.com/v2/searchx/?geodir_search=1&stype=gd_place&spost_category%5B%5D=&s=+&snear=&sort_by=&sgeo_lat=&sgeo_lon=&city=enschede

Use theorange arrow on the map to drag the map left and squish the listings.

As the 5 star rating is squished, extra greay stars (shadows) show up below the 5 star rating.

![image](https://user-images.githubusercontent.com/114659/48652035-d8513b00-e9fd-11e8-8c3a-e66535a61cba.png)

Reporting topic
https://wpgeodirectory.com/support/topic/php-errors/page/2/#post-454634

**Comment by alexrollin** [comment]
Something similar is happening on the detail page

![image](https://user-images.githubusercontent.com/114659/50055109-8ad60400-014a-11e9-8f47-351d23add84d.png)
https://www.revue.pw/prod/australia/queensland/gold-coast/food-drink-and-supplements/chia-deli-crisps/#comment-14

**Comment by wpdev10** [comment]
For https://github.com/AyeCode/geodirectory/issues/518#issue-381793709,

I would suggest we should not allow squishing below say 400px width visible area for listings.

For https://github.com/AyeCode/geodirectory/issues/518#issuecomment-447649151

I have found one CSS causing this issue. The CSS is located in _ratings.scss file of GDV2 core. Following is the output of CSS:
`.gd-rating.gd-rating-output img{width:20%}`

The width is not required here.
