### ISSUE TITLE
post "Is featured" default value checked not saving value

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#524]
When "Is Featured" is set to Defautl Value "Checked" the value does not save with the listing. Instead the box is lit up again.

So, to test, set to default checked
Uncheck the box
save
the listing wil be checked again when refreshed

save again (while it appears checked)
the db value is  not saved

So, in short, default value "Checked" does not work

tested on 38 and 39

![image](https://user-images.githubusercontent.com/114659/49522022-f4caef80-f8a6-11e8-8ec9-750ffd676d97.png)

Related topic:
https://wpgeodirectory.com/support/topic/featured-event-package/page/2/#post-457514

**Comment by Stiofan** [comment]
@1naveengiri please check if this is still an issue, i think it might have been fixed already

**Comment by 1naveengiri** [comment]
@Stiofan & @alexrollin It seems to be fixed in latest master branch code. 
the field is properly reflecting in backend setting as well as in frontend add listing form.

**Comment by pol76** [comment]
Apparently this is still an issue https://wpgeodirectory.com/support/topic/is-featured-default-value-checked-bug/#post-481433

**Comment by alexrollin** [comment]
Also https://wpgeodirectory.com/support/topic/listing-added-approved-featured-but-didnt-pay/#post-481662

**Comment by alexrollin** [comment]
@kprajapatii ^^
