### ISSUE TITLE
Comma in Title (or description) of image caption wipes content after comma

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#528]
To test

use V2, add a listing, add an image, edit the title with a comma and description, close the dialog.
open the caption editor again and see the wipe from after the comma.

reporting topic:
https://wpgeodirectory.com/support/topic/image-caption-and-title-cannot-show-comma/

**Comment by alexrollin** [comment]
@Stiofan @kprajapatii

**Comment by alexrollin** [comment]
member request: https://wpgeodirectory.com/support/topic/image-field/#post-476131

**Comment by Stiofan** [comment]
@picocodes check if this is still an issue, i'm not sure if it is or not.

**Comment by picocodes** [comment]
@Stiofan I have tested with several listings and the issue seems resolved.

**Comment by picocodes** [comment]
@Stiofan apparently, the issue affects some listings and does not affect others

**Comment by picocodes** [comment]
Let me try to fix it

**Comment by picocodes** [comment]
Looks like listing images are separated by a comma while individual image meta details are separated by a vertical bar `|` as shown in the example below:-
```
<input type="hidden" name="post_images" id="post_images" value="http://localhost/wp-content/uploads/2019/04/a18.jpg|72|sample title|sample caption,http://localhost/wp-content/uploads/2019/04/a10-3.jpg|73|another title|another caption">
```
As a result, users can't use a comma or vertical bar in the title or caption fields.

We can solve this by saving the image details as a JSON string or replacing the comma and vertical bar with less used symbols as separators. 

For example:

We can use a caret to separate the images and a grave accent to separate the image meta.

@alexrollin  and @Stiofan let me know if this is something we should explore, or if we should leave the implementation as is and update the docs to inform the users not to  use commas and vertical bars in the image captions and titles.
