### ISSUE TITLE
Archive item review Stars on two lines by default

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#534]
stars inside the archive item container are forced to show on two lines by default 
they should show on one
![2018-12-14-reviews-2](https://user-images.githubusercontent.com/114659/50005538-08fba480-ffab-11e8-9599-ccdc2b8e5173.jpg)

**Comment by alexrollin** [comment]
this is not fixed for listings that are shown in layout=0 alignment="right" if the item is not displaying on a new line and pressed against another item.

**Comment by Stiofan** [comment]
fixed
