### ISSUE TITLE
ER: Use WP color picker for gd_post_badge

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#535]
The current color picker when used on windows doesn't allow input of hex colors

![image](https://user-images.githubusercontent.com/114659/50024146-c2756c80-ffe1-11e8-88d6-8a4dc30e0382.png)

**Comment by Stiofan** [comment]
The input is a HTML5 color input, its provided by the browser, its not something we can change, its just however that browser decides to implement it, alot like how select inputs are different on every browser.

**Comment by alexrollin** [comment]
I have never gotten that from any other app.  It has no hex or rgb input.
