### ISSUE TITLE
ER: gd_post_badge use single quote on "badge" field for html 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#536]
use single quotes to allow possible HTML

[gd_post_badge key="facebook" condition="is_not_empty" badge=**'<i class="fab fa-facebook-square"></i>'** link="%%input%%" bg_color="#ffffff" txt_color="#0000a0"]
[gd_post_badge key="website" condition="is_not_empty" badge=**'<i class="fas fa-link"></i>'** link="%%input%%" bg_color="#ffffff" txt_color="#0000a0"]

**Comment by Stiofan** [comment]
the choice is between a double quote ( " ) and a single quote ( ' ) 
HTML works with either, but if a user is simply entering text then like "Mike's place" then the single quote will cause more problems.
