### ISSUE TITLE
Enable Location Filter is ON by default and no button to disable

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#541]
gd_listing Location Filter is on by default, and should be set to off, based on the fact that the only button is "Enable Location Filter"

`
[gd_listings title="Popular Places" post_type="gd_place" sort_by="az" title_tag="h3" layout="gridview_onefifth" post_limit="15" add_location_filter="1"]
`
![image](https://user-images.githubusercontent.com/114659/50190219-ba426780-0328-11e9-921f-ed8d56fb736c.png)

reporting topic
https://wpgeodirectory.com/support/topic/gd_listings-current-author-multi-cities/#post-459248

**Comment by Stiofan** [comment]
i'm not sure i understand the issue here?
