### ISSUE TITLE
ER gd_post_meta "raw" output

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#547]
Allow post_meta an output type of "raw" that output ONLY the value and nothing else, aka no markup.

For use in GD Post meta show "value_raw" to show
We could post a guide as to what the output would be
like -
phone - the contents without link
url - the url without title or link markup
textarea - the contents of the field
text - the contents of the field
checkbox - 1 or 0
select - the value, or label if no value like (Label/value) Brazilian BBQ/brazilian-bbq

%%my_custom_select_label%%
%%my_custom_select_value%% (raw)

Related to this would be 
additional replacements with raw/slugs for location data and category
 https://github.com/AyeCode/geodirectory/issues/998
helper for image css background in badges
https://github.com/AyeCode/geodirectory/issues/1009

https://wpgeodirectory.com/support/topic/how-to-strip-html-from-shortcode/#post-459937

**Comment by alexrollin** [comment]
requested https://wpgeodirectory.com/support/topic/styling-a-shortcode/#post-466752

**Comment by alexrollin** [comment]
Member request https://wpgeodirectory.com/support/topic/shortcodes-in-the-sidebar/#post-469667

**Comment by alexrollin** [comment]
Member request
https://wpgeodirectory.com/support/topic/gd_post_title/

Specifically for post title.

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/output-fields-without-additional-html/#post-520995

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/how-can-post-meta-keys-be-used-anywhere/

**Comment by scysys** [comment]
Also looking for this. @alexrollin You found an solution for now?

**Comment by alexrollin** [comment]
Request
https://wpgeodirectory.com/support/topic/remove-default-output-markup-of-gd_post_title/

**Comment by scysys** [comment]
> Request
> https://wpgeodirectory.com/support/topic/remove-default-output-markup-of-gd_post_title/

Thanks @alexrollin!
For my needs i solved it in this way

```
<?php

// Get content from shortcodes
$raw = do_shortcode('[gd_post_meta key="facebook"]');
$html = htmlspecialchars_decode($raw);

$doc = new DOMDocument();
@$doc->loadHTML($html);

$tags = $doc->getElementsByTagName('a');

foreach ($tags as $tag) { 
	// Store output into variable
	$radio_facebook_url = $tag->getAttribute('href');
	// Debug output
	#echo $tag->getAttribute('href');
}

// Final output
echo '<a href="'.$radio_facebook_url.'" class="fa fa-facebook" target="_blank"></a>';

?>
```

**Comment by alexrollin** [comment]
Another request
https://wpgeodirectory.com/support/topic/embedding-custom-fields-dynamically/page/2/#post-535081

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/1113/commits/2dbe0cc49eba6767e3fa1f8a24f413c9285ff6c8

New option 'value-raw' added in gd_post_meta value output.

Examples: https://ppldb.com/kiran/gd_post_meta/
