### ISSUE TITLE
geodir_file_relative_url() should check for www.

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#555]
We had a user who's upgrade kept failing as the site url used to have the www. part but now does not, so the term upgrade function never completed, even if run over and over.
https://wpgeodirectory.com/support/topic/converting-v1-to-v2/#post-460515
Should we make the function geodir_file_relative_url() check for a www. in the url also?

Stiofan

**Comment by Stiofan** [comment]
@kprajapatii  did u ever implement this?

**Comment by kprajapatii** [comment]
I will implement this.

**Comment by kprajapatii** [comment]
Fixed
https://github.com/AyeCode/geodirectory/commit/9613aac36f31738334886164f4d0f5a4f3f4a7d5
