### ISSUE TITLE
ER: Image processing - EXIF and Media Library 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#557]
**EXIF advanced support for mobile**
Users take pics with their phones. 
Ayecode could add support for EXIF 'orientation' so that the rotation of the image on the phone is shown also in UWP or GD media gallery.

Also, we could add some processing options like 'rotate', then, to images, to allow users to rotate them and do it only with the EXIF data.

topic
https://wpgeodirectory.com/support/topic/image-is-rotated/#post-460625

**Save title and capition to media library item**
If title or caption is added to a listing image that is also a featured image, store that information to the image in the media library.
![image](https://user-images.githubusercontent.com/114659/66558713-50fc4100-eb54-11e9-9f32-53a65b5268b0.png)
Request
https://wpgeodirectory.com/support/topic/why-dont-uploaded-images-include-file-data/#post-512476

**Comment by Stiofan** [comment]
There was an issue with this that was preventing smaller generated images using the right roations, this has now been fixed.
