### ISSUE TITLE
ER: Add "Processing" to add listing page submit button

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#559]
Member says it is too easy to press the submit button again due to the delay.
Add "Processing" like on the social importer so they user gets some immediate feedback

https://wpgeodirectory.com/support/topic/adding-place-is-buggy/

**Comment by alexrollin** [comment]
member reporting https://wpgeodirectory.com/support/topic/double-emails/#post-465616

**Comment by Stiofan** [comment]
This was added at some point
