### ISSUE TITLE
Register link on Add Listing page

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#563]
I don't understand why we are not giving a register link on the Add Listing page.
We do give a register link when adding reviews:
<a href="https://imgur.com/f09rDX0"><img src="https://i.imgur.com/f09rDX0.png" title="source: imgur.com" /></a>
and when Claiming a listing:
<a href="https://imgur.com/cW8ovsx"><img src="https://i.imgur.com/cW8ovsx.png" title="source: imgur.com" /></a>
Why is there no register link when adding a listing?
<a href="https://imgur.com/mvJmDG5"><img src="https://i.imgur.com/mvJmDG5.png" title="source: imgur.com" /></a>

**Comment by alexrollin** [comment]
I created a small section in the Getting Started doc about login/users: https://wpgeodirectory.com/docs-v2/geodirectory/getting-started/#users

That section links to this doc about account management:

Account Management doc:
https://wpgeodirectory.com/docs-v2/geodirectory/account-management/

Which further links to this doc about UsersWP integration
https://wpgeodirectory.com/docs-v2/integrations/userswp/

What i understood at this time is:
GD default behavior
- If the visitor is not logged in, the default WP Simple login form is shown.
- They can check the settings - GD - Settings, General, Advanced, Allow posting without logging in? - CHECK
   - This will allow users to see the add listing form, and register an account when they add their listing (name and email fields).

If UWP is installed, then
- IN UWP, check to make sure the Login page is configured and working
- UWP will automatically redirect the add-listing page to the UWP Login page
- Users can follow the UWP login-box link to create an account
 - The User will be redirect back to the add-listing page from the login page
- In theory, at some point in a future release - the user will be redirected back to the add listing page from the UWP register page also)

For UWP the same redirects should be in place for comments? and claim?

The UWP add listing page redirect is broken, now, with 20043, but this was working a couple weeks ago, last time I checked on it.

**Comment by Guust-Flater** [comment]
That is not the point.
It should be simple and consistent for our customers.
It is standard to include a register link with a login widget.
The register link can be redirected depending on what you use: UWP or BP or nothing.
Asking only on the Add Listing page to use another BP register link or UWP register link is counter-intuitive for everyone, and bad UX.

**Comment by alexrollin** [comment]
Users waiting for an answer
https://wpgeodirectory.com/support/topic/registration-link-missing-from-add-listing/
