### ISSUE TITLE
Wide checkbox in custom field settings.

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#566]
See image
![capture](https://user-images.githubusercontent.com/25163253/50783450-847e0800-1270-11e9-9abc-cefa02de0588.JPG)
Thanks

**Comment by Stiofan** [comment]
Where was this?  I can't seem to replicate.

**Comment by pol76** [comment]
Using Firefox 

https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings

Any field.

Thanks

**Comment by Stiofan** [comment]
Fixed, will be in next release
