### ISSUE TITLE
PHP 7.3 Warning

### ISSUE THREAD

**Issue by korchung** [AyeCode/geodirectory#569]
Getting this PHP Warning on PHP7.3 

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

File Location : wp-content/plugins/geodirectory/includes/api/class-geodir-rest-posts-controller.php:2522

**Comment by korchung** [comment]
Sorry, 

There were multiple files being affected by this. 

wp-content/plugins/geodirectory/geodirectory.php:472
wp-content/plugins/geodirectory/geodirectory.php:469
wp-content/plugins/geodirectory/geodirectory.php:110
wp-content/plugins/geodirectory/geodirectory.php:320
wp-content/plugins/geodirectory/includes/class-geodir-api.php:34
wp-content/plugins/geodirectory/includes/class-geodir-api.php:106
wp-content/plugins/geodirectory/includes/api/class-geodir-rest-posts-controller.php:2522

**Comment by Stiofan** [comment]
fixed and will be in next release
