### ISSUE TITLE
FB Share of GD listings is reading bad data from site.

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#576]
When a listing is shared to FB it is saying "Sorry, no records found" like it is reading the page remotely and finding that text.

In some cases the logo of the site is being shared instead of the listing image.

Can we do anything to make FB shares better?

reported here:
https://wpgeodirectory.com/support/topic/facebook-description-no-records-found/#post-463127

link to share as example
https://wpgeodirectory.com/support/topic/facebook-description-no-records-found/#post-463127

share outputs on fb from their scraper
![fb share](https://user-images.githubusercontent.com/114659/51102266-90247e00-17de-11e9-8e15-49e8251aad09.jpg)

![fb share 2](https://user-images.githubusercontent.com/114659/51102269-931f6e80-17de-11e9-83c3-b965d73f9bce.jpg)

**Comment by Stiofan** [comment]
Site is running v1 not v2
