### ISSUE TITLE
Front end author actions - After delete, page is 404

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#585]
After editing a page, redirect to home page instead of showing deleted paged as 404

reported here:
https://wpgeodirectory.com/support/topic/page-not-found-14/

**Comment by Stiofan** [comment]
Ideally we would want to show a confirmation message after.
Maybe redirect to the authors listings for that CPT and show a message via the gd_notifications shortcode/widget that will likely be on that page.
So redirect to something like http://localhost/author/admin/places/ and add a query arg to indicate to show a deleted successfully message?

**Comment by 1naveengiri** [comment]
@Stiofan , 
Added code for fixing this issue. Please give it a look.
