### ISSUE TITLE
Sorting and subsort

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#587]
When sorting by price package, then date added, the first

listing 1 - package id 3 - added 2017
listing 2 - package id 3 - added 2018

listing 3 - package id 2 - added 2018
listing 4 - package id 2 - added 2017

sorting by
 - package id - descending
    - subsort with date added, ascending

expected output

1,2,4,3

actual output

1,2,3,4

conclusion

Subsort is being applied to the first group of package ids, but not subsequent groups

**Comment by Stiofan** [comment]
do u have a link to the example?
