### ISSUE TITLE
gd_post_meta for text fields - limited by pricing - still showing on output

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#588]
text field 'slogan' added to places
field excluded from "free" package and included in gold
https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings&tab=cpt-package
[gd_post_meta key="slogan" show="value"] added to archive and detail templates

gd output location on sidebar properly hides the field for Free package 
but detail and archive templates show the output

https://ppldb.com/v2/places/category/awesome/united-states/new-york/new-york/
![image](https://user-images.githubusercontent.com/114659/51447451-8fc83d80-1d1e-11e9-9e37-fb4119e71e87.png)

**Comment by alexrollin** [comment]
@Stiofan

**Comment by Stiofan** [comment]
kiran fixed this recently and it will be in next release
