### ISSUE TITLE
Empty CPT showing in post type selector on gd_map

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#589]
Even if all tags, categories and listings are removed an empty CPT will still show on the post type map.

this is particularly an issue for places which cant be deleted
see: https://ppldb.com/v2/location/
![image](https://user-images.githubusercontent.com/114659/51449938-ca39d680-1d2e-11e9-97e8-285e5c45ebd6.png)

**Comment by alexrollin** [comment]
@Stiofan

**Comment by Guust-Flater** [comment]
You can tick "Disable physical location?" for Places, then it should disappear from the CPT ribbon.
But that will only work if you have the Location Manager active.

**Comment by Stiofan** [comment]
This will be in the next release.
