### ISSUE TITLE
Business hours input format

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#590]
Business hours output format is set by the WP time format settings but the input is not, is there a way to make the input work the same?
https://wpgeodirectory.com/support/topic/display-hours-of-operation-on-listings/#post-464756

**Comment by Stiofan** [comment]
@kprajapatii did u look at this?

**Comment by kprajapatii** [comment]
I have checked and setting target field will fix this. I will implement target field for timepicker.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/675/commits/4aab5d9c515cdbea15aa4681c0d500b3abbc6db2

Now it will use WP time format as a input format. It is also possible to filter input format via hook.
