### ISSUE TITLE
Add exact phrase searching

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#595]
adding the searched text in "quotes" should search for the exact phrase, this should also search exact tags like "hotel rooms"
https://wpgeodirectory.com/support/topic/search-not-working-correctlry/

**Comment by Stiofan** [comment]
@kprajapatii lets also make it that if "quotes" are used that the search is limited to exact text in the title or description only.  Let me know if u have any questions.

**Comment by alexrollin** [comment]
Is this going to cover this case here:
https://wpgeodirectory.com/support/topic/search-not-working-anymore/page/2/#post-475560

Or do we need another issue for that one? The issue is tag results are not returning. Whether it is multiword or multilingual rtd.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/664/commits/6989073ca76e37cb4f59f349d6ed067e744e4417

@alexrollin

**Comment by alexrollin** [comment]
can someone look at this one please?

https://wpgeodirectory.com/support/topic/search-not-working-anymore/page/2/#post-475560

**Comment by Stiofan** [comment]
@alexrollin i have made some changes here that should resolve this for the user
