### ISSUE TITLE
bug gd_post_badge block advanced not showing color

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#601]
![image](https://user-images.githubusercontent.com/114659/52165275-c0d14680-26fe-11e9-8713-146b602a854b.png)

On windows this input ...widget...does not allow input of a hex value.

**Comment by Stiofan** [comment]
This seems to actually be a browser bug that is applied in Gutenberg, i have opened a ticket https://github.com/WordPress/gutenberg/issues/14377
I have added our own CSS fix for this so i'm closing this for now.
