### ISSUE TITLE
Make Package ID CSS consistant

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#607]
In archive items package is being loaded as .gd-post-pkg-2

When detail page is created with blocks then package id is not loaded

New package id snippet hints that new CSS class will be .gd-pkg-id-2 (different than archive item above)

Reported here:
https://wpgeodirectory.com/support/topic/hide-map-for-package/#post-467773

**Comment by Stiofan** [comment]
one is for the body and one is for the individual posts
