### ISSUE TITLE
ER: Listing Bulk Deletion script

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#609]
Some users have 10k+ listings and on special occasions like the setup of a new site need to remove all listings . Where they already have all their custom settings and CPT setup, they want to keep those settings so starting over isn't an option, and they may not have a DB snapshot that would only exclude the listing data.

We could make a special script that would delete all listings from a single CPT
Nice to have would be an option to:
 - exclude all listings in one category. 
 - delete all listings in one category

This would solve the issue of some members occasionally digging into the db to delete large amounts of listings.

Alternatively we have a little tut that explains how to delete 200 at a time here:
https://wpgeodirectory.com/docs-v2/faq/troubleshooting/#delete
@pol76

**Comment by Stiofan** [comment]
Maybe we could add a delete functionality to CSV importer from post id?

**Comment by 1naveengiri** [comment]
one alternative is wp-cli command here 
https://developer.wordpress.org/cli/commands/post/delete/

**Comment by picocodes** [comment]
Most people can't set up wp-cli

**Comment by Stiofan** [comment]
there are plugins that can do this
