### ISSUE TITLE
Location title with %%in_location&& shows comma when city missing like "COOL STUFF in , New Jersey, United States"

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#610]
https://ppldb.com/v2/location/united-states/new-jersey/

![image](https://user-images.githubusercontent.com/114659/52630651-1d7def80-2ebd-11e9-9f0d-b3f3284eed73.png)

COOL STUFF %%in_location%%

https://ppldb.com/v2/wp-admin/admin.php?page=gd-settings&tab=general&section=seo

**Comment by Stiofan** [comment]
Seems to have been fixed sometime in the past
