### ISSUE TITLE
ER: Avia Builder integration

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#616]
Avia builder used in Enfold theme the backend is conflicting with the shortcode builder 

The builder is not particularly visual, and it appears that the edits are mostly with shortcodes, but members also have the opportunity to add a widget area and use GD widgets in that widget area.

https://wpgeodirectory.com/support/topic/v2-search-and-shortcode/#post-469161

**Comment by Stiofan** [comment]
Let @pol76 know when this is fully tested.

**Comment by Stiofan** [comment]
fixed
