### ISSUE TITLE
ER: Read More link or gd_post_badge key for listing_link or listing_url

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#618]
All gd_post_badge to use a key like "listing_link" to create a read more link or other similar

This would allow members to make their own 'read more' link the way they want.

gd_post_badge key='listing_link' badge='<a href="%%input%%">read more</a>

member request
https://wpgeodirectory.com/support/topic/image-sizes-and-disable-read-more-expansion/#post-469260
https://wpgeodirectory.com/support/topic/gd-archive-item-more-info-link/

**Comment by Stiofan** [comment]
https://github.com/AyeCode/geodirectory/issues/538
