### ISSUE TITLE
Map categories can't be shown unticked

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#621]
https://wpgeodirectory.com/support/topic/select-category-to-untick-by-default-on-map-in-v2/

There is no way to show map categories but have them unticked by default like could be done in v1.
Just now we can add remove cats by ID, like 12 or -12 maybe we should add a option like 12u or --12 or similar.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/948/commits/ebf3ba7f0b535ef002d46343417303e895cbb995

**Comment by kprajapatii** [comment]
Example
tick_terms="20,30" to show ticked
OR 
tick_terms="-20,-30" to show unticked

**Comment by Stiofan** [comment]
Good work @kprajapatii :)
