### ISSUE TITLE
Add embeds option for textarea

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#625]
Add a option to textareas to enable "Embed Media URLs" https://codex.wordpress.org/Embeds

see: https://wpgeodirectory.com/support/topic/second-video-tab-only-shows-url/

**Comment by kprajapatii** [comment]
Fixed 
See https://github.com/AyeCode/geodirectory/pull/624/commits/481e63a8537c8bfd238ba9097eb99efe9e8ed0d8
