### ISSUE TITLE
Add link to "View all linked posts" in "linked CPT tab"

### ISSUE THREAD

**Issue by Guust-Flater** [AyeCode/geodirectory#643]
In V1 there used to be a link to all linked posts, for example 
https://wpgeo.directory/docs/places/italy/lombardy/milan/restaurants/zavino-pizzeria-and-wine-bar/#link_business

And I hope the linked post page will have sorting like https://wpgeo.directory/docs/events/?venue=60-Zavino+Pizzeria+and+Wine+Bar

That has disappeared in V2.

**Comment by alexrollin** [comment]
The page is nice. 
https://wpgeo.directory/docs/events/?venue=60-Zavino+Pizzeria+and+Wine+Bar

Would use Archive template?

**Comment by kprajapatii** [comment]
Fixed 
See https://github.com/AyeCode/geodir_custom_posts-v2/pull/25/commits/0a72289fac348307a87e6c0e6c53c31541981676
