### ISSUE TITLE
Advanced Widget Properties (or toggle) not visible in site origin page builder

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#653]
![image](https://user-images.githubusercontent.com/114659/54398281-b620ae80-46b9-11e9-9116-8367da1c7faf.png)

**Comment by Stiofan** [comment]
Seem to work fine for me, what theme are u using?
![Screenshot from 2019-03-15 19-34-13](https://user-images.githubusercontent.com/10433311/54457525-8a550580-4759-11e9-8cac-63120db50874.png)
