### ISSUE TITLE
Elementor - Add listing page map not working

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#659]
Add listing page done with elementor map not working
https://wpgeodirectory.com/support/topic/gd-archive-is-not-showing-anything/#post-475231

**Comment by Stiofan** [comment]
the text editor element where the shortcode inserter is can add double linebreaks which breaks JS, i'm guessing thats the issue here?

**Comment by Stiofan** [comment]
If the issue was related to my comment above then we should add docs that some shortcodes like add lsiting and loop should be added in the code block
