### ISSUE TITLE
ER: GD Listings - Favorites Only - To work with user filtering

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#662]
Member requests (plural)
https://wpgeodirectory.com/support/topic/shortcode-for-favorites/

**Comment by alexrollin** [comment]
Request
https://wpgeodirectory.com/support/topic/event-favourites/#post-475626

**Comment by alexrollin** [comment]
Request
https://wpgeodirectory.com/support/topic/displaying-favorite-listings/#post-482028

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/718/commits/eddb8f76842e6ee9679f5f43d6d48afdad70387e

**Comment by kprajapatii** [comment]
@alexrollin
