### ISSUE TITLE
ER: Yoast Breadcrumbs needs more work

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#671]
Member requests:
https://wpgeodirectory.com/support/topic/yoast-breadcrumbs/#post-476195

Old docs
```

<blockquote><a href="#breadcrumbs" name="breadcrumbs">Add breadcrumbs?</a></blockquote>

Breadcrumbs are really a theme function, and since GD is a plugin, V2 doesn't have a breadcrumbs system built in.

If your theme doesn't have breadcrumbs, you can try Yoast SEO, which has a breadcrumbs feature in the free version of the plugin. 

You can read how to turn the <a href="https://kb.yoast.com/kb/implement-wordpress-seo-breadcrumbs/" rel="noopener" target="_blank">Yoast Breacrumbs feature on and configure it on the Yoast site</a>.

The Yoast breadcrumbs shortcode can be used on GD Archive and GD Detail templates.

<code>[wpseo_breadcrumb]</code>

For other implementations with Yoast breadcrumbs you will need to contact Yoast support or hire a developer.
```

**Comment by alexrollin** [comment]
members are being vocal about wanting these to work properly
https://wpgeodirectory.com/support/topic/breadcrumbs-support-for-supreme-directory-v2/page/2/#post-476851
https://wpgeodirectory.com/support/topic/breadcrumbs-6/

https://wpgeodirectory.com/support/topic/breadcrumbs-issue/

**Comment by picocodes** [comment]
on it

**Comment by MyThemeShop** [comment]
Hello @picocodes , @alexrollin 

Please add the support for the breadcrumbs of the Rank Math plugin as well. A few users requested for the same.

Here are the filters required for the same:
https://rankmath.com/kb/filters-hooks-api-developer/#breadcrumbs

Please let us know if we can help in any way.

Once added, please submit your product here:
https://rankmath.com/contact/

So we can list you on our website as a compatible product:
https://rankmath.com/compatibility/wp-rocket/

Thank you.

**Comment by picocodes** [comment]
on it.

**Comment by picocodes** [comment]
If @stiofan assigns me the task
