### ISSUE TITLE
20049 Address Show in Output Locations (GD Post Meta) not respecting custom field display settings

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#680]
Member reports that after update to 20049 that the address display is now showing portions that were unchecked for display in address custom field.

https://wpgeodirectory.com/support/topic/problem-with-adress-field-after-gd-update-today/#post-476647

**Comment by alexrollin** [comment]
![image](https://user-images.githubusercontent.com/114659/55063426-3ced6800-5078-11e9-8eb8-023af16eae3b.png)

![image](https://user-images.githubusercontent.com/114659/55063456-5098ce80-5078-11e9-9432-e46e9f6332f9.png)

https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings
https://ppldb.com/v2/places/high-zoom/

**Comment by alexrollin** [comment]
Should those settings now be removed in 20049?
Or should they override everything except the gd_post_address?

**Comment by Stiofan** [comment]
fixed and will be in the next release
