### ISSUE TITLE
Bring back sort by location in the CPT backend listing page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#691]
in the places backend
![image](https://user-images.githubusercontent.com/114659/55429156-143f0400-558b-11e9-9578-74211849838c.png)

member request
https://wpgeodirectory.com/support/topic/backend-sorting-by-location-v1-vs-v2/#post-477587

**Comment by Stiofan** [comment]
@picocodes take a look at how it was implemented in v1 and try and improve on it if you can https://ppldb.com/release2/wp-admin/edit.php?post_type=gd_place

**Comment by picocodes** [comment]
@Stiofan on it
