### ISSUE TITLE
Bug - Preview on frontend edit for published listing -> errors

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#721]
To recreate

Add listing on frontend https://ppldb.com/v2/add-listing/
Preview before submit - works
Submit
View listing on frontend
Edit on frontend
Preview listing before submit -> Errors below

Fix - disable location manager

Notice: Trying to get property of non-object in /home/ppldb/public_html/v2/wp-content/plugins/geodirectory/includes/post-functions.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /home/ppldb/public_html/v2/wp-content/plugins/geodirectory/includes/post-functions.php:42) in /home/ppldb/public_html/v2/wp-includes/pluggable.php on line 1251

Warning: Cannot modify header information - headers already sent by (output started at /home/ppldb/public_html/v2/wp-content/plugins/geodirectory/includes/post-functions.php:42) in /home/ppldb/public_html/v2/wp-includes/pluggable.php on line 1254

**Comment by kprajapatii** [comment]
I can't replicate. I tested on my local site and on https://ppldb.com/v2/, at both site can't replicate. See places/united-states/new-jersey/camden/feature/preview-test/

@alexrollin

**Comment by alexrollin** [comment]
I upgraded v2 with 20056 last night. must be a fix in there.
