### ISSUE TITLE
Embedable Ratings Badge Add-on 

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#738]
We absolutely need an add-on that allows the listings owner to get the embed code for a widget showing their business ratings. 

Think Trip Advisor.

This will be the best way for our customers to get links from their listing owners websites and increase rankings

Thanks!

**Comment by pol76** [comment]
@Stiofan please let's discuss this when you have a sec.

**Comment by pol76** [comment]
example https://www.tripadvisor.com/TripAdvisorInsights/w832

**Comment by Stiofan** [comment]
Should this be core or addon?

**Comment by Guust-Flater** [comment]
Just a quick thought: should it be available for selected price packages only? Although the main benefit is to the GD site owner, there may be occasions where this may be a good idea.
But need to consider if the links from the customer site go dead because the price package expire....

**Comment by pol76** [comment]
@Stiofan add-on

@Guust-Flater if we make this a custom field, it shouldn't be difficult to restrict it. The code could continue to work after expiration...

@Stiofan is it possible to make it a custom field that only appears to listings authors? It could be a link saying: Embed your Ratings. Once clicked a modal window with the embed code pops up. 

What do you think?

Let us know...

**Comment by alexrollin** [comment]
Member requests
https://wpgeodirectory.com/support/topic/widget-code-to-embed-for-listing-owners/
