### ISSUE TITLE
ER Font Awesome Pro

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#760]
Allow snippet enabling of FA 5 Pro
https://kb.wpbeaverbuilder.com/article/732-add-font-awesome-5-pro-icons

member waiting updates.
https://wpgeodirectory.com/support/topic/using-font-awesome-pro/#post-486599

**Comment by Stiofan** [comment]
Still lacking info on even what the pro CDN url is, they seem to not show you unless you have a pro licence

**Comment by Stiofan** [comment]
* Font Awesome Pro now supported - ADDED
* Font Awesome Kits now supported - ADDED
