### ISSUE TITLE
Bug - iFrame embed video heights being overridden by GD CSS

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#763]
Several members have reported this issue.

https://ppldb.com/v2/places/united-states/new-jersey/pennsauken-township/attractions-1/video-test-3/

![image](https://user-images.githubusercontent.com/114659/57890560-4e611e00-7838-11e9-8489-c8a95428add2.png)

![image](https://user-images.githubusercontent.com/114659/57890574-5c16a380-7838-11e9-84a7-b0a70aaf5a7e.png)

**Comment by alexrollin** [comment]
if fixed, please notify:
https://wpgeodirectory.com/support/topic/youtube-height-is-small/

**Comment by alexrollin** [comment]
https://elba-island.virtualelba.it/elba/beaches-elba-island/enfola-beach-elba-island/
![image](https://user-images.githubusercontent.com/114659/58001656-68bb2600-7adc-11e9-91d1-8e3c0ebba627.png)

![image](https://user-images.githubusercontent.com/114659/58001636-58a34680-7adc-11e9-9c14-844ba49b0dd1.png)

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/embed-content-size-limit/#post-487942
https://wpgeodirectory.com/support/topic/video-on-details-page/

**Comment by 1naveengiri** [comment]
@Stiofan Please check and merge the pull request.
