### ISSUE TITLE
ER: Yoast breadcrumbs, remove part

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#774]
Member requests ability to remove part of the breadcrumb
https://wpgeodirectory.com/support/topic/ungly-breadcrumbs/#post-488113

**Comment by Stiofan** [comment]
I have added a code snippet for the user https://wpgeodirectory.com/support/topic/ungly-breadcrumbs/#post-490612

Breadcrumbs are based on query variables so i don't think a option here is the best idea.
