### ISSUE TITLE
Bug - Yoast doesn't show categories on a category archive page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#791]
Category output missing here: 
https://ppldb.com/v2/wp-admin/post.php?post=9&action=edit&classic-editor

https://ppldb.com/v2/places/category/attractions-1/

![image](https://user-images.githubusercontent.com/114659/58676915-46d26680-835a-11e9-8bc3-12a56f6edd00.png)

Reported here: 
https://wpgeodirectory.com/support/topic/breadcrumb-not-working-for-categories/#post-490116

**Comment by Stiofan** [comment]
fixed and will be in next release
