### ISSUE TITLE
ER New Addon for screenshots for listings with no images

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#818]
https://wpgeodirectory.com/support/topic/plugin-idea-if-listing-has-no-photo-but-has-a-website-take-a-screenshot-and-us/#post-492351

**Comment by pol76** [comment]
Are we working on this @Stiofan ?

**Comment by pol76** [comment]
Pre-sale question from a visitor: Hey, apart from uploaded images, is there a plugin or add-on that can use something like shrink the web to grab a website screenshot to autopopulate an image?

**Comment by picocodes** [comment]
@pol76 kindly assign me this task.

**Comment by picocodes** [comment]
What will be the name of the addon?

**Comment by pol76** [comment]
Website's screenshot for listing gallery

**Comment by picocodes** [comment]
https://apiflash.com/

https://screenshotlayer.com/

These two APIs seem reliable and both have a free plan. We can use one of them

**Comment by Stiofan** [comment]
This is mostly done, i'll finish it off.

**Comment by alexrollin** [comment]
Another request for this
https://wpgeodirectory.com/support/topic/refresh-screenshot-of-a-website/

**Comment by alexrollin** [comment]
added
