### ISSUE TITLE
Business Hours: check how feasible to set hours when close time falls on next day

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#822]
See https://wpgeodirectory.com/support/topic/gd-business-hours-8/

**Comment by Stiofan** [comment]
https://wpgeodirectory.com/support/topic/business-hours-13/

**Comment by alexrollin** [comment]
another request
https://wpgeodirectory.com/support/topic/open-time-works-randomly/#post-506515

**Comment by Stiofan** [comment]
@kprajapatii lets discuss the best approach on slack, ping me when u have time.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/e50f61ac7badf9bc40fd2dc741c8daa4a54e6969
