### ISSUE TITLE
Bug BB Archive item with widgets no output

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#824]
CPT Settings https://ppldb.com/beaver/wp-admin/edit.php?page=gd_dams-settings&tab=cpt&post_type=gd_dams
CPT Archive https://ppldb.com/beaver/dams/
![image](https://user-images.githubusercontent.com/114659/59425085-8dea3e00-8dd5-11e9-9e88-d7db6d99f6b8.png)

Reporting topic
https://wpgeodirectory.com/support/topic/bb-issue/

**Comment by alexrollin** [comment]
Also the output is being stripped of columns, css, and BB logic isn't being executed.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/fced3726a4155f29cc0b6540e3b87d92251abd99

**Comment by alexrollin** [comment]
I looked at this some more. Please take a look a the pages again.
When the pages have rows or columns, all the inline CSS from those is being stripped out on output from GD Loop.
The shortcodes and widgets seem to be rendering, though.
https://ppldb.com/beaver/default-test-archive-widgets/ - the widgets page (no columns on output)

https://ppldb.com/beaver/default-test-gd-archive-item-shortcodes/ - shortcodes (no columns on output...a custom class was added to the columns .awesomeness and adding width to that will restore the columns

**Comment by alexrollin** [comment]
https://ppldb.com/beaver/default-test-gd-archive-item-shortcodes/

![image](https://user-images.githubusercontent.com/114659/60377139-4938e680-9a14-11e9-9c74-a912b2e2ba5e.png)

https://ppldb.com/beaver/dams/

![image](https://user-images.githubusercontent.com/114659/60377171-b0ef3180-9a14-11e9-955b-346b598770b3.png)

**Comment by Stiofan** [comment]
@kprajapatii BB creates a custom CSS file in cache for each page, i think we need to add the ARCHIVE ITEM file to the ARCHIVE output.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/1c240b9c9512b9277971dcfc874bf6bd41b5a99a

See https://ppldb.com/beaver/dams/

**Comment by alexrollin** [comment]
This is not resolved. Only shortcodes work, not widgets.

**Comment by kprajapatii** [comment]
Fixec via https://github.com/AyeCode/geodirectory/commit/a2f8d904e9d3b323448e152e84a2a127ea17abcf
