### ISSUE TITLE
Bug - Conflict with WP Revisions

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#834]
Members are reporting they cannot save custom fields through front or backend editor.

Reports:

FTP https://wpgeodirectory.com/support/topic/when-adding-a-new-listing-location-doesnt-save/page/2/#post-494495
WPADMIN https://wpgeodirectory.com/support/topic/after-v2-update-many-problems/#post-494658

https://wpgeodirectory.com/support/topic/geo-directory-not-saving-posts/#post-494680

**Comment by kprajapatii** [comment]
https://wpgeodirectory.com/support/topic/add-listing-page-unavailable/

**Comment by Stiofan** [comment]
fixed in latest release
