### ISSUE TITLE
Real Estate dummy data bug

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#844]
If I create a new CPT Property with the pricing manager installed and try to add dummy data, listings will come without custom fields, because they need to be enabled for the price : free listing package.

That's bad UX....

Thanks

**Comment by pol76** [comment]
They should be enabled by default for all price packages created before adding dummy data.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodir_payment_manager-v3/pull/44/commits/6ad5472df8b2ddb1092f8bba207b009086de8f32
