### ISSUE TITLE
Regenerate Featured Images for src set refresh of attachments table

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#850]
Currently it is not possible to 'refresh' the actual images available for src sets for existing GD attachments without customization.

**Comment by alexrollin** [comment]
Member request https://wpgeodirectory.com/support/topic/force-slideshow-images-to-specific-size/#post-497183

@Stiofan @kprajapatii

**Comment by alexrollin** [comment]
Would be nice to load title and caption to media library as an option during this script
can it be per post type?

**Comment by kprajapatii** [comment]
See https://github.com/AyeCode/geodirectory/issues/1615
