### ISSUE TITLE
ER Filter for geodir_listing_belong_to_user

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#852]
https://github.com/AyeCode/geodirectory/blob/master/includes/post-functions.php#L488

enabling a “listing-manager” who could edit a listing like the listing owner.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/854/commits/0405f5e7294773d52c8f778cd482a187d1c4a444
