### ISSUE TITLE
ER - GD Listings - option 'exclude current listing' for use on details page

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#855]
Several members have requested a GD Listings option to avoid showing the current post.
Especially useful for events.

one request
https://wpgeodirectory.com/support/topic/gd_listing-tag-without-the-current/#post-497108

**Comment by Stiofan** [comment]
Pretty sure this is now done by default since last release.
Ping me if you find it's now and i'll reopen.
