### ISSUE TITLE
OSM for import geolocation

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#856]
Please check if there is a reason we are not using this or if we just never added it.
https://github.com/AyeCode/geodirectory/blob/master/includes/admin/class-geodir-admin-import-export.php#L502

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/d719ebbdb141d7ff85318c4894ae9876b3e66d85
