### ISSUE TITLE
Cannot untick Show city in address

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#863]
https://ppldb.com/v2/wp-admin/edit.php?post_type=gd_place&page=gd_place-settings

If you untick it, it comes back ticked again.
![image](https://user-images.githubusercontent.com/114659/61390442-166b6b00-a8bb-11e9-84f5-e1f32fba6d5d.png)

Member report
https://wpgeodirectory.com/support/topic/supreme-detail-page-template-adress/#post-498039

**Comment by 1naveengiri** [comment]
Fixed https://github.com/AyeCode/geodir_location_manager-v2/pull/97
