### ISSUE TITLE
Search for a parent category should show listings in child categories

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#870]
right now archives are showing listings in the parent when a child cat has been selected, even if the parent is not.

this does not carry over to search, but it should

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/commit/43df066242932dbc65cfef74c61a9f48656bcc48 & 
https://github.com/AyeCode/geodir_advance_search_filters-v2/pull/37/commits/b554f39847d849a9e13837f14e3cadc3b16269da
