### ISSUE TITLE
Roadblock : Mandatory category map marker

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#882]
An opportunity to make setup faster and more user-friendly.

Instead of asking for a mandatory category map marker, let's add a nice default marker (same for all new categories) and the option to change it.

That way, users won't feel the need to stop adding their categories to search/create the markers and they can do that later without being stuck or having to add a default marker themselves.

See: https://wpgeodirectory.com/support/topic/why-are-map-icons-required-when-creating-cpt-categories/

**Comment by alexrollin** [comment]
This would be a good addition to the setup wizard, perhaps?

BUTTON - Add default map icon

**Comment by Stiofan** [comment]
![Screenshot from 2019-08-06 18-22-22](https://user-images.githubusercontent.com/10433311/62561489-3cab7780-b877-11e9-8417-d92b108902ab.png)
