### ISSUE TITLE
Private advertiser option (custom field checkbox)

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#885]
Hi,

please add this option that was available in PHPmydirectory.

A checkbox custom fields "Is private advertiser" if checked, hide the physical address on listings and don't show marker in maps.

Visible here: https://www.buyusedguns.com.au/

Thank you!

**Comment by alexrollin** [comment]
To keep in mind, if possible, 'obscured address' to indicate an 'area' (not trying to 'fix' area search, just maps) https://github.com/AyeCode/geodirectory/issues/891

**Comment by pol76** [comment]
@kiran @stiofan, this should be a really easy one to implement? Can we plan for it next?

**Comment by kprajapatii** [comment]
We can hide listing showing on map if ticked private via field, but for address need some more details.
We shows address data like country, region, city, street in different ways like post meta, post badge with own widget etc. So to hide address only limited to full listing address or it applies to street, city, region and country as well?

@pol76

**Comment by alexrollin** [comment]
Thinking out loud here

Should the field be called "Private Location" - instead of "Private Listing"?

Members have also asked for something that will resemble allowing a user to change the status of a listing, like making it draft.

Wondering if that might be a 'Private Listing" where it doesn't event show in Loop/GD Listings.

**Comment by Stiofan** [comment]
I would think only the street and GPS info must be hidden.  
For the map, what if we just center it on the city GPS info and add a big blue circle around that? 

Or maybe we add a new select option in address called "location privacy" with options like
- Show my location
- show only my city
- show only my region
- show only my country
- hide all my location info.

@alexrollin in regards to your comments:
1. I'm on with that wording, makes more sense.
2. Do you mean like a "mark as sold" thing?
3. I think for removing from the loop that's a different thing and should only be under admin control like maybe a CPT setting such as "Show to only logged in" or "Show to only X_user_roll"

**Comment by alexrollin** [comment]
This is my take on private listings - https://github.com/AyeCode/geodirectory/issues/1787

**Comment by alexrollin** [comment]
Field Label: Location Visibility (Private Location, Location Privacy)
Field Type: Select
Field Description: Adjust the location visibility for your listing.
Options:
 - Show complete address
 - Show city without map pin
 - Show region without map pin
 - Show country without map pin
 - Hide location

**Comment by pol76** [comment]
@stiofan, @kiran I provided the link to a website showing exactly what was requested. (no longer visible because they converted to GD already)

If the option to turn make address private, the listing is not showing in maps and the address is obfuscated (no matter what it is used to output it)

**We MUST stop turning simple things into complex things** that we end up not developing (because we never come to an agreement) and add the simple requested option instead and quickly. 

We always have the option to add more sophistication later.

**Comment by Stiofan** [comment]
moved to https://github.com/AyeCode/geodirectory/issues/1842
