### ISSUE TITLE
ER Conditional Fields

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#924]
If field A has value = x THEN show field B, else none
https://wpgeodirectory.com/support/topic/add-conditional-rules-to-form-fields/#post-507925
https://wpgeodirectory.com/support/topic/associating-custom-fields/#post-494995

**Comment by pol76** [comment]
another request https://wordpress.org/support/topic/custom-fields-hierarchical-chained-dependent-select-field/#post-14613518

We really need to work on this next for both UWP, GP, and GD.

**Comment by Stiofan** [comment]
OK, so lets find the best implementation of this and apply it.  If you know of any let us know. (currently researching)

**Comment by wpdev10** [comment]
Something like gravity forms provides. See https://docs.gravityforms.com/enable-conditional-logic/

**Comment by pol76** [comment]
We should add this to all 3 plugins. Not just GD. Ultimate Member has a pretty simple and straightforward implementation in their free plugin.

**Comment by alexrollin** [comment]
Request https://secure.helpscout.net/conversation/1572928838/22017/

**Comment by Stiofan** [comment]
@kprajapatii let's go over this next week and then I can write a full spec.  I think we can use the JS logic from super duper.
