### ISSUE TITLE
ER validation for Name and Email for logged out posting fields

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#930]
to prevent failed user registrations
field length for name
valid email format for email
https://wpgeodirectory.com/support/topic/add-listing-page-queries/page/2/#post-508543

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/933/commits/089d966ef0db15f53db04ed50f9053735ed4b2c5
