### ISSUE TITLE
No way to allow iframes

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#945]
iframes seem to be stripped now no matter what?

**Comment by kprajapatii** [comment]
Till v2.0.0.66 i found we didn't sanitize custom fields before saving so it allows script/html tags in custom fields for all field types. In v2.0.0.67 i have sanitized text fields by geodir_clean() and textarea & html fields by geodir_sanitize_textarea_field() & geodir_sanitize_html_field() functions. After release of v2.0.0.67 during testing found that geodir_sanitize_html_field() functions strips allows only tags which supported by wp_kses_allowed_html( 'post' ).
So in ope of my recent push i have allowed iframe tag in html fields and also added filter so in case some customer wants to allow more tags(one of customer want to use script tags anyhow). 
See https://github.com/AyeCode/geodirectory/commit/349b8c21e4c34ea7c7dcf17e404fe7ddee42542a#diff-c308e6c7b1c93bec1d76d4e0ba557b66R1264

Let me know your comments.

**Comment by Stiofan** [comment]
Thanks!
