### ISSUE TITLE
Few suggestions and inputs in GD setup wizard.

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/geodirectory#96]
Please see following screenshots:

![1](https://user-images.githubusercontent.com/32451578/37455072-3d01679a-2862-11e8-96cc-7093c0d6c9c5.png)

![2](https://user-images.githubusercontent.com/32451578/37455083-46795dc8-2862-11e8-8464-43ae1f0b8917.png)

![3](https://user-images.githubusercontent.com/32451578/37455088-4c49d2dc-2862-11e8-9b70-6d71ac05a4a2.png)

Let me know if you need more details to regenerate any thing.

**Comment by Stiofan** [comment]
i have implemented everything apart from the first image which i don't agree with.
Thanks for the feedback :)
