### ISSUE TITLE
Search console errors

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#964]
Google Search Console marks all page we use as templates as 500 errors.

If we can, we should either redirect them or noindex them.

**Comment by Stiofan** [comment]
We currently show a message to normal users, we do nothing for admins as builders sometimes need to view them on frontend.  I have set a 301 perminant re-direct to home for normal users now.

**Comment by kprajapatii** [comment]
FYI: I have added already some code to exclude GD template pages from Yoast XML page sitemap. It will be in v2.0.0.68.
 
See https://github.com/AyeCode/geodirectory/commit/2f77a914f87d8bb4c735fba19d0faf85bf3e658e
