### ISSUE TITLE
Conflict with rank match

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#968]
We are using #new_post_type element id for grabbing post type. 

but rankmatch also using same id for showing notice. it creating conflict issue and causing following issue.
https://wpgeodirectory.com/support/topic/unable-to-add-field-in-advanced-search/

**Comment by Stiofan** [comment]
I can't recreate this.  Is it still an issue?

**Comment by 1naveengiri** [comment]
already fixed in this commit.
https://github.com/AyeCode/geodirectory/commit/27115f6f9cedcecba21fa7a497392b318b8049cd
