### ISSUE TITLE
ER Move map updates listings

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#981]
If map is moved then listings moved outside the viewable map area are removed from the list.

https://wpgeodirectory.com/support/topic/zoom-parameters-filter-search-results/#post-517032

**Comment by Stiofan** [comment]
https://wpgeodirectory.com/support/topic/update-listings-as-map-moves-reopened/

**Comment by kprajapatii** [comment]
https://secure.helpscout.net/conversation/1405192622/13708#thread-4060675157
